### ISSUE TITLE
Error while loading plugin

### ISSUE THREAD

**Issue by NertzhulDEV** [PikaMug/Quests#1095]
>.... [17:24:03 INFO]: [Quests] Enabling Quests v3.8.8-b75
>.... [17:24:03 WARN]: Enabled plugin with unregistered PluginClassLoader Quests v3.8.8-b75
>.... [17:24:03 ERROR]: Error occurred while enabling Quests v3.8.8-b75 (Is it up to date?)
java.lang.IllegalArgumentException: The embedded resource 'lang/fil-PH/strings.yml' cannot be found in Quests jar
at me.blackvein.quests.Quests.saveResourceAs(Quests.java:435) ~[?:?]
at me.blackvein.quests.Quests.setupLang(Quests.java:408) ~[?:?]
at me.blackvein.quests.Quests.onEnable(Quests.java:152) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-243]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-243]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-243]
at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:366) ~[?:?]
at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:318) ~[?:?]
at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:380) ~[?:?]
at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122) ~[?:?]
at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.14.4.jar:git-Paper-243]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.4.jar:git-Paper-243]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1804) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1612) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1158) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-243]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
>.... [17:24:03 INFO]: [Quests] Disabling Quests v3.8.8-b75
>.... [17:24:03 INFO]: [Quests] Saving Quester data...

**Comment by NertzhulDEV** [comment]
I just reloaded my server and now it's working again.

**Comment by PikaMug** [comment]
Seems to have been a conflict with PlugMan.
