### ISSUE TITLE
/questadmin causes error

### ISSUE THREAD

**Issue by Tsumitsuki** [PikaMug/Quests#1170]
Our Builder and Quest-Creator said he can't use /questadmin and the created npcs wouldn't saved.

i googled a bit but i can just find programming plugins and nothing realy relevant to this error (i guess). I've no idea what's causing that and how to fix it.
"Null" seems like theres some value missing to me. but where?

The console give out this error:

[10:26:19 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'questadmin' in plugin Quests v3.9.1-b37
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.15.2.jar:git-Paper-"2c37d2eb"]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-"2c37d2eb"]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:752) ~[patched_1.15.2.jar:git-Paper-"2c37d2eb"]
        at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1825) ~[patched_1.15.2.jar:git-Paper-"2c37d2eb"]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1633) ~[patched_1.15.2.jar:git-Paper-"2c37d2eb"]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Paper-"2c37d2eb"]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Paper-"2c37d2eb"]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-"2c37d2eb"]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-"2c37d2eb"]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-"2c37d2eb"]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-"2c37d2eb"]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-"2c37d2eb"]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-"2c37d2eb"]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-"2c37d2eb"]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-"2c37d2eb"]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015) ~[patched_1.15.2.jar:git-Paper-"2c37d2eb"]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938) ~[patched_1.15.2.jar:git-Paper-"2c37d2eb"]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.util.List (java.lang.Integer and java.util.List are in module java.base of loader 'bootstrap')
        at me.blackvein.quests.Quests.loadQuestRewards(Quests.java:1385) ~[?:?]
        at me.blackvein.quests.Quests.loadQuests(Quests.java:1356) ~[?:?]
        at me.blackvein.quests.Quests.reloadQuests(Quests.java:1150) ~[?:?]
        at me.blackvein.quests.listeners.CmdExecutor.adminReload(CmdExecutor.java:888) ~[?:?]
        at me.blackvein.quests.listeners.CmdExecutor.questAdminCommandHandler(CmdExecutor.java:305) ~[?:?]
        at me.blackvein.quests.listeners.CmdExecutor.onCommand(CmdExecutor.java:86) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.2.jar:git-Paper-"2c37d2eb"]
        ... 17 more

**Comment by Larskei-dev** [comment]
This error usually occurs when you setup a quest wrongly by having a typo in material names, or things like that, check your quests file.
