### ISSUE TITLE
Error in quests Chat messages.

### ISSUE THREAD

**Issue by assersson** [PikaMug/Quests#1210]
**What is your Quests version / build number (do _not_ say "latest")?**
Plugin Quests v3.9.3

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Taking a guest trought GUI gives an error and Start / End chat messages doesnt display on the chat.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/JCBnDft9

Heres the error log:

[WARNING] [Quests] Plugin Quests v3.9.3-b100 generated an exception whilst handling conversation input

org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled

at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:453) ~[spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:181) ~[spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:172) ~[spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.scheduleSyncRepeatingTask(CraftScheduler.java:167) ~[spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.scheduleSyncDelayedTask(CraftScheduler.java:131) ~[spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at org.bukkit.conversations.InactivityConversationCanceller.startTimer(InactivityConversationCanceller.java:51) ~[spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at org.bukkit.conversations.InactivityConversationCanceller.cancelBasedOnInput(InactivityConversationCanceller.java:37) ~[spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:227) ~[spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at org.bukkit.craftbukkit.v1_15_R1.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:59) [spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at org.bukkit.craftbukkit.v1_15_R1.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1190) [spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at net.minecraft.server.v1_15_R1.PlayerConnection$2.run(PlayerConnection.java:1509) [spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1049) [spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:406) [spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984) [spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824) [spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]

**Comment by PikaMug** [comment]
Thanks for the report. I'm unable to replicate this by accepting a quest via GUI and suspect that something else might be the cause. Could you please share the server log _**using Pastebin or Hastebin.com**_?

**Comment by PikaMug** [comment]
Closing due to lack of response from OP.
