### ISSUE TITLE
Quests warnings 3.9.3 e 3.9.4

### ISSUE THREAD

**Issue by RyuzakiL07** [PikaMug/Quests#1258]
I'm using the google translator, sorry for any mistake.

The plug-in is flooding the console with warnings when the player finishes a mission or decides to do so.

Quests 3.9.3
Quests 3.9.4 

**When the player accepts a mission!**

[[19:06:04] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[19:06:04] [Server thread/WARN]:        at sun.reflect.GeneratedMethodAccessor109.invoke(Unknown Source)
[19:06:04] [Server thread/WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[19:06:04] [Server thread/WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[19:06:04] [Server thread/WARN]:        at rush.apis.TitleAPI.broadcastTitle(TitleAPI.java:40)
[19:06:04] [Server thread/WARN]:        at rush.comandos.ComandoTitle.onCommand(ComandoTitle.java:30)
[19:06:04] [Server thread/WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[19:06:04] [Server thread/WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[19:06:04] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:723)
[19:06:04] [Server thread/WARN]:        at me.blackvein.quests.Quester.takeQuest(Quester.java:551)
[19:06:04] [Server thread/WARN]:        at me.blackvein.quests.Quests$QuestAcceptPrompt.acceptInput(Quests.java:382)
[19:06:04] [Server thread/WARN]:        at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:234)
[19:06:04] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_15_R1.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:59)
[19:06:04] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_15_R1.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1225)
[19:06:04] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.PlayerConnection$2.run(PlayerConnection.java:1509)
[19:06:04] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1049)
[19:06:04] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:406)
[19:06:04] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984)
[19:06:04] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824)
[19:06:04] [Server thread/WARN]:        at java.lang.Thread.run(Unknown Source)
[19:06:04] [Server thread/WARN]: Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 27 path $.text
[19:06:04] [Server thread/WARN]:        at com.google.gson.internal.Streams.parse(Streams.java:60)
[19:06:04] [Server thread/WARN]:        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:65)
[19:06:04] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.ChatDeserializer.a(SourceFile:494)
[19:06:04] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.ChatDeserializer.a(SourceFile:519)
[19:06:04] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.IChatBaseComponent$ChatSerializer.a(SourceFile:399)
[19:06:04] [Server thread/WARN]:        ... 19 more
[19:06:04] [Server thread/WARN]: Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 27 path $.text
[19:06:04] [Server thread/WARN]:        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
[19:06:04] [Server thread/WARN]:        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:491)
[19:06:04] [Server thread/WARN]:        at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414)
[19:06:04] [Server thread/WARN]:        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:738)
[19:06:04] [Server thread/WARN]:        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714)
[19:06:04] [Server thread/WARN]:        at com.google.gson.internal.Streams.parse(Streams.java:48)
[19:06:04] [Server thread/WARN]:        ... 23 more
[19:06:04] [Server thread/INFO]: Title enviado com sucesso.
[19:06:04] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[19:06:04] [Server thread/WARN]:        at sun.reflect.GeneratedMethodAccessor109.invoke(Unknown Source)
[19:06:04] [Server thread/WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[19:06:04] [Server thread/WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[19:06:04] [Server thread/WARN]:        at rush.apis.TitleAPI.broadcastTitle(TitleAPI.java:40)
[19:06:04] [Server thread/WARN]:        at rush.comandos.ComandoTitle.onCommand(ComandoTitle.java:30)
[19:06:04] [Server thread/WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[19:06:04] [Server thread/WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[19:06:04] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:723)
[19:06:04] [Server thread/WARN]:        at me.blackvein.quests.Quester.takeQuest(Quester.java:554)
[19:06:04] [Server thread/WARN]:        at me.blackvein.quests.Quests$QuestAcceptPrompt.acceptInput(Quests.java:382)
[19:06:04] [Server thread/WARN]:        at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:234)
[19:06:04] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_15_R1.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:59)
[19:06:04] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_15_R1.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1225)
[19:06:04] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.PlayerConnection$2.run(PlayerConnection.java:1509)
[19:06:04] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1049)
[19:06:04] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:406)
[19:06:04] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984)
[19:06:04] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824)
[19:06:04] [Server thread/WARN]:        at java.lang.Thread.run(Unknown Source)
[19:06:04] [Server thread/WARN]: Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 30 path $.text
[19:06:04] [Server thread/WARN]:        at com.google.gson.internal.Streams.parse(Streams.java:60)
[19:06:04] [Server thread/WARN]:        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:65)
[19:06:04] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.ChatDeserializer.a(SourceFile:494)
[19:06:04] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.ChatDeserializer.a(SourceFile:519)
[19:06:04] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.IChatBaseComponent$ChatSerializer.a(SourceFile:399)
[19:06:04] [Server thread/WARN]:        ... 19 more
[19:06:04] [Server thread/WARN]: Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 30 path $.text
[19:06:04] [Server thread/WARN]:        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
[19:06:04] [Server thread/WARN]:        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:491)
[19:06:04] [Server thread/WARN]:        at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414)
[19:06:04] [Server thread/WARN]:        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:738)
[19:06:04] [Server thread/WARN]:        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714)
[19:06:04] [Server thread/WARN]:        at com.google.gson.internal.Streams.parse(Streams.java:48)
[19:06:04] [Server thread/WARN]:        ... 23 more
[19:06:04] [Server thread/INFO]: Title enviado com sucesso.

**Error when the mission is completed ...**

[19:07:18] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[19:07:18] [Server thread/WARN]:        at sun.reflect.GeneratedMethodAccessor109.invoke(Unknown Source)
[19:07:18] [Server thread/WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[19:07:18] [Server thread/WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[19:07:18] [Server thread/WARN]:        at rush.apis.TitleAPI.broadcastTitle(TitleAPI.java:40)
[19:07:18] [Server thread/WARN]:        at rush.comandos.ComandoTitle.onCommand(ComandoTitle.java:30)
[19:07:18] [Server thread/WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[19:07:18] [Server thread/WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[19:07:18] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:723)
[19:07:18] [Server thread/WARN]:        at me.blackvein.quests.Quest.completeQuest(Quest.java:586)
[19:07:18] [Server thread/WARN]:        at me.blackvein.quests.Quest.nextStage(Quest.java:196)
[19:07:18] [Server thread/WARN]:        at me.blackvein.quests.Quester.finishObjective(Quester.java:2456)
[19:07:18] [Server thread/WARN]:        at me.blackvein.quests.Quester.reachLocation(Quester.java:2096)
[19:07:18] [Server thread/WARN]:        at me.blackvein.quests.listeners.PlayerListener.playerMove(PlayerListener.java:1074)
[19:07:18] [Server thread/WARN]:        at me.blackvein.quests.listeners.PlayerListener.onPlayerMove(PlayerListener.java:1056)
[19:07:18] [Server thread/WARN]:        at sun.reflect.GeneratedMethodAccessor60.invoke(Unknown Source)
[19:07:18] [Server thread/WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[19:07:18] [Server thread/WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[19:07:18] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315)
[19:07:18] [Server thread/WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[19:07:18] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
[19:07:18] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
[19:07:18] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:998)
[19:07:18] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.PacketPlayInFlying.a(SourceFile:122)
[19:07:18] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:56)
[19:07:18] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)
[19:07:18] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
[19:07:18] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144)
[19:07:18] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[19:07:18] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118)
[19:07:18] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918)
[19:07:18] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911)
[19:07:18] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(SourceFile:103)
[19:07:18] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:894)
[19:07:18] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828)
[19:07:18] [Server thread/WARN]:        at java.lang.Thread.run(Unknown Source)
[19:07:18] [Server thread/WARN]: Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 27 path $.text
[19:07:18] [Server thread/WARN]:        at com.google.gson.internal.Streams.parse(Streams.java:60)
[19:07:18] [Server thread/WARN]:        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:65)
[19:07:18] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.ChatDeserializer.a(SourceFile:494)
[19:07:18] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.ChatDeserializer.a(SourceFile:519)
[19:07:18] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.IChatBaseComponent$ChatSerializer.a(SourceFile:399)
[19:07:18] [Server thread/WARN]:        ... 35 more
[19:07:18] [Server thread/WARN]: Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 27 path $.text
[19:07:18] [Server thread/WARN]:        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
[19:07:18] [Server thread/WARN]:        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:491)
[19:07:18] [Server thread/WARN]:        at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414)
[19:07:18] [Server thread/WARN]:        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:738)
[19:07:18] [Server thread/WARN]:        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714)
[19:07:18] [Server thread/WARN]:        at com.google.gson.internal.Streams.parse(Streams.java:48)
[19:07:18] [Server thread/WARN]:        ... 39 more
[19:07:18] [Server thread/INFO]: Title enviado com sucesso.
[19:07:18] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[19:07:18] [Server thread/WARN]:        at sun.reflect.GeneratedMethodAccessor109.invoke(Unknown Source)
[19:07:18] [Server thread/WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[19:07:18] [Server thread/WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[19:07:18] [Server thread/WARN]:        at rush.apis.TitleAPI.broadcastTitle(TitleAPI.java:40)
[19:07:18] [Server thread/WARN]:        at rush.comandos.ComandoTitle.onCommand(ComandoTitle.java:30)
[19:07:18] [Server thread/WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[19:07:18] [Server thread/WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[19:07:18] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:723)
[19:07:18] [Server thread/WARN]:        at me.blackvein.quests.Quest.completeQuest(Quest.java:589)
[19:07:18] [Server thread/WARN]:        at me.blackvein.quests.Quest.nextStage(Quest.java:196)
[19:07:18] [Server thread/WARN]:        at me.blackvein.quests.Quester.finishObjective(Quester.java:2456)
[19:07:18] [Server thread/WARN]:        at me.blackvein.quests.Quester.reachLocation(Quester.java:2096)
[19:07:18] [Server thread/WARN]:        at me.blackvein.quests.listeners.PlayerListener.playerMove(PlayerListener.java:1074)
[19:07:18] [Server thread/WARN]:        at me.blackvein.quests.listeners.PlayerListener.onPlayerMove(PlayerListener.java:1056)
[19:07:18] [Server thread/WARN]:        at sun.reflect.GeneratedMethodAccessor60.invoke(Unknown Source)
[19:07:18] [Server thread/WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[19:07:18] [Server thread/WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[19:07:18] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315)
[19:07:18] [Server thread/WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[19:07:18] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
[19:07:18] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
[19:07:18] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:998)
[19:07:18] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.PacketPlayInFlying.a(SourceFile:122)
[19:07:18] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:56)
[19:07:18] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)
[19:07:18] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
[19:07:18] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144)
[19:07:18] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[19:07:18] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118)
[19:07:18] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918)
[19:07:18] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911)
[19:07:18] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(SourceFile:103)
[19:07:18] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:894)
[19:07:18] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828)
[19:07:18] [Server thread/WARN]:        at java.lang.Thread.run(Unknown Source)
[19:07:18] [Server thread/WARN]: Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 30 path $.text
[19:07:18] [Server thread/WARN]:        at com.google.gson.internal.Streams.parse(Streams.java:60)
[19:07:18] [Server thread/WARN]:        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:65)
[19:07:18] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.ChatDeserializer.a(SourceFile:494)
[19:07:18] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.ChatDeserializer.a(SourceFile:519)
[19:07:18] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.IChatBaseComponent$ChatSerializer.a(SourceFile:399)
[19:07:18] [Server thread/WARN]:        ... 35 more
[19:07:18] [Server thread/WARN]: Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 30 path $.text
[19:07:18] [Server thread/WARN]:        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
[19:07:18] [Server thread/WARN]:        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:491)
[19:07:18] [Server thread/WARN]:        at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414)
[19:07:18] [Server thread/WARN]:        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:738)
[19:07:18] [Server thread/WARN]:        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714)
[19:07:18] [Server thread/WARN]:        at com.google.gson.internal.Streams.parse(Streams.java:48)
[19:07:18] [Server thread/WARN]:        ... 39 more
[19:07:18] [Server thread/INFO]: Title enviado com sucesso.
[19:07:22] [Craft Scheduler Thread - 20/INFO]: [Metrics] Connection timed out: connect
>

**Comment by PikaMug** [comment]
Problem is with TitleAPI, not Quests.

**Comment by RyuzakiL07** [comment]
Good afternoon, sorry, I really don't know how to solve this, can you help me? what would be this TitleAPI Where can I find it? would it be a plugin? because if it is, I don't have it, should I put it on?

Sorry for any mistake, I'm using google translator.

**Comment by RyuzakiL07** [comment]
Good afternoon, sorry, I really don't know how to solve this, can you help
me? what would be this TitleAPI Where can I find it? would it be a plugin?
because if it is, I don't have it, should I put it on?

Sorry for any mistake, I'm using google translator.
Sorry to send it here and on github I was a little confused about where she
responds, you know how the google translator is, it doesn't help very well
...


Em dom., 26 de abr. de 2020 às 02:03, PikaMug <notifications@github.com>
escreveu:

**Comment by PikaMug** [comment]
TitleAPI is part of another resource you are using, located at https://github.com/eduardo-mior/System

Since this is not an issue with Quests, I am unable to assist you further.
