### ISSUE TITLE
Plugin is currently loading. Please try again later.

### ISSUE THREAD

**Issue by Ripperinoo** [PikaMug/Quests#1301]
My quests version: 3.9.4
My spigot version: 1.8.8

I downloaded this plugin today but it gives error on console when starting and when i write the chat /quest or /quests it says plugin is currently loading please try again later. I love your plugin so much but it just gives error and i don't know how i can solve this. I hope you can help me.

**Comment by PikaMug** [comment]
Thanks for the report. Please share your startup log, usually located at _serverFolder/logs/latest.log_

**Comment by Ripperinoo** [comment]
[17:16:08] [Server thread/WARN]: [Quests] Task #26 for Quests v3.9.4-b${env.BUILD_NUMBER} generated an exception
java.lang.NoSuchMethodError: org.bukkit.Material.matchMaterial(Ljava/lang/String;Z)Lorg/bukkit/Material;
	at me.blackvein.quests.util.ItemUtil.processItemStack(ItemUtil.java:178) ~[?:?]
	at me.blackvein.quests.util.ItemUtil.readItemStack(ItemUtil.java:341) ~[?:?]
	at me.blackvein.quests.Quests.loadQuestRequirements(Quests.java:1684) ~[?:?]
	at me.blackvein.quests.Quests.loadQuests(Quests.java:1445) ~[?:?]
	at me.blackvein.quests.Quests$2.run(Quests.java:518) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[server.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [server.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [server.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [server.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [server.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [server.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
[17:16:08] [Craft Scheduler Thread -

**Comment by PikaMug** [comment]
Closing as OP did not provide the requested information.

There should be a line at startup, or immediately proceeding that error, which tells you about an invalid material in your quest file. You must correct that issue before using the plugin.
