### ISSUE TITLE
Bug in server files

### ISSUE THREAD

**Issue by Arno2596** [PikaMug/Quests#1354]
Recently i found this, and i do not know how to fix:

> Could not pass event PlayerCommandPreprocessEvent to Quests v3.9.1-b86
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[craftbukkit-1.12.2-SNAPSHOT.jar:git-Spigot-642f6d2-fbe3046]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit-1.12.2-SNAPSHOT.jar:git-Spigot-642f6d2-fbe3046]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [craftbukkit-1.12.2-SNAPSHOT.jar:git-Spigot-642f6d2-fbe3046]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [craftbukkit-1.12.2-SNAPSHOT.jar:git-Spigot-642f6d2-fbe3046]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1389) [craftbukkit-1.12.2-SNAPSHOT.jar:git-Spigot-642f6d2-fbe3046]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [craftbukkit-1.12.2-SNAPSHOT.jar:git-Spigot-642f6d2-fbe3046]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [craftbukkit-1.12.2-SNAPSHOT.jar:git-Spigot-642f6d2-fbe3046]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [craftbukkit-1.12.2-SNAPSHOT.jar:git-Spigot-642f6d2-fbe3046]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit-1.12.2-SNAPSHOT.jar:git-Spigot-642f6d2-fbe3046]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_251]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [craftbukkit-1.12.2-SNAPSHOT.jar:git-Spigot-642f6d2-fbe3046]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [craftbukkit-1.12.2-SNAPSHOT.jar:git-Spigot-642f6d2-fbe3046]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [craftbukkit-1.12.2-SNAPSHOT.jar:git-Spigot-642f6d2-fbe3046]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [craftbukkit-1.12.2-SNAPSHOT.jar:git-Spigot-642f6d2-fbe3046]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [craftbukkit-1.12.2-SNAPSHOT.jar:git-Spigot-642f6d2-fbe3046]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.NullPointerException
        at me.blackvein.quests.listeners.PlayerListener.onPlayerCommandPreprocess(PlayerListener.java:478) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor318.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[craftbukkit-1.12.2-SNAPSHOT.jar:git-Spigot-642f6d2-fbe3046]
        ... 16 more

**Comment by PikaMug** [comment]
Closing as OP did not follow issue template.

Update to the latest version (3.9.5) and make a new ticket if the issue persists.
