### ISSUE TITLE
1.8 BUG

### ISSUE THREAD

**Issue by heitormsb** [PikaMug/Quests#1377]
I have solution for this?

[20:31:11 WARN]: java.lang.reflect.InvocationTargetException
[20:31:11 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:31:11 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:31:11 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:31:11 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
[20:31:11 WARN]: at rush.apis.TitleAPI.broadcastTitle(TitleAPI.java:40)
[20:31:11 WARN]: at rush.comandos.ComandoTitle.onCommand(ComandoTitle.java:30)
[20:31:11 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[20:31:11 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[20:31:11 WARN]: at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[20:31:11 WARN]: at me.blackvein.quests.Quester.takeQuest(Quester.java:564)
[20:31:11 WARN]: at me.blackvein.quests.listeners.PlayerListener.onInventoryClickEvent(PlayerListener.java:120)
[20:31:11 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:31:11 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:31:11 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:31:11 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
[20:31:11 WARN]: at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[20:31:11 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[20:31:11 WARN]: at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[20:31:11 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[20:31:11 WARN]: at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1630)
[20:31:11 WARN]: at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31)
[20:31:11 WARN]: at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9)
[20:31:11 WARN]: at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[20:31:11 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[20:31:11 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[20:31:11 WARN]: at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[20:31:11 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[20:31:11 WARN]: at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[20:31:11 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[20:31:11 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[20:31:11 WARN]: at java.lang.Thread.run(Thread.java:748)
[20:31:11 WARN]: Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 27
[20:31:11 WARN]: at com.google.gson.internal.Streams.parse(Streams.java:56)
[20:31:11 WARN]: at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:54)
[20:31:11 WARN]: at com.google.gson.Gson.fromJson(Gson.java:803)
[20:31:11 WARN]: at com.google.gson.Gson.fromJson(Gson.java:717)
[20:31:11 WARN]: at com.google.gson.Gson.fromJson(Gson.java:768)
[20:31:11 WARN]: at com.google.gson.Gson.fromJson(Gson.java:689)
[20:31:11 WARN]: at net.minecraft.server.v1_8_R3.IChatBaseComponent$ChatSerializer.a(SourceFile:199)
[20:31:11 WARN]: ... 31 more
[20:31:11 WARN]: Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 27
[20:31:11 WARN]: at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1505)
[20:31:11 WARN]: at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:480)
[20:31:11 WARN]: at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:403)
[20:31:11 WARN]: at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:666)
[20:31:11 WARN]: at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:642)
[20:31:11 WARN]: at com.google.gson.internal.Streams.parse(Streams.java:44)
[20:31:11 WARN]: ... 37 more
[20:31:11 INFO]: Title enviado com sucesso.
[20:31:11 WARN]: java.lang.reflect.InvocationTargetException
[20:31:11 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:31:11 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:31:11 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:31:11 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
[20:31:11 WARN]: at rush.apis.TitleAPI.broadcastTitle(TitleAPI.java:40)
[20:31:11 WARN]: at rush.comandos.ComandoTitle.onCommand(ComandoTitle.java:30)
[20:31:11 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[20:31:11 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[20:31:11 WARN]: at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[20:31:11 WARN]: at me.blackvein.quests.Quester.takeQuest(Quester.java:567)
[20:31:11 WARN]: at me.blackvein.quests.listeners.PlayerListener.onInventoryClickEvent(PlayerListener.java:120)
[20:31:11 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:31:11 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:31:11 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:31:11 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
[20:31:11 WARN]: at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[20:31:11 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[20:31:11 WARN]: at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[20:31:11 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[20:31:11 WARN]: at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1630)
[20:31:11 WARN]: at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31)
[20:31:11 WARN]: at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9)
[20:31:11 WARN]: at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[20:31:11 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[20:31:11 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[20:31:11 WARN]: at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[20:31:11 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[20:31:11 WARN]: at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[20:31:11 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[20:31:11 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[20:31:11 WARN]: at java.lang.Thread.run(Thread.java:748)
[20:31:11 WARN]: Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 30
[20:31:11 WARN]: at com.google.gson.internal.Streams.parse(Streams.java:56)
[20:31:11 WARN]: at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:54)
[20:31:11 WARN]: at com.google.gson.Gson.fromJson(Gson.java:803)
[20:31:11 WARN]: at com.google.gson.Gson.fromJson(Gson.java:768)
[20:31:11 WARN]: at com.google.gson.Gson.fromJson(Gson.java:717)
[20:31:11 WARN]: at com.google.gson.Gson.fromJson(Gson.java:689)
[20:31:11 WARN]: ... 31 more
[20:31:11 WARN]: at net.minecraft.server.v1_8_R3.IChatBaseComponent$ChatSerializer.a(SourceFile:199)
[20:31:11 WARN]: Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 30
[20:31:11 WARN]: at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1505)
[20:31:11 WARN]: at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:480)
[20:31:11 WARN]: at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:403)
[20:31:11 WARN]: at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:666)
[20:31:11 WARN]: at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:642)
[20:31:11 WARN]: ... 37 more
[20:31:11 WARN]: at com.google.gson.internal.Streams.parse(Streams.java:44)
[20:31:11 INFO]: Title enviado com sucesso.

**Comment by PikaMug** [comment]
Closing as OP did not follow issue template.

Also, this appears to be an issue with TitleAPI, not Quests.
