### ISSUE TITLE
NPE on first connect

### ISSUE THREAD

**Issue by SlimeDog** [PikaMug/Quests#1405]
**What is your Quests version / build number (do _not_ say "latest")?**
Java 14.0.2
Spigot 1.16.3
Quests 3.9.6-b143

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**

On first player connect after server start-up:
```
[03:29:57] [Server thread/WARN]: [Quests] Task #8774 for Quests v3.9.6-b143 generated an exception
java.lang.NullPointerException: null
        at me.blackvein.quests.Quester.canUseCompass(Quester.java:3825) ~[?:?]
        at me.blackvein.quests.listeners.PlayerListener$3.run(PlayerListener.java:811) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.16.3.jar-2020-09-11-1705:git-Spigot-2740d5a-d5a7296]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[spigot-1.16.3.jar-2020-09-11-1705:git-Spigot-2740d5a-d5a7296]
        at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1059) ~[spigot-1.16.3.jar-2020-09-11-1705:git-Spigot-2740d5a-d5a7296]
        at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:349) ~[spigot-1.16.3.jar-2020-09-11-1705:git-Spigot-2740d5a-d5a7296]
        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1007) ~[spigot-1.16.3.jar-2020-09-11-1705:git-Spigot-2740d5a-d5a7296]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:846) ~[spigot-1.16.3.jar-2020-09-11-1705:git-Spigot-2740d5a-d5a7296]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.3.jar-2020-09-11-1705:git-Spigot-2740d5a-d5a7296]
        at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by PikaMug** [comment]
Thanks for the report. Use https://ci.codemc.io/job/PikaMug/job/Quests/144/

**Comment by SlimeDog** [comment]
Yeah, I track dev updates. Thanks.
