### ISSUE TITLE
EventException on player connect

### ISSUE THREAD

**Issue by SlimeDog** [PikaMug/Quests#1441]
**What is your Quests version / build number (do _not_ say "latest")?**
Spigot 1.16.4
Quests 4.0.0-rc.2-b160

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
On player connect
```
[04:42:05] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to Quests v4.0.0-rc.2-b160
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.PlayerList.a(PlayerList.java:200) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.LoginListener.c(LoginListener.java:154) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.LoginListener.tick(LoginListener.java:53) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:219) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:130) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1126) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:355) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1007) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:846) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassCastException: class me.blackvein.quests.Quester cannot be cast to class java.lang.Comparable (me.blackvein.quests.Quester is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @55ed16c4; java.lang.Comparable is in module java.base of loader 'bootstrap')
        at java.util.concurrent.ConcurrentSkipListMap.cpr(ConcurrentSkipListMap.java:392) ~[?:?]
        at java.util.concurrent.ConcurrentSkipListMap.doPut(ConcurrentSkipListMap.java:636) ~[?:?]
        at java.util.concurrent.ConcurrentSkipListMap.putIfAbsent(ConcurrentSkipListMap.java:1787) ~[?:?]
        at java.util.concurrent.ConcurrentSkipListSet.add(ConcurrentSkipListSet.java:242) ~[?:?]
        at java.util.AbstractCollection.addAll(AbstractCollection.java:352) ~[?:?]
        at java.util.concurrent.ConcurrentSkipListSet.<init>(ConcurrentSkipListSet.java:141) ~[?:?]
        at me.blackvein.quests.Quests.setQuesters(Quests.java:337) ~[?:?]
        at me.blackvein.quests.listeners.PlayerListener.onPlayerJoin(PlayerListener.java:802) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        ... 14 more
```

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
Four default quests.

**Comment by PikaMug** [comment]
@SlimeDog Thanks for the report. This is an extension of #1439 

Please try the following development build:
https://ci.codemc.io/job/PikaMug/job/Quests/161/

**Comment by SlimeDog** [comment]
I'm not sure why it's closed. Anyway, on player connect:
```
[13:23:41] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to Quests v4.0.0-rc.2-b161
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.PlayerList.a(PlayerList.java:200) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.LoginListener.c(LoginListener.java:154) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.LoginListener.tick(LoginListener.java:53) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:219) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:130) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1126) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:355) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1007) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:846) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassCastException: class me.blackvein.quests.Quester cannot be cast to class java.lang.Comparable (me.blackvein.quests.Quester is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @393e2bc5; java.lang.Comparable is in module java.base of loader 'bootstrap')
        at java.util.concurrent.ConcurrentSkipListMap.cpr(ConcurrentSkipListMap.java:392) ~[?:?]
        at java.util.concurrent.ConcurrentSkipListMap.doPut(ConcurrentSkipListMap.java:636) ~[?:?]
        at java.util.concurrent.ConcurrentSkipListMap.putIfAbsent(ConcurrentSkipListMap.java:1787) ~[?:?]
        at java.util.concurrent.ConcurrentSkipListSet.add(ConcurrentSkipListSet.java:242) ~[?:?]
        at me.blackvein.quests.listeners.PlayerListener.onPlayerJoin(PlayerListener.java:801) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        ... 14 more
```

**Comment by PikaMug** [comment]
@SlimeDog It was done automatically.

https://ci.codemc.io/job/PikaMug/job/Quests/162/

**Comment by SlimeDog** [comment]
On player connect:
```
[14:48:40] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to Quests v4.0.0-rc.2-b162
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.PlayerList.a(PlayerList.java:200) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.LoginListener.c(LoginListener.java:154) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.LoginListener.tick(LoginListener.java:53) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:219) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:130) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1126) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:355) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1007) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:846) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassCastException: class me.blackvein.quests.Quester cannot be cast to class java.util.UUID (me.blackvein.quests.Quester is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @6cf19d85; java.util.UUID is in module java.base of loader 'bootstrap')
        at me.blackvein.quests.Quester.compareTo(Quester.java:74) ~[?:?]
        at java.util.concurrent.ConcurrentSkipListMap.cpr(ConcurrentSkipListMap.java:392) ~[?:?]
        at java.util.concurrent.ConcurrentSkipListMap.doPut(ConcurrentSkipListMap.java:636) ~[?:?]
        at java.util.concurrent.ConcurrentSkipListMap.putIfAbsent(ConcurrentSkipListMap.java:1787) ~[?:?]
        at java.util.concurrent.ConcurrentSkipListSet.add(ConcurrentSkipListSet.java:242) ~[?:?]
        at me.blackvein.quests.listeners.PlayerListener.onPlayerJoin(PlayerListener.java:801) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.16.4.jar-2020-11-04-0548:git-Spigot-37d799b-3eb7236]
        ... 14 more
```

**Comment by PikaMug** [comment]
@SlimeDog Thanks for your patience and continued feedback.

https://ci.codemc.io/job/PikaMug/job/Quests/163/

**Comment by SlimeDog** [comment]
Resolved with build 163. Thanks.
