### ISSUE TITLE
Quests won't load

### ISSUE THREAD

**Issue by Grievous07** [PikaMug/Quests#1472]
**Where else have you looked for answers to this question?**
Discord, FQA, youtube, and tired copy/paste error in google search

**Share your question with as much detail as possible?**
Every time I restart the server or do /questsadmin reload this all comes up. And I cant figure out how to fix it without completely uninstalling/reinstalling the plugin. Which I desperately don't want to do, as to not loose progress.
```25.11 09:08:16 [Server] INFO [Quests] Loaded language en-US. Translations via Crowdin
25.11 09:08:16 [Server] WARN me.blackvein.quests.exceptions.ConditionFormatException: stay-within-world is not a valid world, see condition of ID conditions.AdvSur.
25.11 09:08:16 [Server] WARN at me.blackvein.quests.Quests.loadCondition(Quests.java:3416)
25.11 09:08:16 [Server] WARN at me.blackvein.quests.Quests.loadQuestStages(Quests.java:2995)
25.11 09:08:16 [Server] WARN at me.blackvein.quests.Quests.loadQuests(Quests.java:1472)
25.11 09:08:16 [Server] WARN at me.blackvein.quests.Quests$3.run(Quests.java:1248)
25.11 09:08:16 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
25.11 09:08:16 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
25.11 09:08:16 [Server] WARN at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
25.11 09:08:16 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
25.11 09:08:16 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
25.11 09:08:16 [Server] WARN at java.lang.Thread.run(Thread.java:748)
25.11 09:08:16 [Server] WARN me.blackvein.quests.exceptions.ConditionFormatException: stay-within-world is not a valid world, see condition of ID conditions.AdvSur.
25.11 09:08:16 [Server] WARN at me.blackvein.quests.Quests.loadCondition(Quests.java:3416)
25.11 09:08:16 [Server] WARN at me.blackvein.quests.Quests.loadQuestStages(Quests.java:2995)
25.11 09:08:16 [Server] WARN at me.blackvein.quests.Quests.loadQuests(Quests.java:1472)
25.11 09:08:16 [Server] WARN at me.blackvein.quests.Quests$3.run(Quests.java:1248)
25.11 09:08:16 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
25.11 09:08:16 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
25.11 09:08:16 [Server] WARN at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
25.11 09:08:16 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
25.11 09:08:16 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
25.11 09:08:16 [Server] WARN at java.lang.Thread.run(Thread.java:748)
25.11 09:08:16 [Server] WARN me.blackvein.quests.exceptions.ConditionFormatException: stay-within-world is not a valid world, see condition of ID conditions.AdvSur.
25.11 09:08:16 [Server] WARN at me.blackvein.quests.Quests.loadCondition(Quests.java:3416)
25.11 09:08:16 [Server] WARN at me.blackvein.quests.Quests.loadQuestStages(Quests.java:2995)
25.11 09:08:16 [Server] WARN at me.blackvein.quests.Quests.loadQuests(Quests.java:1472)
25.11 09:08:16 [Server] WARN at me.blackvein.quests.Quests$3.run(Quests.java:1248)
25.11 09:08:16 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
25.11 09:08:16 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
25.11 09:08:16 [Server] WARN at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
25.11 09:08:16 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
25.11 09:08:16 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
25.11 09:08:16 [Server] WARN at java.lang.Thread.run(Thread.java:748)
25.11 09:08:16 [Server] WARN me.blackvein.quests.exceptions.ConditionFormatException: stay-within-world is not a valid world, see condition of ID conditions.AdvSur.
25.11 09:08:16 [Server] WARN at me.blackvein.quests.Quests.loadCondition(Quests.java:3416)
25.11 09:08:16 [Server] WARN at me.blackvein.quests.Quests.loadQuestStages(Quests.java:2995)
25.11 09:08:16 [Server] WARN at me.blackvein.quests.Quests.loadQuests(Quests.java:1472)
25.11 09:08:16 [Server] WARN at me.blackvein.quests.Quests$3.run(Quests.java:1248)
25.11 09:08:16 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
25.11 09:08:16 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
25.11 09:08:16 [Server] WARN at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
25.11 09:08:16 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
25.11 09:08:16 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
25.11 09:08:16 [Server] WARN at java.lang.Thread.run(Thread.java:748)
25.11 09:08:16 [Server] WARN me.blackvein.quests.exceptions.StageFormatException: mobs-to-kill has invalid mob name Pig Zombie, see quest NetherAdventure stage 1
25.11 09:08:16 [Server] WARN at me.blackvein.quests.Quests.loadQuestStages(Quests.java:2612)
25.11 09:08:16 [Server] WARN at me.blackvein.quests.Quests.loadQuests(Quests.java:1472)
25.11 09:08:16 [Server] WARN at me.blackvein.quests.Quests$3.run(Quests.java:1248)
25.11 09:08:16 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
25.11 09:08:16 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
25.11 09:08:16 [Server] WARN at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
25.11 09:08:16 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
25.11 09:08:16 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
25.11 09:08:16 [Server] WARN at java.lang.Thread.run(Thread.java:748)
25.11 09:08:16 [Server] WARN me.blackvein.quests.exceptions.ConditionFormatException: stay-within-world is not a valid world, see condition of ID conditions.AdvSur.
25.11 09:08:16 [Server] WARN at me.blackvein.quests.Quests.loadCondition(Quests.java:3416)
25.11 09:08:16 [Server] WARN at me.blackvein.quests.Quests.loadQuestStages(Quests.java:2995)
25.11 09:08:16 [Server] WARN at me.blackvein.quests.Quests.loadQuests(Quests.java:1472)
25.11 09:08:16 [Server] WARN at me.blackvein.quests.Quests$3.run(Quests.java:1248)
25.11 09:08:16 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
25.11 09:08:16 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
25.11 09:08:16 [Server] WARN at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
25.11 09:08:16 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
25.11 09:08:16 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
25.11 09:08:16 [Server] WARN at java.lang.Thread.run(Thread.java:748)
25.11 09:08:16 [Server] WARN me.blackvein.quests.exceptions.ConditionFormatException: stay-within-world is not a valid world, see condition of ID conditions.AdvSur.
25.11 09:08:16 [Server] WARN at me.blackvein.quests.Quests.loadCondition(Quests.java:3416)
25.11 09:08:16 [Server] WARN at me.blackvein.quests.Quests.loadQuestStages(Quests.java:2995)
25.11 09:08:16 [Server] WARN at me.blackvein.quests.Quests.loadQuests(Quests.java:1472)
25.11 09:08:16 [Server] WARN at me.blackvein.quests.Quests$3.run(Quests.java:1248)
25.11 09:08:16 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
25.11 09:08:16 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
25.11 09:08:16 [Server] WARN at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
25.11 09:08:16 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
25.11 09:08:16 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
25.11 09:08:16 [Server] WARN at java.lang.Thread.run(Thread.java:748)
25.11 09:08:16 [Server] WARN me.blackvein.quests.exceptions.ConditionFormatException: stay-within-world is not a valid world, see condition of ID conditions.AdvSur.
25.11 09:08:16 [Server] WARN at me.blackvein.quests.Quests.loadCondition(Quests.java:3416)
25.11 09:08:16 [Server] WARN at me.blackvein.quests.Quests.loadQuestStages(Quests.java:2995)
25.11 09:08:16 [Server] WARN at me.blackvein.quests.Quests.loadQuests(Quests.java:1472)
25.11 09:08:16 [Server] WARN at me.blackvein.quests.Quests$3.run(Quests.java:1248)
25.11 09:08:16 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
25.11 09:08:16 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
25.11 09:08:16 [Server] WARN at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
25.11 09:08:16 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
25.11 09:08:16 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
25.11 09:08:16 [Server] WARN at java.lang.Thread.run(Thread.java:748)
25.11 09:08:16 [Server] WARN me.blackvein.quests.exceptions.ConditionFormatException: stay-within-world is not a valid world, see condition of ID conditions.AdvSur.
25.11 09:08:16 [Server] WARN at me.blackvein.quests.Quests.loadCondition(Quests.java:3416)
25.11 09:08:16 [Server] WARN at me.blackvein.quests.Quests.loadQuestStages(Quests.java:2995)
25.11 09:08:16 [Server] WARN at me.blackvein.quests.Quests.loadQuests(Quests.java:1472)
25.11 09:08:16 [Server] WARN at me.blackvein.quests.Quests$3.run(Quests.java:1248)
25.11 09:08:16 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
25.11 09:08:16 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
25.11 09:08:16 [Server] WARN at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
25.11 09:08:16 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
25.11 09:08:16 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
25.11 09:08:16 [Server] WARN at java.lang.Thread.run(Thread.java:748)
25.11 09:08:16 [Server] WARN me.blackvein.quests.exceptions.ConditionFormatException: stay-within-world is not a valid world, see condition of ID conditions.AdvSur.
25.11 09:08:16 [Server] WARN at me.blackvein.quests.Quests.loadCondition(Quests.java:3416)
25.11 09:08:16 [Server] WARN at me.blackvein.quests.Quests.loadQuestStages(Quests.java:2995)
25.11 09:08:16 [Server] WARN at me.blackvein.quests.Quests.loadQuests(Quests.java:1472)
25.11 09:08:16 [Server] WARN at me.blackvein.quests.Quests$3.run(Quests.java:1248)
25.11 09:08:16 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
25.11 09:08:16 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
25.11 09:08:16 [Server] WARN at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
25.11 09:08:16 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
25.11 09:08:16 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
25.11 09:08:16 [Server] WARN at java.lang.Thread.run(Thread.java:748)
25.11 09:08:16 [Server] WARN me.blackvein.quests.exceptions.ConditionFormatException: stay-within-world is not a valid world, see condition of ID conditions.AdvSur.
25.11 09:08:16 [Server] WARN at me.blackvein.quests.Quests.loadCondition(Quests.java:3416)
25.11 09:08:16 [Server] WARN at me.blackvein.quests.Quests.loadQuestStages(Quests.java:2995)
25.11 09:08:16 [Server] WARN at me.blackvein.quests.Quests.loadQuests(Quests.java:1472)
25.11 09:08:16 [Server] WARN at me.blackvein.quests.Quests$3.run(Quests.java:1248)
25.11 09:08:16 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
25.11 09:08:16 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
25.11 09:08:16 [Server] WARN at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
25.11 09:08:16 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
25.11 09:08:16 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
25.11 09:08:16 [Server] WARN at java.lang.Thread.run(Thread.java:748)
25.11 09:08:16 [Server] WARN me.blackvein.quests.exceptions.ConditionFormatException: stay-within-world is not a valid world, see condition of ID conditions.AdvSur.
25.11 09:08:16 [Server] WARN at me.blackvein.quests.Quests.loadCondition(Quests.java:3416)
25.11 09:08:16 [Server] WARN at me.blackvein.quests.Quests.loadConditions(Quests.java:3712)
25.11 09:08:16 [Server] WARN at me.blackvein.quests.Quests$3.run(Quests.java:1250)
25.11 09:08:16 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
25.11 09:08:16 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
25.11 09:08:16 [Server] WARN at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
25.11 09:08:16 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
25.11 09:08:16 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
25.11 09:08:16 [Server] WARN at java.lang.Thread.run(Thread.java:748)
25.11 09:08:16 [Server] ERROR [Quests] Failed to load Condition "AdvSur". Skipping.
25.11 09:08:16 [Server] WARN me.blackvein.quests.exceptions.ConditionFormatException: stay-within-world is not a valid world, see condition of ID conditions.Adv.
25.11 09:08:16 [Server] WARN at me.blackvein.quests.Quests.loadCondition(Quests.java:3416)
25.11 09:08:16 [Server] WARN at me.blackvein.quests.Quests.loadConditions(Quests.java:3712)
25.11 09:08:16 [Server] WARN at me.blackvein.quests.Quests$3.run(Quests.java:1250)
25.11 09:08:16 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
25.11 09:08:16 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
25.11 09:08:16 [Server] WARN at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
25.11 09:08:16 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
25.11 09:08:16 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
25.11 09:08:16 [Server] WARN at java.lang.Thread.run(Thread.java:748)
25.11 09:08:16 [Server] ERROR [Quests] Failed to load Condition "Adv". Skipping.
25.11 09:08:16 [Server] INFO [Quests] Loaded Module: Kill MythicMobs Objective by BerndiVader
25.11 09:08:16 [Server] INFO [Quests] Registered events for custom objective "Kill MythicMobs Objective"
25.11 09:08:16 [Server] INFO [Quests] Loaded Module: MythicMobs Item Require by BerndiVader, idea Wahrheit
25.11 09:08:16 [Server] INFO [Quests] Loaded Module: MythicMobs Item Reward by BerndiVader
25.11 09:08:16 [Server] INFO [Quests] Loaded Module: MythicMobs Conditions Require by BerndiVader, idea Wahrheit
25.11 09:08:16 [Server] INFO [Quests] Loaded Module: MythicItem NPC Deliver Objective by BerndiVader, idea Wahrheit
25.11 09:08:16 [Server] ERROR [Quests] Plugin Quests v4.0.0-rc.2-b157 has failed to register events for class com.gmail.berndivader.mythicmobsquests.MythicItemDeliverObjective because net/citizensnpcs/api/event/NPCRightClickEvent does not exist.
25.11 09:08:16 [Server] INFO [Quests] Registered events for custom objective "MythicItem NPC Deliver Objective"
25.11 09:08:16 [Server] WARN [Quests] Unable to load custom objectives because quest for custom1 was null
25.11 09:08:16 [Server] WARN [Quests] Unable to load custom objectives because quest for custom2 was null
25.11 09:08:16 [Server] WARN [Quests] Unable to load custom objectives because quest for custom3 was null
25.11 09:08:16 [Server] WARN [Quests] Unable to load custom objectives because quest for custom4 was null
25.11 09:08:16 [Server] WARN [Quests] Unable to load custom objectives because quest for custom5 was null
25.11 09:08:16 [Server] WARN [Quests] Unable to load custom objectives because quest for custom6 was null
25.11 09:08:16 [Server] WARN [Quests] Unable to load custom objectives because quest for custom7 was null
25.11 09:08:16 [Server] WARN [Quests] Unable to load custom objectives because quest for custom8 was null
25.11 09:08:16 [Server] WARN [Quests] Unable to load custom objectives because quest for custom9 was null
25.11 09:08:16 [Server] WARN [Quests] Unable to load custom objectives because quest for custom10 was null
25.11 09:08:16 [Server] WARN [Quests] Unable to load custom objectives because quest for custom11 was null
25.11 09:08:16 [Server] INFO Quests reloaded.
25.11 09:08:16 [Server] Startup 0 Quests loaded.
```

**If applicable, which Java class or API method does this reference?**
I run server 1.16.4, and have the absolute latest quests plugin version.

**Comment by PikaMug** [comment]
**Backup your /Quests/data folder** and try using the latest development build:
https://ci.codemc.io/job/PikaMug/job/Quests/166/

Post any resulting errors in a new ticket **using the Report a bug template**.
