### ISSUE TITLE
bug with disconnect

### ISSUE THREAD

**Issue by Lunatik934** [PikaMug/Quests#1499]
**What is your Quests version / build number (do _not_ say "latest")?**
# 176
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
When a player accepts a quest, if he disconnects, he can no longer complete it.

I use mysql storage

**Comment by Lunatik934** [comment]
`[17:16:54] [ForkJoinPool.commonPool-worker-2/WARN]: java.util.ConcurrentModificationException
[17:16:54] [ForkJoinPool.commonPool-worker-2/WARN]: 	at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:966)
[17:16:54] [ForkJoinPool.commonPool-worker-2/WARN]: 	at java.util.LinkedList$ListItr.next(LinkedList.java:888)
[17:16:54] [ForkJoinPool.commonPool-worker-2/WARN]: 	at me.blackvein.quests.storage.implementation.sql.SqlStorage.saveQuesterData(SqlStorage.java:238)
[17:16:54] [ForkJoinPool.commonPool-worker-2/WARN]: 	at me.blackvein.quests.storage.Storage.lambda$saveQuesterData$3(Storage.java:101)
[17:16:54] [ForkJoinPool.commonPool-worker-2/WARN]: 	at me.blackvein.quests.storage.Storage.lambda$makeFuture$1(Storage.java:59)
[17:16:54] [ForkJoinPool.commonPool-worker-2/WARN]: 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
[17:16:54] [ForkJoinPool.commonPool-worker-2/WARN]: 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632)
[17:16:54] [ForkJoinPool.commonPool-worker-2/WARN]: 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[17:16:54] [ForkJoinPool.commonPool-worker-2/WARN]: 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[17:16:54] [Server thread/INFO]: Title command successfully executed
[17:16:54] [ForkJoinPool.commonPool-worker-2/WARN]: 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[17:16:54] [ForkJoinPool.commonPool-worker-2/WARN]: 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)`

**Comment by PikaMug** [comment]
Thanks for the report. Issue should be resolved in https://ci.codemc.io/job/PikaMug/job/Quests/178/
