### ISSUE TITLE
The new version built does not support Papi variables

### ISSUE THREAD

**Issue by 2032704270** [PikaMug/Quests#1522]
Download the latest version of the source code to build plug-ins, but do not support the variables of the placeholder API.

There was an error when using the [trmenu](https://www.spigotmc.org/resources/20-off-trmenu-premium-modern-advanced-menu-plugin-1-8-1-16.83120/) plug-in. After checking the Papi variable, I don't know why?

[22:31:07] [Craft Scheduler Thread - 6/WARN]: [TrMenu] Plugin TrMenu v2.08 generated an exception while executing task 151
java.lang.NoSuchMethodError: me.blackvein.quests.Quester.getCompletedQuests()Ljava/util/LinkedList;
        at me.pikamug.questsexpansion.QuestsExpansion.getPlayerPlaceholder(QuestsExpansion.java:175) ~[?:?]
        at me.pikamug.questsexpansion.QuestsExpansion.onPlaceholderRequest(QuestsExpansion.java:137) ~[?:?]
        at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:38) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:237) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:377) ~[?:?]
        at me.arasple.mc.trmenu.util.Msger.replaceWithPlaceholders(Msger.kt:66) ~[?:?]
        at me.arasple.mc.trmenu.util.Msger.replace(Msger.kt:57) ~[?:?]
        at me.arasple.mc.trmenu.modules.display.item.property.Lore.formatLores(Lore.kt:46) ~[?:?]
        at me.arasple.mc.trmenu.modules.display.item.property.Lore.formatedLore(Lore.kt:41) ~[?:?]
        at me.arasple.mc.trmenu.modules.display.item.DynamicItem.displayLore(DynamicItem.kt:30) ~[?:?]
        at me.arasple.mc.trmenu.modules.display.icon.IconDisplay.refresh(IconDisplay.kt:71) ~[?:?]
        at me.arasple.mc.trmenu.modules.display.Icon.refreshCache(Icon.kt:112) ~[?:?]
        at me.arasple.mc.trmenu.api.action.impl.menu.ActionRefresh.onExecute(ActionRefresh.kt:16) ~[?:?]
        at me.arasple.mc.trmenu.api.action.base.Action$run$1.run(Action.kt:38) ~[?:?]
        at me.arasple.mc.trmenu.modules.service.mirror.MirrorData.eval(MirrorData.kt:37) ~[?:?]
        at me.arasple.mc.trmenu.modules.service.mirror.Mirror.eval(Mirror.kt:16) ~[?:?]
        at me.arasple.mc.trmenu.modules.service.mirror.Mirror.eval$default(Mirror.kt:15) ~[?:?]
        at me.arasple.mc.trmenu.api.action.base.Action.run(Action.kt:24) ~[?:?]
        at me.arasple.mc.trmenu.api.action.Actions$run$1.run(Actions.kt:177) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[CraftTask.class:git-CatServer-1.12.2-5068915]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [CraftAsyncTask.class:git-CatServer-1.12.2-5068915]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_261]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_261]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]

**Comment by DeadlykillOfficial** [comment]
https://github.com/PikaMug/PlaceholderExpansion-Quests - You would need to compile the jar yourself in order to work. 
At least till 4.0.0 is released.
