### ISSUE TITLE
Error with HikariCP while shutting down the server

### ISSUE THREAD

**Issue by kn-km** [PikaMug/Quests#1531]
**What is your Quests version / build number (do _not_ say "latest")?**
187
Quests-4.0.0-rc.3.jar
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
If using MySQL database, we sometimes get there error while shutting down the server.

[17:38:37 INFO]: [Quests] Saving Quester data...
[17:38:37 INFO]: [Quests] Closing storage...
[17:38:37 WARN]: [Server thread] INFO me.blackvein.quests.libs.hikari.HikariDataSource - quests-hikari - Shutdown initiated...
[17:38:37 WARN]: java.sql.SQLException: HikariDataSource HikariDataSource (quests-hikari) has been closed.
[17:38:37 WARN]:        at me.blackvein.quests.libs.hikari.HikariDataSource.getConnection(HikariDataSource.java:96)
[17:38:37 WARN]:        at me.blackvein.quests.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:122)
[17:38:37 WARN]:        at me.blackvein.quests.storage.implementation.sql.SqlStorage.getQuesterLastKnownName(SqlStorage.java:293)
[17:38:37 WARN]:        at me.blackvein.quests.storage.implementation.sql.SqlStorage.saveQuesterData(SqlStorage.java:182)
[17:38:37 WARN]:        at me.blackvein.quests.storage.Storage.lambda$saveQuesterData$3(Storage.java:101)
[17:38:37 WARN]:        at me.blackvein.quests.storage.Storage.lambda$makeFuture$1(Storage.java:59)
[17:38:37 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
[17:38:37 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
[17:38:37 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[17:38:37 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[17:38:37 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[17:38:37 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[17:38:37 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[17:38:37 WARN]: [Server thread] INFO me.blackvein.quests.libs.hikari.HikariDataSource - quests-hikari - Shutdown completed.
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

**Comment by kn-km** [comment]
More error reports.
[19:54:15 INFO]: [Quests] Closing storage...
[19:54:15 WARN]: [Server thread] INFO me.blackvein.quests.libs.hikari.HikariDataSource - quests-hikari - Shutdown initiated...
[19:54:15 WARN]: [Server thread] INFO me.blackvein.quests.libs.hikari.HikariDataSource - quests-hikari - Shutdown completed.
[19:54:15 WARN]: [ForkJoinPool.commonPool-worker-7] WARN me.blackvein.quests.libs.hikari.pool.ProxyConnection - quests-hikari - Connection me.blackvein.quests.libs.mysql.cj.jdbc.ConnectionImpl@6d380e87 marked as broken because of SQLSTATE(08S01), ErrorCode(0)
[19:54:15 WARN]: me.blackvein.quests.libs.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
[19:54:15 WARN]:        at me.blackvein.quests.libs.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
[19:54:15 WARN]:        at me.blackvein.quests.libs.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
[19:54:15 WARN]:        at me.blackvein.quests.libs.mysql.cj.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:637)
[19:54:15 WARN]:        at me.blackvein.quests.libs.mysql.cj.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:418)
[19:54:15 WARN]:        at me.blackvein.quests.libs.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003)
[19:54:15 WARN]:        at me.blackvein.quests.libs.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
[19:54:15 WARN]:        at me.blackvein.quests.libs.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
[19:54:15 WARN]:        at me.blackvein.quests.storage.implementation.sql.SqlStorage.getQuesterLastKnownName(SqlStorage.java:296)
[19:54:15 WARN]:        at me.blackvein.quests.storage.implementation.sql.SqlStorage.saveQuesterData(SqlStorage.java:182)
[19:54:15 WARN]:        at me.blackvein.quests.storage.Storage.lambda$saveQuesterData$3(Storage.java:101)
[19:54:15 WARN]:        at me.blackvein.quests.storage.Storage.lambda$makeFuture$1(Storage.java:59)
[19:54:15 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
[19:54:15 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
[19:54:15 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[19:54:15 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[19:54:15 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[19:54:15 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[19:54:15 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[19:54:15 WARN]: Caused by: me.blackvein.quests.libs.mysql.cj.exceptions.CJCommunicationsException: Communications link failure
[19:54:15 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[19:54:15 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[19:54:15 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[19:54:15 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[19:54:15 WARN]:        at me.blackvein.quests.libs.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
[19:54:15 WARN]:        at me.blackvein.quests.libs.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
[19:54:15 WARN]:        at me.blackvein.quests.libs.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
[19:54:15 WARN]:        at me.blackvein.quests.libs.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
[19:54:15 WARN]:        at me.blackvein.quests.libs.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:544)
[19:54:15 WARN]:        at me.blackvein.quests.libs.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:708)
[19:54:15 WARN]:        at me.blackvein.quests.libs.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:647)
[19:54:15 WARN]:        at me.blackvein.quests.libs.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:134)
[19:54:15 WARN]:        at me.blackvein.quests.libs.mysql.cj.NativeSession.sendCommand(NativeSession.java:311)
[19:54:15 WARN]:        at me.blackvein.quests.libs.mysql.cj.ServerPreparedQuery.sendExecutePacket(ServerPreparedQuery.java:334)
[19:54:15 WARN]:        at me.blackvein.quests.libs.mysql.cj.ServerPreparedQuery.serverExecute(ServerPreparedQuery.java:207)
[19:54:15 WARN]:        at me.blackvein.quests.libs.mysql.cj.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:635)
[19:54:15 WARN]:        ... 15 more
[19:54:15 WARN]: Caused by: javax.net.ssl.SSLException: Socket closed
[19:54:15 WARN]:        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:127)
[19:54:15 WARN]:        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:350)
[19:54:15 WARN]:        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:293)
[19:54:15 WARN]:        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:288)
[19:54:15 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1581)
[19:54:15 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:979)
[19:54:15 WARN]:        at java.base/java.io.FilterInputStream.read(FilterInputStream.java:133)
[19:54:15 WARN]:        at me.blackvein.quests.libs.mysql.cj.protocol.FullReadInputStream.readFully(FullReadInputStream.java:64)
[19:54:15 WARN]:        at me.blackvein.quests.libs.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:63)
[19:54:15 WARN]:        at me.blackvein.quests.libs.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:45)
[19:54:15 WARN]:        at me.blackvein.quests.libs.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:54)
[19:54:15 WARN]:        at me.blackvein.quests.libs.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:44)
[19:54:15 WARN]:        at me.blackvein.quests.libs.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:538)
[19:54:15 WARN]:        ... 22 more
[19:54:15 WARN]: Caused by: java.net.SocketException: Socket closed
[19:54:15 WARN]:        at java.base/java.net.SocketInputStream.socketRead0(Native Method)
[19:54:15 WARN]:        at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
[19:54:15 WARN]:        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
[19:54:15 WARN]:        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
[19:54:15 WARN]:        at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:476)
[19:54:15 WARN]:        at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:470)
[19:54:15 WARN]:        at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70)
[19:54:15 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1354)
[19:54:15 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:963)
[19:54:15 WARN]:        ... 29 more
[19:54:15 WARN]: me.blackvein.quests.libs.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
[19:54:15 WARN]:        at me.blackvein.quests.libs.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
[19:54:15 WARN]:        at me.blackvein.quests.libs.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
[19:54:15 WARN]:        at me.blackvein.quests.libs.mysql.cj.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:637)
[19:54:15 WARN]:        at me.blackvein.quests.libs.mysql.cj.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:418)
[19:54:15 WARN]:        at me.blackvein.quests.libs.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003)
> 2020-12-31 19:54:15,803 Log4j2-TF-1-AsyncLogger[AsyncContext@45ff54e6]-1 ERROR Attempted to append to non-started appender MyPet-Exception-Appender
[19:54:15 WARN]:        at me.blackvein.quests.libs.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
[19:54:15 WARN]:        at me.blackvein.quests.libs.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
[19:54:15 WARN]:        at me.blackvein.quests.storage.implementation.sql.SqlStorage.getQuesterLastKnownName(SqlStorage.java:296)
[19:54:15 WARN]:        at me.blackvein.quests.storage.implementation.sql.SqlStorage.saveQuesterData(SqlStorage.java:182)
[19:54:15 WARN]:        at me.blackvein.quests.storage.Storage.lambda$saveQuesterData$3(Storage.java:101)
[19:54:15 WARN]:        at me.blackvein.quests.storage.Storage.lambda$makeFuture$1(Storage.java:59)
[19:54:15 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
[19:54:15 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
[19:54:15 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[19:54:15 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[19:54:15 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[19:54:15 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[19:54:15 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[19:54:15 WARN]: Caused by: me.blackvein.quests.libs.mysql.cj.exceptions.CJCommunicationsException: Communications link failure
[19:54:15 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[19:54:15 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[19:54:15 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[19:54:15 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[19:54:15 WARN]:        at me.blackvein.quests.libs.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
[19:54:15 WARN]:        at me.blackvein.quests.libs.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
[19:54:15 WARN]:        at me.blackvein.quests.libs.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
[19:54:15 WARN]:        at me.blackvein.quests.libs.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
[19:54:15 WARN]:        at me.blackvein.quests.libs.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:544)
[19:54:15 WARN]:        at me.blackvein.quests.libs.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:708)
[19:54:15 WARN]:        at me.blackvein.quests.libs.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:647)
[19:54:15 WARN]:        at me.blackvein.quests.libs.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:134)
[19:54:15 WARN]:        at me.blackvein.quests.libs.mysql.cj.NativeSession.sendCommand(NativeSession.java:311)
[19:54:15 WARN]:        at me.blackvein.quests.libs.mysql.cj.ServerPreparedQuery.sendExecutePacket(ServerPreparedQuery.java:334)
[19:54:15 WARN]:        at me.blackvein.quests.libs.mysql.cj.ServerPreparedQuery.serverExecute(ServerPreparedQuery.java:207)
[19:54:15 WARN]:        at me.blackvein.quests.libs.mysql.cj.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:635)
[19:54:15 WARN]:        ... 15 more
[19:54:15 INFO]: [MythicMobs] Disabling MythicMobs v4.10.1-3456
[19:54:15 WARN]: Caused by: javax.net.ssl.SSLException: Socket closed
[19:54:15 WARN]:        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:127)
[19:54:15 WARN]:        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:350)
[19:54:15 WARN]:        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:293)
[19:54:15 WARN]:        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:288)
[19:54:15 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1581)
[19:54:15 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:979)
[19:54:15 WARN]:        at java.base/java.io.FilterInputStream.read(FilterInputStream.java:133)
[19:54:15 WARN]:        at me.blackvein.quests.libs.mysql.cj.protocol.FullReadInputStream.readFully(FullReadInputStream.java:64)
[19:54:15 WARN]:        at me.blackvein.quests.libs.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:63)
[19:54:15 WARN]:        at me.blackvein.quests.libs.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:45)
[19:54:15 WARN]:        at me.blackvein.quests.libs.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:54)
[19:54:15 WARN]:        at me.blackvein.quests.libs.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:44)
[19:54:15 WARN]:        at me.blackvein.quests.libs.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:538)
[19:54:15 WARN]:        ... 22 more
[19:54:15 WARN]: Caused by: java.net.SocketException: Socket closed
[19:54:15 WARN]:        at java.base/java.net.SocketInputStream.socketRead0(Native Method)
[19:54:15 WARN]:        at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
[19:54:15 WARN]:        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
[19:54:15 WARN]:        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
[19:54:15 WARN]:        at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:476)
[19:54:15 WARN]:        at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:470)
[19:54:15 WARN]:        at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70)
[19:54:15 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1354)
[19:54:15 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:963)
[19:54:15 WARN]:        ... 29 more

**Comment by PikaMug** [comment]
Thanks for the report. These can be safely ignored. Please use Hastebin or Pastebin when posting console errors in the future.
