### ISSUE TITLE
bug with right-click event

### ISSUE THREAD

**Issue by Arno2596** [PikaMug/Quests#1587]
Hello i found a bug with a quest that need to night click on an npc to complete it.

First i create that quest:

```
  custom15:
    name: '[2] Sterak'
    ask-message: '§6Hello'
    finish-message: thanks
    npc-giver-id: 41
    requirements:
      quests:
      - '[1] The first step'
    stages:
      ordered:
        '1':
          locations-to-reach:
          - RPG 1199.0 122.0 2934.0
          reach-location-radii:
          - 15
          reach-location-names:
          - entry
          start-event: Sterak
          objective-override:
          - Find the entry
        '2':
          locations-to-reach:
          - RPG 1500.0 150.0 2934.0
          reach-location-radii:
          - 1
          reach-location-names:
          - sterak
          objective-override:
          - Enter the tower and collect the treasure
        '3':
          custom-objectives:
            custom1:
              name: MythicItem NPC Deliver Objective
              count: 1
              data:
                Objective Name: 'Deliver'
                NPC IDs: '41'
                Conditions: NONE
                TargetConditions: NONE
                Material: ENDER_PEARL
                MythicItem: NONE
                NameEnds: NONE
                Lore: 'Sterak'
                Amount: '1'
                HoldItem: 'false'
                RemoveItem: 'true'
          objective-override:
          - Deliver the Orb of Sterak
```
But when i right-clicked the npc, the quest doen't end and the item disepeared and from my console i found this:

```
[22:23:36] [Server thread/ERROR]: Could not pass event NPCRightClickEvent to Quests v4.0.0-rc.4-b191
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[craftbukkit-1.15.2-SNAPSHOT.jar:git-Spigot-a99063f-be6aaf0]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[craftbukkit-1.15.2-SNAPSHOT.jar:git-Spigot-a99063f-be6aaf0]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[craftbukkit-1.15.2-SNAPSHOT.jar:git-Spigot-a99063f-be6aaf0]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[craftbukkit-1.15.2-SNAPSHOT.jar:git-Spigot-a99063f-be6aaf0]
        at net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:494) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor433.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[craftbukkit-1.15.2-SNAPSHOT.jar:git-Spigot-a99063f-be6aaf0]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[craftbukkit-1.15.2-SNAPSHOT.jar:git-Spigot-a99063f-be6aaf0]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[craftbukkit-1.15.2-SNAPSHOT.jar:git-Spigot-a99063f-be6aaf0]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[craftbukkit-1.15.2-SNAPSHOT.jar:git-Spigot-a99063f-be6aaf0]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1828) ~[craftbukkit-1.15.2-SNAPSHOT.jar:git-Spigot-a99063f-be6aaf0]
        at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(SourceFile:68) ~[craftbukkit-1.15.2-SNAPSHOT.jar:git-Spigot-a99063f-be6aaf0]
        at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(SourceFile:13) ~[craftbukkit-1.15.2-SNAPSHOT.jar:git-Spigot-a99063f-be6aaf0]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[craftbukkit-1.15.2-SNAPSHOT.jar:git-Spigot-a99063f-be6aaf0]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [craftbukkit-1.15.2-SNAPSHOT.jar:git-Spigot-a99063f-be6aaf0]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [craftbukkit-1.15.2-SNAPSHOT.jar:git-Spigot-a99063f-be6aaf0]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [craftbukkit-1.15.2-SNAPSHOT.jar:git-Spigot-a99063f-be6aaf0]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [craftbukkit-1.15.2-SNAPSHOT.jar:git-Spigot-a99063f-be6aaf0]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [craftbukkit-1.15.2-SNAPSHOT.jar:git-Spigot-a99063f-be6aaf0]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [craftbukkit-1.15.2-SNAPSHOT.jar:git-Spigot-a99063f-be6aaf0]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [craftbukkit-1.15.2-SNAPSHOT.jar:git-Spigot-a99063f-be6aaf0]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895) [craftbukkit-1.15.2-SNAPSHOT.jar:git-Spigot-a99063f-be6aaf0]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [craftbukkit-1.15.2-SNAPSHOT.jar:git-Spigot-a99063f-be6aaf0]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: java.lang.NullPointerException
        at me.blackvein.quests.Objective.<init>(Objective.java:37) ~[?:?]
        at me.blackvein.quests.Quester.finishObjective(Quester.java:3051) ~[?:?]
        at com.gmail.berndivader.mythicmobsquests.MythicItemDeliverObjective.onNPCInteract(MythicItemDeliverObjective.java:93) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[craftbukkit-1.15.2-SNAPSHOT.jar:git-Spigot-a99063f-be6aaf0]
        ... 25 more

```

**Comment by PikaMug** [comment]
Thanks for the report. Please check whether the issue still occurs on the latest development version. If so, report back with the new error (even if it appears similar):
https://ci.codemc.io/job/PikaMug/job/Quests/

**Comment by Arno2596** [comment]
hi, i tried it but it seems to have again an error:

```
[10:30:55] [Server thread/ERROR]: Could not pass event NPCRightClickEvent to Quests v4.0.0-rc.4-b206
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[craftbukkit-1.15.2-SNAPSHOT.jar:git-Spigot-a99063f-be6aaf0]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[craftbukkit-1.15.2-SNAPSHOT.jar:git-Spigot-a99063f-be6aaf0]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[craftbukkit-1.15.2-SNAPSHOT.jar:git-Spigot-a99063f-be6aaf0]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[craftbukkit-1.15.2-SNAPSHOT.jar:git-Spigot-a99063f-be6aaf0]
        at net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:494) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[craftbukkit-1.15.2-SNAPSHOT.jar:git-Spigot-a99063f-be6aaf0]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[craftbukkit-1.15.2-SNAPSHOT.jar:git-Spigot-a99063f-be6aaf0]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[craftbukkit-1.15.2-SNAPSHOT.jar:git-Spigot-a99063f-be6aaf0]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[craftbukkit-1.15.2-SNAPSHOT.jar:git-Spigot-a99063f-be6aaf0]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1828) ~[craftbukkit-1.15.2-SNAPSHOT.jar:git-Spigot-a99063f-be6aaf0]
        at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(SourceFile:68) ~[craftbukkit-1.15.2-SNAPSHOT.jar:git-Spigot-a99063f-be6aaf0]
        at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(SourceFile:13) ~[craftbukkit-1.15.2-SNAPSHOT.jar:git-Spigot-a99063f-be6aaf0]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[craftbukkit-1.15.2-SNAPSHOT.jar:git-Spigot-a99063f-be6aaf0]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [craftbukkit-1.15.2-SNAPSHOT.jar:git-Spigot-a99063f-be6aaf0]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [craftbukkit-1.15.2-SNAPSHOT.jar:git-Spigot-a99063f-be6aaf0]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [craftbukkit-1.15.2-SNAPSHOT.jar:git-Spigot-a99063f-be6aaf0]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [craftbukkit-1.15.2-SNAPSHOT.jar:git-Spigot-a99063f-be6aaf0]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [craftbukkit-1.15.2-SNAPSHOT.jar:git-Spigot-a99063f-be6aaf0]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [craftbukkit-1.15.2-SNAPSHOT.jar:git-Spigot-a99063f-be6aaf0]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [craftbukkit-1.15.2-SNAPSHOT.jar:git-Spigot-a99063f-be6aaf0]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895) [craftbukkit-1.15.2-SNAPSHOT.jar:git-Spigot-a99063f-be6aaf0]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [craftbukkit-1.15.2-SNAPSHOT.jar:git-Spigot-a99063f-be6aaf0]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: java.lang.NullPointerException
        at me.blackvein.quests.Objective.<init>(Objective.java:37) ~[?:?]
        at me.blackvein.quests.Quester.finishObjective(Quester.java:3097) ~[?:?]
        at com.gmail.berndivader.mythicmobsquests.MythicItemDeliverObjective.onNPCInteract(MythicItemDeliverObjective.java:93) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[craftbukkit-1.15.2-SNAPSHOT.jar:git-Spigot-a99063f-be6aaf0]
        ... 26 more
```

**Comment by PikaMug** [comment]
@Arno2596 Thanks for that information. Please try the following build:
https://ci.codemc.io/job/PikaMug/job/Quests/207/

**Comment by Arno2596** [comment]
again an error with this new build :(

```
[23:55:57] [Server thread/ERROR]: Could not pass event NPCRightClickEvent to Quests v4.0.0-rc.4-b207
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[craftbukkit-1.16.4-SNAPSHOT.jar:git-Spigot-a93cbb1-7029c0a]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[craftbukkit-1.16.4-SNAPSHOT.jar:git-Spigot-a93cbb1-7029c0a]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[craftbukkit-1.16.4-SNAPSHOT.jar:git-Spigot-a93cbb1-7029c0a]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[craftbukkit-1.16.4-SNAPSHOT.jar:git-Spigot-a93cbb1-7029c0a]
        at net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:494) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor302.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[craftbukkit-1.16.4-SNAPSHOT.jar:git-Spigot-a93cbb1-7029c0a]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[craftbukkit-1.16.4-SNAPSHOT.jar:git-Spigot-a93cbb1-7029c0a]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[craftbukkit-1.16.4-SNAPSHOT.jar:git-Spigot-a93cbb1-7029c0a]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[craftbukkit-1.16.4-SNAPSHOT.jar:git-Spigot-a93cbb1-7029c0a]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1956) ~[craftbukkit-1.16.4-SNAPSHOT.jar:git-Spigot-a93cbb1-7029c0a]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(SourceFile:74) ~[craftbukkit-1.16.4-SNAPSHOT.jar:git-Spigot-a93cbb1-7029c0a]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(SourceFile:13) ~[craftbukkit-1.16.4-SNAPSHOT.jar:git-Spigot-a93cbb1-7029c0a]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[craftbukkit-1.16.4-SNAPSHOT.jar:git-Spigot-a93cbb1-7029c0a]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[craftbukkit-1.16.4-SNAPSHOT.jar:git-Spigot-a93cbb1-7029c0a]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(SourceFile:144) ~[craftbukkit-1.16.4-SNAPSHOT.jar:git-Spigot-a93cbb1-7029c0a]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[craftbukkit-1.16.4-SNAPSHOT.jar:git-Spigot-a93cbb1-7029c0a]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(SourceFile:118) ~[craftbukkit-1.16.4-SNAPSHOT.jar:git-Spigot-a93cbb1-7029c0a]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:942) ~[craftbukkit-1.16.4-SNAPSHOT.jar:git-Spigot-a93cbb1-7029c0a]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:935) ~[craftbukkit-1.16.4-SNAPSHOT.jar:git-Spigot-a93cbb1-7029c0a]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[craftbukkit-1.16.4-SNAPSHOT.jar:git-Spigot-a93cbb1-7029c0a]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:919) ~[craftbukkit-1.16.4-SNAPSHOT.jar:git-Spigot-a93cbb1-7029c0a]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:851) ~[craftbukkit-1.16.4-SNAPSHOT.jar:git-Spigot-a93cbb1-7029c0a]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[craftbukkit-1.16.4-SNAPSHOT.jar:git-Spigot-a93cbb1-7029c0a]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: java.lang.NullPointerException
        at me.blackvein.quests.Objective.<init>(Objective.java:37) ~[?:?]
        at me.blackvein.quests.Quester.finishObjective(Quester.java:3101) ~[?:?]
        at com.gmail.berndivader.mythicmobsquests.MythicItemDeliverObjective.onNPCInteract(MythicItemDeliverObjective.java:93) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor309.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[craftbukkit-1.16.4-SNAPSHOT.jar:git-Spigot-a93cbb1-7029c0a]
        ... 26 more
```

**Comment by DeadlykillOfficial** [comment]
Is Craftbukkit even supported on 1.16.4?

**Comment by Arno2596** [comment]
sorry it's me ^^' it is just the name i gave him. it's spigot 1.16.4

**Comment by PikaMug** [comment]
@AlessioDP Yes, it's supported.

@Arno2596 Try https://ci.codemc.io/job/PikaMug/job/Quests/208/ once it's ready

**Comment by PikaMug** [comment]
@DeadlykillOfficial Yes, it's supported.

@Arno2596 Try https://ci.codemc.io/job/PikaMug/job/Quests/208/ once it's ready

**Comment by Arno2596** [comment]
```
[00:25:45] [Server thread/ERROR]: Could not pass event NPCRightClickEvent to Quests v4.0.0-rc.4-b208
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.16.4-SNAPSHOT.jar:git-Spigot-a93cbb1-7029c0a]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.4-SNAPSHOT.jar:git-Spigot-a93cbb1-7029c0a]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.4-SNAPSHOT.jar:git-Spigot-a93cbb1-7029c0a]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.4-SNAPSHOT.jar:git-Spigot-a93cbb1-7029c0a]
        at net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:494) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.16.4-SNAPSHOT.jar:git-Spigot-a93cbb1-7029c0a]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.4-SNAPSHOT.jar:git-Spigot-a93cbb1-7029c0a]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.4-SNAPSHOT.jar:git-Spigot-a93cbb1-7029c0a]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.4-SNAPSHOT.jar:git-Spigot-a93cbb1-7029c0a]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1956) ~[spigot-1.16.4-SNAPSHOT.jar:git-Spigot-a93cbb1-7029c0a]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(SourceFile:74) ~[spigot-1.16.4-SNAPSHOT.jar:git-Spigot-a93cbb1-7029c0a]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(SourceFile:13) ~[spigot-1.16.4-SNAPSHOT.jar:git-Spigot-a93cbb1-7029c0a]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.16.4-SNAPSHOT.jar:git-Spigot-a93cbb1-7029c0a]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[spigot-1.16.4-SNAPSHOT.jar:git-Spigot-a93cbb1-7029c0a]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.4-SNAPSHOT.jar:git-Spigot-a93cbb1-7029c0a]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.4-SNAPSHOT.jar:git-Spigot-a93cbb1-7029c0a]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.4-SNAPSHOT.jar:git-Spigot-a93cbb1-7029c0a]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:942) ~[spigot-1.16.4-SNAPSHOT.jar:git-Spigot-a93cbb1-7029c0a]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:935) ~[spigot-1.16.4-SNAPSHOT.jar:git-Spigot-a93cbb1-7029c0a]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot-1.16.4-SNAPSHOT.jar:git-Spigot-a93cbb1-7029c0a]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:919) ~[spigot-1.16.4-SNAPSHOT.jar:git-Spigot-a93cbb1-7029c0a]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:851) ~[spigot-1.16.4-SNAPSHOT.jar:git-Spigot-a93cbb1-7029c0a]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.4-SNAPSHOT.jar:git-Spigot-a93cbb1-7029c0a]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: java.lang.NullPointerException
        at me.blackvein.quests.Objective.<init>(Objective.java:37) ~[?:?]
        at me.blackvein.quests.Quester.finishObjective(Quester.java:3101) ~[?:?]
        at com.gmail.berndivader.mythicmobsquests.MythicItemDeliverObjective.onNPCInteract(MythicItemDeliverObjective.java:93) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.16.4-SNAPSHOT.jar:git-Spigot-a93cbb1-7029c0a]
        ... 27 more
```

**Comment by PikaMug** [comment]
If this doesn't work, I'm unsure what else to try. The developer of the MythicMobs module may simply need to update it.
https://ci.codemc.io/job/PikaMug/job/Quests/209/

**Comment by PikaMug** [comment]
https://ci.codemc.io/job/PikaMug/job/Quests/211/

**Comment by Arno2596** [comment]
the error is gone but i still can't finish my quest anyway. :/

![image](https://user-images.githubusercontent.com/55548766/106113497-d8593380-614e-11eb-87ea-f4796b69f6bc.png)
![image](https://user-images.githubusercontent.com/55548766/106113531-e313c880-614e-11eb-8b22-6434f3a7622e.png)
![image](https://user-images.githubusercontent.com/55548766/106113603-f45cd500-614e-11eb-8570-2f5daf7b2560.png)
![image](https://user-images.githubusercontent.com/55548766/106113656-03438780-614f-11eb-8243-5ded6296ee69.png)
