### ISSUE TITLE
[QuestsConverter] Failed to transfer data of Quester

### ISSUE THREAD

**Issue by hkkongou** [PikaMug/Quests#1704]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests-4.0.3#241

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**

hi, i am currently trying to test the converter function by converting data from yaml to mysql, but during the test, it show error message
``
[13:01:06] [ForkJoinPool.commonPool-worker-19/ERROR]: [QuestsConverter] Failed to transfer data of Quester cae29729-9289-446f-a27a-f023e32f9426
[13:01:06] [ForkJoinPool.commonPool-worker-19/WARN]: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[13:01:06] [ForkJoinPool.commonPool-worker-19/WARN]: 	at java.base/java.util.LinkedList.checkElementIndex(LinkedList.java:559)
[13:01:06] [ForkJoinPool.commonPool-worker-19/WARN]: 	at java.base/java.util.LinkedList.get(LinkedList.java:480)
[13:01:06] [ForkJoinPool.commonPool-worker-19/WARN]: 	at me.blackvein.quests.storage.implementation.file.SeparatedYamlStorage.loadQuesterData(SeparatedYamlStorage.java:338)
[13:01:06] [ForkJoinPool.commonPool-worker-19/WARN]: 	at me.pikamug.questsconverter.conversion.Conversion.convertPlayerData(Conversion.java:55)
[13:01:06] [ForkJoinPool.commonPool-worker-19/WARN]: 	at me.pikamug.questsconverter.conversion.Conversion.lambda$beginConversion$1(Conversion.java:38)
[13:01:06] [ForkJoinPool.commonPool-worker-19/WARN]: 	at me.pikamug.questsconverter.conversion.Conversion.lambda$makeFuture$0(Conversion.java:25)
[13:01:06] [ForkJoinPool.commonPool-worker-19/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
[13:01:06] [ForkJoinPool.commonPool-worker-19/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
[13:01:06] [ForkJoinPool.commonPool-worker-19/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[13:01:06] [ForkJoinPool.commonPool-worker-19/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[13:01:06] [ForkJoinPool.commonPool-worker-19/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[13:01:06] [ForkJoinPool.commonPool-worker-19/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[13:01:06] [ForkJoinPool.commonPool-worker-19/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
``
full log here:
https://paste.gg/p/anonymous/df2a3019a8a448afb667af92361ce25b

not sure is this a big problem. from the log, there are 122 errors, 11167 success.

one of the error player data yaml, listed above is this:
https://paste.gg/p/anonymous/a4662d8f4d4d474c986a6348cf9bdc23

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**
https://paste.gg/p/anonymous/cbefbb0e349f4bf0b78eda01eaf6fda3

**Comment by PikaMug** [comment]
I'll address this here, but in the future please use https://github.com/PikaMug/QuestsConverter/issues

**Comment by PikaMug** [comment]
@hkkongou I'm not entirely certain this will fix it, but please try https://ci.codemc.io/job/PikaMug/job/Quests/242/ and, if the problem still exists, post the new startup log here.

**Comment by hkkongou** [comment]
> @hkkongou I'm not entirely certain this will fix it, but please try https://ci.codemc.io/job/PikaMug/job/Quests/242/ and, if the problem still exists, post the new startup log here.

error down to 6 which is related to 

``java.sql.SQLIntegrityConstraintViolationException: Column 'lastknownname' cannot be null``

![image](https://user-images.githubusercontent.com/61608872/120098865-e3f35000-c16a-11eb-84b6-322d6ddc75ce.png)

full log
https://paste.gg/p/anonymous/f9074b93c35f471cafc4ae0d81ff592d

**Comment by PikaMug** [comment]
Thanks for that. Could I please see the player file from that error? The one starting with 0d0623d5

**Comment by hkkongou** [comment]
> 0d0623d5

```
currentQuests: none
currentStages: none
quest-points: 0
completed-Quests: none

```
thats it

**Comment by PikaMug** [comment]
If that's all, go ahead and delete the file and any others like it.

**Comment by hkkongou** [comment]
> If that's all, go ahead and delete the file and any others like it.

yep, deleted those files then no error.
thanks for the help
