### ISSUE TITLE
player stage progress reset after relogin when using mysql

### ISSUE THREAD

**Issue by hkkongou** [PikaMug/Quests#1707]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests-4.0.3#242

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
when using mysql as storage type, if a player took a quest and submit something without finishing the plugin, then relogin server, his submit progress will change back to 0, got reset.

no error

this does not happen when using yaml storage
**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**
https://paste.gg/p/anonymous/02a27ae5d03e471da2c0d90dc10cf769

**Comment by PikaMug** [comment]
This is a known caveat of the MySQL implementation (mentioned in #1529 and elsewhere). I'll leave this ticket open so you can be notified once an update has been pushed.

**Comment by hkkongou** [comment]
> This is a known caveat of the MySQL implementation (mentioned in #1529 and elsewhere). I'll leave this ticket open so you can be notified once an update has been pushed.

hope this problem can fix soon : (

ci fthis problem will  not be fixed  very fast plz tet me know,. and  will it be possible for quest converter to  back to yaml?

**Comment by hkkongou** [comment]
> This is a known caveat of the MySQL implementation (mentioned in #1529 and elsewhere). I'll leave this ticket open so you can be notified once an update has been pushed.

excuse me, will it be possible for me to find a person pull request for this part of mysql implementation?
i don't want to urge you, you maybe busy, but the issue is almost 1 month already ...
I love quest a lot and I hope it can be one perfect solution for all the scenarios , I hope I can find someone to help, but not sure will you approve : (

**Comment by PikaMug** [comment]
The following build is _EXPERIMENTAL_ regardless of storage type, so _back up your data first_:

https://ci.codemc.io/job/PikaMug/job/Quests/248/

A new `_questdata` table will be created for SQL users. You will not be able to transfer existing YAML data to SQL until [QuestsConverter](https://www.spigotmc.org/resources/questsconverter.86165/) is updated (no ETA). Only use this build if you are OK with players losing their current quest progress.

Password and custom objectives may behave unexpectedly due to changes for both YAML and SQL storage. Players can now trigger Chat and Command Actions multiple times per stage instead of just once. If you are using a Chat Action for a sensitive part of your quest, consider using a password objective instead.

If you have trouble saving quests with this build ("no permission"), please see: https://github.com/PikaMug/Quests/issues/1737#issuecomment-876886006

Bilingual contributors are welcome to lend a hand on Crowdin: https://crowdin.com/project/translate-quests

**Comment by hkkongou** [comment]
``Only use this build if you are OK with players losing their current quest progress.``

i am sorry i am not quick understand this sentence.
as i am currently using mysql for storage and my players have been losing data for more than a month, so after i back up. The only thing i have to do is to switch .jar file?

and then the player progress should be storing if nothing goes wrong?

**Comment by DeadlykillOfficial** [comment]
> `Only use this build if you are OK with players losing their current quest progress.`
> 
> i am sorry i am not quick understand this sentence.
> as i am currently using mysql for storage and my players have been losing data for more than a month, so after i back up. The only thing i have to do is to switch .jar file?
> 
> and then the player progress should be storing if nothing goes wrong?

All of the old data you have will be lost when you switch Jars.
It will reset all players data. 
That's what it means

**Comment by hkkongou** [comment]
just tested #248
the storage is fine, downgrade or upgrade  #248 build does not create any problem

however got an error
```
[09:42:54] [Server thread/ERROR]: Could not pass event NPCRightClickEvent to Quests v4.0.5-b248
java.lang.IndexOutOfBoundsException: Index: 2007, Size: 1
	at java.util.LinkedList.checkElementIndex(LinkedList.java:559) ~[?:?]
	at java.util.LinkedList.get(LinkedList.java:480) ~[?:?]
	at me.blackvein.quests.listeners.NpcListener.onNPCRightClick(NpcListener.java:194) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor889.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:491) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor745.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2442) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:55) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:12) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1325) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1318) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1294) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1138) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by hkkongou** [comment]
A player reported in mysql storage method, one day all of his finished quest progress got loss.

This was believe won't happen under mysql storage method, only in yaml #1589  but.... it still happened 

https://cdn.discordapp.com/attachments/851097423082160138/869512254494765076/2021-07-27_17.30.43.png

**Comment by DeadlykillOfficial** [comment]
Isn't you using modified version of Quests specifically for MySQL progress. I believe i've spoken to your Dev about it?

**Comment by hkkongou** [comment]
> Isn't you using modified version of Quests specifically for MySQL progress. I believe i've spoken to your Dev about it?

no 
i never use any other private version in my live server
the higher version i used for my live server is #247 from jenkins , which is offical and it does not have any progress related functions yet

**Comment by DeadlykillOfficial** [comment]
On 4.0.8?

**Comment by hkkongou** [comment]
> On 4.0.8?

Yes 4.0.8 # 267

**Comment by hkkongou** [comment]
/qa reload after adding new quest also makes some of the player data got reset 
not all of the players tho

**Comment by PikaMug** [comment]
@hkkongou The working theory is that _/qa reload_ was not saving player data fast enough for it to be properly loaded. This build will attempt to resolve this, but must be tested. As always, backup your files before using experimental versions of Quests.
https://ci.codemc.io/job/PikaMug/job/Quests/288/

If this does not resolve the issue, reply below and/or follow the [SpigotMC thread](https://www.spigotmc.org/threads/open-eliminate-a-bug.538251/).
