### ISSUE TITLE
CustomObjective error

### ISSUE THREAD

**Issue by Korvinius** [PikaMug/Quests#1779]
**Version 4.0.6**

**Console error:**
```
[14:06:50] [Thread-12/INFO]: [WebSender] Login is successful.
[14:06:50] [Thread-12/INFO]: WebSender: vote player dinknip                                         //debug message
[14:06:50] [Thread-12/INFO]: WebSender: vote quest , Голосовать за сервер           //debug message
[14:06:50] [Thread-12/ERROR]: Could not pass event BukkitSocketOnMessageEvent to Quests v4.0.6-b254
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[middle171.jar:3219-Spigot-b166a49-8c6d60c]                                                                                                         
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[middle171.jar:3219-Spigot-b166a49-8c6d60c]                                                                                                           
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) [middle171.jar:3219-Spigot-b166a49-8c6d60c]                                                                                                         
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) [middle171.jar:3219-Spigot-b166a49-8c6d60c]                                                                                                         
        at tc.yigit.bukkit.BukkitEvents.callOnMessageEvent(BukkitEvents.java:25) [WebSender.jar:?]
        at tc.yigit.shared.SocketServer.run(SocketServer.java:75) [WebSender.jar:?]
Caused by: java.lang.IllegalStateException: QuesterPreUpdateObjectiveEvent cannot be triggered asynchronously from another thread.                                                                                                           
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:572) ~[middle171.jar:3219-Spigot-b166a49-8c6d60c]                                                                                                        
        at me.blackvein.quests.CustomObjective.incrementObjective(CustomObjective.java:181) ~[?:?]
        at net.wealth_mc.mysteryquest.MysteryQuestMonitoring.onBukkitSocketOnMessageEvent(MysteryQuestMonitoring.java:39) ~[?:?]                                                                                                             
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[middle171.jar:3219-Spigot-b166a49-8c6d60c]                                                                                                         
        ... 5 more

```

**Code CustomObjective:**
```
package net.wealth_mc.mysteryquest;

import org.bukkit.Bukkit;
import org.bukkit.ChatColor;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;

import me.blackvein.quests.CustomObjective;
import me.blackvein.quests.Quest;
import me.blackvein.quests.Quester;
import me.blackvein.quests.Quests;
import tc.yigit.events.BukkitSocketOnMessageEvent;

public class MysteryQuestMonitoring extends CustomObjective implements Listener {
	private static Quests quests = (Quests) Bukkit.getServer().getPluginManager().getPlugin("Quests");
	
	public MysteryQuestMonitoring() {
		setName("Голосовать за сервер");
		setAuthor("Korvinius");
		setShowCount(false);
		setDisplay(ChatColor.GREEN + "Голосовать за сервер");
	}
	
	@EventHandler
    public void onBukkitSocketOnMessageEvent(BukkitSocketOnMessageEvent event) {
		Player player = Bukkit.getPlayer(event.getMessage());
		if (player == null) {
			return;
		}
		Quester quester = quests.getQuester(player.getUniqueId());
		if (quester == null) {
			return;
		}
		for (Quest q : quester.getCurrentQuests().keySet()) {
			Bukkit.getLogger().info("WebSender: " +  "vote player " + player.getName());          //debug message
			Bukkit.getLogger().info("WebSender: " +  "vote quest " + ", " + q.getName());          //debug message
			incrementObjective(player, this, 1, q);
		}
		Bukkit.getLogger().info("WebSender: " + event.getMessage());
	}
}
```

**Comment by DeadlykillOfficial** [comment]
Your Custom plugin it's firing the event in Async mode while it must do it in Sync. 
add Bukkit#Scheduler#runTask and it should work

**Comment by Korvinius** [comment]
Thanks, I'll try

**Comment by DeadlykillOfficial** [comment]
Also such errors caused by your code. It's entirely your responsibility to handle
