### ISSUE TITLE
Build 264 - "Plugin is currently loading"

### ISSUE THREAD

**Issue by Tirco** [PikaMug/Quests#1795]
**What is your Quests version / build number (do _not_ say "latest")?**
Build 264

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
```
[11:37:02 WARN]: [Quests] Task #548 for Quests v4.0.7-b264 generated an exception
java.lang.ClassCastException: class java.util.ArrayList cannot be cast to class java.util.LinkedList (java.util.ArrayList and java.util.LinkedList are in module java.base of loader 'bootstrap')
        at me.blackvein.quests.Quests.loadCondition(Quests.java:3845) ~[Quests-4.0.7b264.jar:?]
        at me.blackvein.quests.Quests.loadConditions(Quests.java:4088) ~[Quests-4.0.7b264.jar:?]
        at me.blackvein.quests.Quests.lambda$delayLoadQuestInfo$1(Quests.java:773) ~[Quests-4.0.7b264.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-257]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-257]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1559) ~[patched_1.17.1.jar:git-Paper-257]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-257]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1475) ~[patched_1.17.1.jar:git-Paper-257]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1274) ~[patched_1.17.1.jar:git-Paper-257]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-257]
        at java.lang.Thread.run(Thread.java:831) [?:?]
   
```
This happens on load, and then you can't use any of the commands. For some reason I could accept a quest from an npc tho.
   

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**
- Not applicable.

**Comment by Tirco** [comment]
Noticed that it was an issue with my conditions, that I didn't use anyways... Deleted the file and let quests generate a new one.
Here was the contents that caused the issue:
```YAML
conditions:
  '7':
    check-placeholder-id:
    - '%mmocore_level%'
    check-placeholder-value:
    - '>9'
```
