### ISSUE TITLE
NullPointerException in editor with invalid enchantement name

### ISSUE THREAD

**Issue by marcelschoen** [PikaMug/Quests#1827]
- Quests 4.1.1

I accidentally entered an invalid (non-existent) enchantment name in the in-game editor for a reward item, and now I can't quit the editor anymore. When I try to "Exit" it, nothing happens, but I see this exception in the server log (caused, I assume, by the invalid enchantment name):

```
03.11 00:53:49 [Server] WARN Plugin Quests v4.1.1-b275 generated an exception whilst handling conversation input
03.11 00:53:49 [Server] INFO java.lang.NullPointerException: Cannot invoke "String.replace(java.lang.CharSequence, java.lang.CharSequence)" because the return value of "org.bukkit.enchantments.Enchantment.getName()" is null
03.11 00:53:49 [Server] INFO at me.blackvein.quests.util.ItemUtil.getEnchantmentFromProperName(ItemUtil.java:676) ~[Quests-4.1.1.jar:?]
03.11 00:53:49 [Server] INFO at me.blackvein.quests.util.ItemUtil.getEnchantmentFromPrettyName(ItemUtil.java:754) ~[Quests-4.1.1.jar:?]
03.11 00:53:49 [Server] INFO at me.blackvein.quests.convo.generic.ItemStackPrompt$ItemEnchantmentPrompt.acceptInput(ItemStackPrompt.java:616) ~[Quests-4.1.1.jar:?]
03.11 00:53:49 [Server] INFO at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:234) ~[patched_1.17.1.jar:git-Paper-279]
03.11 00:53:49 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:59) ~[patched_1.17.1.jar:git-Paper-279]
03.11 00:53:49 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1705) ~[patched_1.17.1.jar:git-Paper-279]
03.11 00:53:49 [Server] INFO at net.minecraft.server.network.PlayerConnection$1.run(PlayerConnection.java:2079) ~[patched_1.17.1.jar:git-Paper-279]
03.11 00:53:49 [Server] INFO at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1572) ~[patched_1.17.1.jar:git-Paper-279]
03.11 00:53:49 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-279]
03.11 00:53:49 [Server] INFO at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1475) ~[patched_1.17.1.jar:git-Paper-279]
03.11 00:53:49 [Server] INFO at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1274) ~[patched_1.17.1.jar:git-Paper-279]
03.11 00:53:49 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-279]
03.11 00:53:49 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]

```

**Comment by PikaMug** [comment]
Thanks for the report. What is the exact word or phrase that you entered into the editor?

**Comment by marcelschoen** [comment]
I think I entered "UNBREAKING" as the name for the enchantment. Without any numbers.

**Comment by marcelschoen** [comment]
I strongly suspect you can easily reproduce this by entering just an arbitrary value, like "DOODELDOO"... but I can't test it right now as I am working at the office. Will be able to retry in about 10 hours.

**Comment by PikaMug** [comment]
Thanks for the reply. Both entries return the message "Invalid enchantment name!" for me, but please try the latest development build at https://ci.codemc.io/job/PikaMug/job/Quests/278/

If the problem still occurs, share the quest from your _quests.yml_ file using a pastebin service.
