### ISSUE TITLE
Actions not recognizing Denizen Scripts

### ISSUE THREAD

**Issue by Curtis73** [PikaMug/Quests#1877]
### What is your Quests version / build number (do _not_ say "latest")?

 4.2.0-b296

### Describe the problem and how to replicate it.

Since updating to the most recent release of Denizen, Quests seems unable to identify or run Denizen Scripts via actions.

If I run /questadmin give (player) (quest), I get a console error (below), but if I accept the quest as normal via an NPC then the script still doesn't run, a blank line is printed in chat, but no errors go to console.

If I go into the actions editor and edit an action with a `denizen-script` value set in config, the "Denizen Script" output specifies "None Set"
Similarly, if I try to set a new Denizen Script, the list of available scripts is shown, but typing the full name of the script doesn't do anything.

### Any console errors to share?

```shell
[14:24:30] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'questadmin' in plugin Quests v4.2.0-b296
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:897) ~[paper-1.18.1.jar:git-Paper-177]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2287) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2098) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2079) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.1.jar:git-Paper-177]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.1.jar:git-Paper-177]
at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.1.jar:git-Paper-177]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.1.jar:git-Paper-177]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.1.jar:git-Paper-177]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1362) ~[paper-1.18.1.jar:git-Paper-177]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1268) ~[paper-1.18.1.jar:git-Paper-177]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-177]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'boolean com.denizenscript.denizencore.scripts.ScriptRegistry.containsScript(java.lang.String)'
at me.blackvein.quests.reflect.denizen.DenizenAPI_1_1_1.containsScript(DenizenAPI_1_1_1.java:32) ~[Quests-4.2.0.jar:?]
at me.blackvein.quests.reflect.denizen.DenizenAPI.containsScript(DenizenAPI.java:106) ~[Quests-4.2.0.jar:?]
at me.blackvein.quests.dependencies.DenizenTrigger.runDenizenScript(DenizenTrigger.java:28) ~[Quests-4.2.0.jar:?]
at me.blackvein.quests.actions.Action.fire(Action.java:463) ~[Quests-4.2.0.jar:?]
at me.blackvein.quests.Quester.takeQuest(Quester.java:855) ~[Quests-4.2.0.jar:?]
at me.blackvein.quests.listeners.CmdExecutor.adminGive(CmdExecutor.java:1080) ~[Quests-4.2.0.jar:?]
at me.blackvein.quests.listeners.CmdExecutor.questAdminCommandHandler(CmdExecutor.java:292) ~[Quests-4.2.0.jar:?]
at me.blackvein.quests.listeners.CmdExecutor.onCommand(CmdExecutor.java:91) ~[Quests-4.2.0.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
... 21 more
```

**Comment by PikaMug** [comment]
Thanks for the report. What is the Denizen version/build number?

**Comment by Curtis73** [comment]
I'm running Denizen 1.2.3, build #1760

**Comment by PikaMug** [comment]
@Curtis73 Try https://ci.codemc.io/job/PikaMug/job/Quests/297/
