### ISSUE TITLE
HOw can I solve this

### ISSUE THREAD

**Issue by albos7** [PikaMug/Quests#1878]
### What is your Quests version / build number (do _not_ say "latest")?

1.17

### Describe the problem and how to replicate it.

Something gives error when I try to do a gui with this quests

### Any console errors to share?

```shell
[00:16:05 WARN]: [DeluxeMenus] Plugin DeluxeMenus v1.13.4-Release generated an exception while executing task 1211
java.lang.NullPointerException: null
        at java.util.concurrent.ConcurrentSkipListMap.doGet(ConcurrentSkipListMap.java:541) ~[?:?]
        at java.util.concurrent.ConcurrentSkipListMap.containsKey(ConcurrentSkipListMap.java:1294) ~[?:?]
        at java.util.concurrent.ConcurrentSkipListSet.contains(ConcurrentSkipListSet.java:225) ~[?:?]
        at me.pikamug.questsexpansion.QuestsExpansion.getPlayerPlaceholder(QuestsExpansion.java:244) ~[?:?]
        at me.pikamug.questsexpansion.QuestsExpansion.onPlaceholderRequest(QuestsExpansion.java:137) ~[?:?]
        at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:32) ~[PlaceholderAPI-2.11.1 (1).jar:?]
        at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:161) ~[PlaceholderAPI-2.11.1 (1).jar:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:70) ~[PlaceholderAPI-2.11.1 (1).jar:?]
        at com.extendedclip.deluxemenus.menu.MenuHolder.setPlaceholders(MenuHolder.java:95) ~[DeluxeMenus-1.13.4-Release.jar:?]
        at com.extendedclip.deluxemenus.requirement.InputResultRequirement.evaluate(InputResultRequirement.java:21) ~[DeluxeMenus-1.13.4-Release.jar:?]
        at com.extendedclip.deluxemenus.requirement.RequirementList.evaluate(RequirementList.java:21) ~[DeluxeMenus-1.13.4-Release.jar:?]
        at com.extendedclip.deluxemenus.menu.Menu.lambda$openMenu$5(Menu.java:348) ~[DeluxeMenus-1.13.4-Release.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-408]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Paper-408]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-408]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### If applicable, can you provide an example quest from quests.yml?

```shell
Oak1:
    name: §6§lOak Lumberjack &e#1
    ask-message: §eChop §d1000§e logs of §dOak Wood§e.
    
    finish-message: §eWell done. Here is your reward. ########
    stages:
      ordered:
        '1':
          break-block-names:
          - OAK_LOG
          break-block-amounts:
          - 1000
          break-block-durability: #
          - 0
    rewards:
      quest-points: 1
      commands:
      - tokens give <player> 2
    planner:
      cooldown: -1
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
  Oak2:
    name: §6§lOak Lumberjack &e#2
    ask-message: §eChop §d5000§e logs of §dOak Wood§e.
    
    finish-message: §eWell done. Here is your reward. ########
    requirements:
      quests:
      - Oak1
    stages:
      ordered:
        '1':
          break-block-names:
          - OAK_LOG
          break-block-amounts:
          - 5000
          break-block-durability: #
          - 0
    rewards:
      quest-points: 1
      commands:
      - tokens give <player> 3
    planner:
      cooldown: -1
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
  Oak3:
    name: §6§lOak Lumberjack &e#3
    ask-message: §eChop §d10000§e logs of §dOak Wood§e.
    
    finish-message: §eWell done. Here is your reward. ########
    requirements:
      quests:
      - Oak2
    stages:
      ordered:
        '1':
          break-block-names:
          - OAK_LOG
          break-block-amounts:
          - 10000
          break-block-durability: #
          - 0
    rewards:
      quest-points: 1
      commands:
      - crazycrates give <player> common 1
    planner:
      cooldown: -1
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
  Spruce1:
    name: §6§lSpruce Lumberjack &e#1
    ask-message: §eChop §d1000§e logs of §dSpruce Wood§e.
    
    finish-message: §eWell done. Here is your reward. ########
    stages:
      ordered:
        '1':
          break-block-names:
          - SPRUCE_LOG
          break-block-amounts:
          - 1000
          break-block-durability: #
          - 0
    rewards:
      quest-points: 1
      commands:
      - tokens give <player> 2
    planner:
      cooldown: -1
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
  Spruce2:
    name: §6§lSpruce Lumberjack &e#2
    ask-message: §eChop §d5000§e logs of §dSpruce Wood§e.
    
    finish-message: §eWell done. Here is your reward. ########
    requirements:
      quests:
      - Spruce1
    stages:
      ordered:
        '1':
          break-block-names:
          - SPRUCE_LOG
          break-block-amounts:
          - 5000
          break-block-durability: #
          - 0
    rewards:
      quest-points: 1
      commands:
      - tokens give <player> 3
    planner:
      cooldown: -1
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
  Spruce3:
    name: §6§lSpruce Lumberjack &e#3
    ask-message: §eChop §d10000§e logs of §dSpruce Wood§e.
    
    finish-message: §eWell done. Here is your reward. ########
    requirements:
      quests:
      - Spruce2
    stages:
      ordered:
        '1':
          break-block-names:
          - SPRUCE_LOG
          break-block-amounts:
          - 10000
          break-block-durability: #
          - 0
    rewards:
      quest-points: 1
      commands:
      - crazycrates give <player> common 1
    planner:
      cooldown: -1
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
```

**Comment by DeadlykillOfficial** [comment]
This error it's related to DeluxeMenus and not Quests in general.
You can updated the plugin but didn't updated the Quests Placeholder Expansion therefore you are experiencing this problem.

**Comment by PikaMug** [comment]
Thanks for the report. As Deadlykill said, it looks like you ought to update the placeholder expansion for Quests. You can download it through the _/papi_ command or at https://www.spigotmc.org/resources/placeholderexpansion-quests.69357/

Let us know if you have any trouble after updating by replying below.
