### ISSUE TITLE
I need Help

### ISSUE THREAD

**Issue by MuniGHG** [PikaMug/Quests#1886]
### What is your Quests version / build number (do _not_ say "latest")?

4.2.1

### Describe the problem and how to replicate it.

My console is flooding with warnings and I don't know what the problem is, it's flooding 24/7 and they need to disable the plugin for this.

### Any console errors to share?

```shell
[19:05:11 WARN]: Exception in thread "Craft Scheduler Thread - 122698" 
[19:05:11 WARN]: org.apache.commons.lang.UnhandledException: Plugin Quests v4.2.1-b300 generated an exception while executing task 5836990
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
```

### If applicable, can you provide an example quest from quests.yml?

```shell
custom1:
    name: 「Mata 10 Skeletons | Ordeña 5 Vacas」
    ask-message: Mision Diaria
    finish-message: Bien Hecho!
    npc-giver-id: 34
    stages:
      ordered:
        '1':
          cows-to-milk: 5
          mobs-to-kill:
          - Skeleton
          mob-amounts:
          - 10
    planner:
      cooldown: 172800
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
  custom2:
    name: 「Domestica 2 Lobos | Pezca 3 peces」
    ask-message: Segunda Mision
    finish-message: Bien Hecho!
    npc-giver-id: 34
    stages:
      ordered:
        '1':
          fish-to-catch: 5
          mobs-to-tame:
          - Wolf
          mob-tame-amounts:
          - 2
    planner:
      cooldown: 172800
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
  custom3:
    name: 「Mata 3 Endermans」
    ask-message: Tercera Mision
    finish-message: Bien Hecho!
    npc-giver-id: 34
    stages:
      ordered:
        '1':
          mobs-to-kill:
          - Enderman
          mob-amounts:
          - 3
    planner:
      cooldown: 172800
  custom4:
    name: 「Mata 5 Jugadores」
    ask-message: Mision Kills
    finish-message: Sigue asi! no tengas piedad con nadie
    npc-giver-id: 36
    stages:
      ordered:
        '1':
          players-to-kill: 5
          start-message: Matalos a todos
    planner:
      cooldown: 3600
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
  custom5:
    name: 「Mata 10 Jugadores」
    ask-message: Misione Diaria
    finish-message: Bien Hecho!
    npc-giver-id: 36
    stages:
      ordered:
        '1':
          players-to-kill: 10
    planner:
      cooldown: 3600
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
```

**Comment by PikaMug** [comment]
Thanks for the report. The portion of that exception you shared is not useful in diagnosing the issue. Please look earlier in your server log file for a more descriptive exception, or upload the file itself for review.
