### ISSUE TITLE
Editor. Stages

### ISSUE THREAD

**Issue by ZelefRU** [PikaMug/Quests#1890]
### What is your Quests version / build number (do _not_ say "latest")?

4.2.1-b300

### Describe the problem and how to replicate it.

In Russian, the word "Clear" is used not as a list cleanup, but as a replacement word
![unknown](https://user-images.githubusercontent.com/95104322/156752799-bf653599-5291-4568-91ea-cfdc9b2f8060.png)

### Any console errors to share?

```shell
[14:06:53] [Server thread/INFO]: Zelef issued server command: /quests info
[14:09:50] [Server thread/INFO]: [Quests] Player 6f04dd27-5570-3a67-8e62-d459fd8f51b6 saved quest rus
[14:09:53] [Server thread/INFO]: Zelef issued server command: /qa reload
[14:09:53] [Craft Scheduler Thread - 25 - Quests/INFO]: [Quests] Loaded language ru-RU. Translations via Crowdin
[14:09:53] [Thread-74/WARN]: java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[14:09:53] [Thread-74/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
[14:09:53] [Thread-74/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[14:09:53] [Thread-74/WARN]: 	at Quests-4.2.1.jar//me.blackvein.quests.Quests.lambda$null$3(Quests.java:1691)
[14:09:53] [Thread-74/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787)
[14:09:53] [Thread-74/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[14:09:53] [Thread-74/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[14:09:53] [Thread-74/WARN]: Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[14:09:53] [Thread-74/WARN]: 	at java.base/java.util.LinkedList.checkElementIndex(LinkedList.java:559)
[14:09:53] [Thread-74/WARN]: 	at java.base/java.util.LinkedList.get(LinkedList.java:480)
[14:09:53] [Thread-74/WARN]: 	at Quests-4.2.1.jar//me.blackvein.quests.storage.implementation.file.SeparatedYamlStorage.loadQuester(SeparatedYamlStorage.java:203)
[14:09:53] [Thread-74/WARN]: 	at Quests-4.2.1.jar//me.blackvein.quests.storage.Storage.lambda$loadQuester$2(Storage.java:89)
[14:09:53] [Thread-74/WARN]: 	at Quests-4.2.1.jar//me.blackvein.quests.storage.Storage.lambda$makeFuture$0(Storage.java:46)
[14:09:53] [Thread-74/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[14:09:53] [Thread-74/WARN]: 	... 1 more
```

**Comment by PikaMug** [comment]
Try https://ci.codemc.io/job/PikaMug/job/Quests/301/

**Comment by ZelefRU** [comment]
@PikaMug Same problem. Word "Очищено" doesn't work
![Screenshot_1](https://user-images.githubusercontent.com/95104322/156874535-3e7681a8-8894-49ea-8c2a-847c18f5e016.png)

**Comment by ZelefRU** [comment]
The same problem with the word "Выйти(Cancel)"

**Comment by PikaMug** [comment]
Try https://ci.codemc.io/job/PikaMug/job/Quests/302/

**Comment by ZelefRU** [comment]
> Try https://ci.codemc.io/job/PikaMug/job/Quests/302/

Yes, it worked, but other problems appeared and the old ones did not go away.
