### ISSUE TITLE
Error message/Send Title

### ISSUE THREAD

**Issue by Zebi231** [PikaMug/Quests#1903]
### What is your Quests version / build number (do _not_ say "latest")?

Quests 4.2.2-b303

### Describe the problem and how to replicate it.

When a quest ends the Send Title is not displayed and it shows me a big error message in the console, I don't know if it's a bad version.

### Any console errors to share?

```shell
[07:49:29] [Server thread/ERROR]: Could not pass event BlockBreakEvent to Quests v4.2.2-b303

org.bukkit.event.EventException

	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]

	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]

	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]

	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]

	at net.minecraft.server.v1_8_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:286) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]

	at net.minecraft.server.v1_8_R3.PlayerInteractManager.a(PlayerInteractManager.java:121) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]

	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:600) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]

	at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:40) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]

	at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:10) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]

	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]

	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_202]

	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_202]

	at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]

	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]

	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]

	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]

	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]

	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]

Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Player.sendTitle(Ljava/lang/String;Ljava/lang/String;)V

	at me.blackvein.quests.Quest.completeQuest(Quest.java:901) ~[?:?]

	at me.blackvein.quests.Quest.completeQuest(Quest.java:665) ~[?:?]

	at me.blackvein.quests.Quest.nextStage(Quest.java:274) ~[?:?]

	at me.blackvein.quests.Quester.finishObjective(Quester.java:3424) ~[?:?]

	at me.blackvein.quests.Quester.breakBlock(Quester.java:1701) ~[?:?]

	at me.blackvein.quests.listeners.BlockListener.onBlockBreak(BlockListener.java:84) ~[?:?]

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202]

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]

	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]

	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.7.jar:git-Spigot-f928e7a-994b2aa]

	... 17 more
```

### If applicable, can you provide an example quest from quests.yml?

```shell
name: TestQuests
    ask-message: Go
    finish-message: thanks
    npc-giver-id: 12
    internships:
      ordered:
        '1':
          break-block-names:
          - 'GRASS'
          break-block-amounts:
          - 10
          break-block-durability:
          - 0
          start-message: 10 blocks grass
          complete-message: thx
    rewards:
      money: 2000
```

**Comment by PikaMug** [comment]
What is your server version?

**Comment by Zebi231** [comment]
Do you know where the problem comes from ?

**Comment by PikaMug** [comment]
For now, set `show-titles: false` in your _config.yml_ file.

**Comment by Zebi231** [comment]
Well I would like the title to appear haha

**Comment by PikaMug** [comment]
@Zebi231 Try https://ci.codemc.io/job/PikaMug/job/Quests/306/

**Comment by Zebi231** [comment]
@PikaMug Ok it works, thank you very much :)
