### ISSUE TITLE
Cannot start/edit quests!

### ISSUE THREAD

**Issue by MaxDaFoxHybridz** [PikaMug/Quests#1922]
### What is your Quests version / build number (do *not* say "latest")?

4.3.1-b321

### Describe the problem and how to replicate it.

Description of the problem : 

The problem/error occurs when you try to edit a quest using the Quest editor. Instead of going into the quests' properties it just gives 0 responses while still staying in the editor.

The problem also occurs when attempting to start a quest, doing the command /quests take [quest name] usually would start the quest as normal after accepting it. This time it just shows a gray-colored "Yes" after clicking the yes button and does nothing and gives 0 responses. This also occurs when trying to accept a quest via an NPC

How to replicate it :

I haven't found a direct way on replicating it, the problem first started on version 4.2.3. Tried updating to the latest version (4.3.1-b321) and it still is bugged. The server version is 1.18.2 and software is Purpur

### Any console errors to share?

```shell
Error that happens when attempting to edit/start a quest:
[14:41:10 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.getType()" because "toBreak" is null
[14:41:10 WARN]:        at Quests-4.3.1.jar//me.blackvein.quests.Quester.addEmptiesFor(Quester.java:4090)
[14:41:10 WARN]:        at Quests-4.3.1.jar//me.blackvein.quests.Quester.takeQuest(Quester.java:735)
[14:41:10 WARN]:        at Quests-4.3.1.jar//me.blackvein.quests.Quests$QuestAcceptPrompt.acceptInput(Quests.java:723)
[14:41:10 WARN]:        at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:234)
[14:41:10 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:59)
[14:41:10 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1804)
[14:41:10 WARN]:        at net.minecraft.server.network.PlayerConnection$2.run(PlayerConnection.java:2202)
[14:41:10 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1575)
[14:41:10 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:522)
[14:41:10 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1485)
[14:41:10 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1248)
[14:41:10 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322)
[14:41:10 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

Warning/Error message that happens upon server startup:

[14:17:26 ERROR]: [Quests] Module error! Seek help from developer of module:
[14:17:26 WARN]: java.lang.NoClassDefFoundError: net/livecar/nuttyworks/npc_destinations/api/Navigation_NewDestination
[14:17:26 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[14:17:26 WARN]:        at java.base/java.lang.Class.forName(Class.java:467)
[14:17:26 WARN]:        at Quests-4.3.1.jar//me.blackvein.quests.Quests.loadModule(Quests.java:994)
[14:17:26 WARN]:        at Quests-4.3.1.jar//me.blackvein.quests.Quests.loadModules(Quests.java:935)
[14:17:26 WARN]:        at Quests-4.3.1.jar//me.blackvein.quests.Quests.lambda$delayLoadQuestInfo$2(Quests.java:850)
[14:17:26 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[14:17:26 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[14:17:26 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1562)
[14:17:26 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:522)
[14:17:26 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1485)
[14:17:26 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1248)
[14:17:26 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322)
[14:17:26 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[14:17:26 WARN]: Caused by: java.lang.ClassNotFoundException: net.livecar.nuttyworks.npc_destinations.api.Navigation_NewDestination
[14:17:26 WARN]:        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
[14:17:26 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
[14:17:26 WARN]:        at java.base/java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:872)
[14:17:26 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[14:17:26 WARN]:        ... 13 more
```

### If applicable, can you provide an example quest from quests.yml?

```shell
custom1:
    name: Beta Tester Quest
    ask-message: '&dCustomCraft&f is currently in its &eBETA&f phase! Participate
      in this &cquest&f to obtain the limited time "Beta" rank. Reminder to do it
      before this quest expires'
    finish-message: Congratulations on becoming a Beta Tester! We hope you enjoy your
      time in CustomCraft
    npc-giver-id: 2
    stages:
      ordered:
        '1':
          break-block-names:
          - Stone,
          - Oak_log
          break-block-amounts:
          - 20
          - 10
          break-block-durability:
          - 0
          - 0
          items-to-smelt:
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: IRON_INGOT
            amount: 5
          mobs-to-kill:
          - pig
          - cow
          - zombie
          mob-amounts:
          - 5
          - 5
          - 5
    rewards:
      commands:
      - lp user <player> parent set beta-tester



The above might be of use, keep in mind I'm a beginner to the Quests plugin!
```

**Comment by 91leMAC** [comment]
I have the same error !

**Comment by PikaMug** [comment]
Being unable to edit quests is a duplicate of #1818

The first error, I'll look into.

The second error is an issue with the NPCDestinations plugin. Reach out to its developer; nothing I can do about that.

**Comment by MaxDaFoxHybridz** [comment]
I see, thank you for responding, and sorry for the trouble of making an accidental duplicate of this issue.

Weird that NPCDestinations was involved didn't expect that. I thought I removed the plugin a few days ago

Again apologies for the duplicate issues and have a good day/night
