### ISSUE TITLE
1.editing quests doesn't work for me 2.Giving money for a quest doesn't work

### ISSUE THREAD

**Issue by redpid42** [PikaMug/Quests#1932]
### Where else have you looked for answers to this question?

discord

### Share your question with as much detail as possible.

1.when i do /quests editor and select edit quest and enter the name of the quest it doesn't work. I can change it in the files but not in game
This is the console:	
[20:36:21 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'quest' in plugin Quests v4.3.1-b321
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:897) ~[paper-1.18.1.jar:git-Paper-101]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2268) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2079) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2060) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.1.jar:git-Paper-101]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.1.jar:git-Paper-101]
	at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.1.jar:git-Paper-101]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.1.jar:git-Paper-101]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.1.jar:git-Paper-101]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1462) ~[paper-1.18.1.jar:git-Paper-101]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-101]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-101]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: net/citizensnpcs/api/CitizensAPI
	at me.blackvein.quests.Quest.getNpcStart(Quest.java:193) ~[Quests-4.3.1.jar:?]
	at me.blackvein.quests.commands.quest.QuestCommandHandler.showQuestDetails(QuestCommandHandler.java:117) ~[Quests-4.3.1.jar:?]
	at me.blackvein.quests.commands.quest.QuestCommandHandler.check(QuestCommandHandler.java:69) ~[Quests-4.3.1.jar:?]
	at me.blackvein.quests.listeners.CommandManager.onCommand(CommandManager.java:51) ~[Quests-4.3.1.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	... 21 more
Caused by: java.lang.ClassNotFoundException: net.citizensnpcs.api.CitizensAPI
	at me.blackvein.quests.Quest.getNpcStart(Quest.java:193) ~[Quests-4.3.1.jar:?]
	at me.blackvein.quests.commands.quest.QuestCommandHandler.showQuestDetails(QuestCommandHandler.java:117) ~[Quests-4.3.1.jar:?]
	at me.blackvein.quests.commands.quest.QuestCommandHandler.check(QuestCommandHandler.java:69) ~[Quests-4.3.1.jar:?]
	at me.blackvein.quests.listeners.CommandManager.onCommand(CommandManager.java:51) ~[Quests-4.3.1.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	... 21 more

	
2.When setting a quest to give a money reward it doesn't give it to me (any other rewards don't work too)

**Comment by PikaMug** [comment]
It seems you are a reporting a bug, not asking a question. Please select the correct option when opening an issue. If you have more than one problem, open a separate issue for each.

It seems you have a Start NPC defined for one of your quests but the Citizens plugin did not load correctly. Resolve the issue with Citizens or remove any `npc-giver-id` lines from your _quests.yml_ file. Money rewards operate through Vault; make sure that Vault loaded correctly.
