### ISSUE TITLE
Carrots and Cocoa beans does not register when i break it

### ISSUE THREAD

**Issue by sebberj** [PikaMug/Quests#1965]
### What is your Quests version / build number (do *not* say "latest")?

4.4.1

### Describe the problem and how to replicate it.

Hi, I have been trying to make a "Farmer" Quest. but I can't make it work..? I want the quest to break Carrots, but the plugin does not register when I break it? - I tried the same thing with Cocoa beans, and that works almost perfectly, except that I get an error in the console and it does not say that I have to break 5 Cocoa beans, but when I break 5 cocoa beans the quest i completed and i get the rewards.

### Any console errors to share?

```shell
This is the error for Carrots: - Its the same error for cocoa beans, just different material name:


[13:17:13 WARN]: java.lang.IllegalArgumentException: CARROTS material could not be queried!
[13:17:13 WARN]:        at Quests-4.4.1.jar//me.blackvein.quests.libs.localelib.LocaleManager.queryMaterial(LocaleManager.java:384)
[13:17:13 WARN]:        at Quests-4.4.1.jar//me.blackvein.quests.libs.localelib.LocaleManager.sendMessage(LocaleManager.java:125)
[13:17:13 WARN]:        at Quests-4.4.1.jar//me.blackvein.quests.libs.localelib.LocaleManager.sendMessage(LocaleManager.java:164)
[13:17:13 WARN]:        at Quests-4.4.1.jar//me.blackvein.quests.Quester.finishObjective(Quester.java:3662)
[13:17:13 WARN]:        at Quests-4.4.1.jar//me.blackvein.quests.Quester.breakBlock(Quester.java:2232)
[13:17:13 WARN]:        at Quests-4.4.1.jar//me.blackvein.quests.listeners.BlockListener.onBlockBreak(BlockListener.java:85)
[13:17:13 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor557.execute(Unknown Source)
[13:17:13 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
[13:17:13 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[13:17:13 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[13:17:13 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629)
[13:17:13 WARN]:        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:412)
[13:17:13 WARN]:        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:366)
[13:17:13 WARN]:        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:248)
[13:17:13 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1769)
[13:17:13 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:34)
[13:17:13 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:8)
[13:17:13 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[13:17:13 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[13:17:13 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[13:17:13 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:23)
[13:17:13 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1399)
[13:17:13 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188)
[13:17:13 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
[13:17:13 WARN]:        at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1376)
[13:17:13 WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1369)
[13:17:13 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[13:17:13 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1347)
[13:17:13 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1229)
[13:17:13 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[13:17:13 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[13:17:13 ERROR]: [LocaleLib] Unable to query Material: CARROTS
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
Test:
    name: Test
    ask-message: 'Break some carrots!'
    finish-message: 'Nice work!'
    stages:
      ordered:
        '1':
          break-block-names:
          - CARROTS
          break-block-amounts:
          - 5
          break-block-durability:
          - 0
    rewards:
      money: 500
      commands:
      - addxp <player> Herbalism 1000
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
```

**Comment by PikaMug** [comment]
Assuming you're using pre-1.13 version of Minecraft, CARROTS is not a valid item. See https://helpch.at/docs/1.8/org/bukkit/Material.html
