### ISSUE TITLE
Plugin tries to measure distance between two separate worlds

### ISSUE THREAD

**Issue by Septicuss** [PikaMug/Quests#1967]
### What is your Quests version / build number (do *not* say "latest")?

Quests-4.0.4

### Describe the problem and how to replicate it.

Take a quest that requires you to reach a certain location (or an area close to the location) and then teleport to another world. 

### Any console errors to share?

```shell
[08:50:12 ERROR]: [Quests] An error has occurred with Quests. Please report on Github with info below
[08:50:12 WARN]: [Quests] quest = custom75
[08:50:12 WARN]: [Quests] index = 0
[08:50:12 WARN]: [Quests] location = Location{world=CraftWorld{name=11level},x=210.30000001192093,y=66.0,z=-48.027374814498295,pitch=11.25011,yaw=-575.69543}
[08:50:12 WARN]: [Quests] locationsToReach = 1
[08:50:12 WARN]: [Quests] locationsReached = 1
[08:50:12 WARN]: [Quests] hasReached = 1
[08:50:12 WARN]: java.lang.IllegalArgumentException: Cannot measure distance between world and 11level
[08:50:12 WARN]:        at org.bukkit.Location.distanceSquared(Location.java:510)
[08:50:12 WARN]:        at me.blackvein.quests.Quester.reachLocation(Quester.java:2583)
[08:50:12 WARN]:        at me.blackvein.quests.listeners.PlayerListener$4$1.run(PlayerListener.java:993)
[08:50:12 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101)
[08:50:12 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:485)
[08:50:12 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1432)
[08:50:12 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436)
[08:50:12 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1347)
[08:50:12 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1135)
[08:50:12 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[08:50:12 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
custom75:
    name: тренировка на коньках
    ask-message: Хочешь научиться кататься? Бери коньки в судуке справа от тебя и
      снова подходи ко мне!
    finish-message: Я горжусь тобой!
    npc-giver-id: 474
    stages:
      ordered:
        '1':
          npc-ids-to-talk-to:
          - 474
          locations-to-reach:
          - world -162.0 52.0 232.0
          reach-location-radii:
          - 5
          reach-location-names:
          - каток
          start-message: иди к катку, и делай все так как я скажу,а именно ******************************************************************************************************************************
        '2':
          npc-ids-to-talk-to:
          - 474
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 2586
        type: PAPER
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gold","text":"карточка"}],"text":""}'
          lore:
          - '{"extra":[{"text":"прошедший обучение катания на коньках"}],"text":""}'
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-dungeonsxl-plugin: false
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
```

**Comment by Septicuss** [comment]
Old version
