### ISSUE TITLE
Could not pass event Error 

### ISSUE THREAD

**Issue by Stick3rz** [PikaMug/Quests#1996]
### What is your Quests version / build number (do *not* say "latest")?

 Version 3.13.1-77ab390

### Describe the problem and how to replicate it.

Every time a user purchases or sells something from ShopGUI+ my console receives the error listed below. I am currently not using the latest release for Quests as this completely breaking my PlaceholderAPI (I will report this in another bug report later on) However it should be easy to replicate if need be. I am aware this may be down to an error with ShopGUI but as Quests is mentioned I thought I'd come here first.

### Any console errors to share?

```shell
[20:40:43 ERROR]: Could not pass event ShopPostTransactionEvent to Quests v3.13.1-77ab390
java.lang.NoSuchMethodError: 'net.brcdev.shopgui.shop.ShopItem net.brcdev.shopgui.shop.ShopTransactionResult.getShopItem()'
        at com.leonardobishop.quests.bukkit.tasktype.type.dependent.ShopGUIPlusSellTaskType.afterTransaction(ShopGUIPlusSellTaskType.java:49) ~[Quests-3.13.1-77ab390.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1076.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:git-Paper-88]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at net.brcdev.shopgui.shop.ShopManager.handleItemSellAll(ShopManager.java:1212) ~[ShopGUIPlus-1.78.0.jar:?]
        at net.brcdev.shopgui.listener.PlayerListener.clickAmountSelectionGui(PlayerListener.java:427) ~[ShopGUIPlus-1.78.0.jar:?]
        at net.brcdev.shopgui.listener.PlayerListener.onInventoryClick(PlayerListener.java:141) ~[ShopGUIPlus-1.78.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor919.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:git-Paper-88]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3254) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.1.jar:git-Paper-88]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1359) ~[paper-1.19.1.jar:git-Paper-88]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.1.jar:git-Paper-88]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1336) ~[paper-1.19.1.jar:git-Paper-88]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1329) ~[paper-1.19.1.jar:git-Paper-88]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1463) ~[paper-1.19.1.jar:git-Paper-88]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[paper-1.19.1.jar:git-Paper-88]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.1.jar:git-Paper-88]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by PikaMug** [comment]
Wrong plugin. Pretty sure you want https://github.com/LMBishop/Quests
