### ISSUE TITLE
Player Error when selecting a quest

### ISSUE THREAD

**Issue by ThyCodex** [PikaMug/Quests#2002]
### What is your Quests version / build number (do *not* say "latest")?

Version 4.5.
[error_log.txt](https://github.com/PikaMug/Quests/files/9329280/error_log.txt)
2

### Describe the problem and how to replicate it.

player can not select quest 

### Any console errors to share?

```shell
- [Fri 18:47:13 ERROR Minecraft] Could not pass event QuesterPreOpenGUIEvent to QuestsGUI v0.47
java.lang.IllegalArgumentException: Material cannot be null
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
    at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:85)
    at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:73)
    at QuestsGUI-0.47.jar//org.browsit.milkgui.item.Item.<init>(Item.java:127)
    at QuestsGUI-0.47.jar//org.browsit.questsgui.npc.display.DisplayGUI.<init>(DisplayGUI.java:72)
    at QuestsGUI-0.47.jar//org.browsit.questsgui.listeners.QuesterListener.onQuesterPreOpenGUIEvent(QuesterListener.java:32)
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor447.execute(Unknown Source)
    at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:669)
    at Quests-4.5.2.jar//me.blackvein.quests.Quester.showGUIDisplay(Quester.java:4574)
    at Quests-4.5.2.jar//me.blackvein.quests.listeners.CitizensListener.onNPCRightClick(CitizensListener.java:254)
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor395.execute(Unknown Source)
    at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:669)
    at Citizens-2.0.30-b2575.jar//net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:493)
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor342.execute(Unknown Source)
    at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
    at co.aik
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
it is any quest, it wont let the player even open the gui to see the quest
```

**Comment by PikaMug** [comment]
It looks like you have changed a GUI item to an invalid material name within QuestsGUI, or perhaps are using an unsupported version of Minecraft. Either way, use the appropriate channels for QuestsGUI support (this tracker is for Quests only).
