### ISSUE TITLE
Java exception at block break listener

### ISSUE THREAD

**Issue by elb41** [PikaMug/Quests#2018]
### What is your Quests version / build number (do *not* say "latest")?

- 4.5.3 plugin version
- Paper 1.19.2 build 161

### Describe the problem and how to replicate it.

1. Start a server and join (im using debug = true on server.properties for more info about)
2. Join and wait doing stuff like hitting animals (not tested if its necessary at all).
3. In a few seconds the error will come out and a big freeze of the server with it

### Any console errors to share?

```shell
[18:27:42 ERROR]: [STDERR] [org.bukkit.craftbukkit.v1_19_R1.legacy.CraftLegacy] Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[18:27:42 WARN]: java.lang.Exception
[18:27:42 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.legacy.CraftLegacy.<clinit>(CraftLegacy.java:260)
[18:27:42 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.util.CraftMagicNumbers.getMaterial(CraftMagicNumbers.java:113)
[18:27:42 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.block.CraftBlockState.getData(CraftBlockState.java:154)
[18:27:42 WARN]:        at Quests-4.5.3.jar//me.blackvein.quests.listeners.BlockListener.onBlockBreak(BlockListener.java:59)
[18:27:42 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor85.execute(Unknown Source)
[18:27:42 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
[18:27:42 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[18:27:42 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[18:27:42 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670)
[18:27:42 WARN]:        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:369)
[18:27:42 WARN]:        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:328)
[18:27:42 WARN]:        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:214)
[18:27:42 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1882)
[18:27:42 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:42)
[18:27:42 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:15)
[18:27:42 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[18:27:42 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[18:27:42 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[18:27:42 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[18:27:42 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1361)
[18:27:42 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185)
[18:27:42 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[18:27:42 WARN]:        at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1338)
[18:27:42 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1331)
[18:27:42 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[18:27:42 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1309)
[18:27:42 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1197)
[18:27:42 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[18:27:42 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
quests:
  cows:
    name: Kill 10 cows
    ask-message: Can you help me?
    finish-message: Good job!
    stages:
      ordered:
        '1':
          mobs-to-kill:
          - Cow
          mob-amounts:
          - 10
    rewards:
      money: 5000
    planner:
      cooldown: 21600
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: false
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true
```

**Comment by PikaMug** [comment]
This will occur the first time someone interacts with an item or block after the server starts. It's a necessary but harmless process to maintain compatibility with <1.13 servers and should only last a few seconds. If you want the process to go faster, increase available RAM and/or processor speed.

**Comment by eUipKh** [comment]
I know this issue is marked as _wontfix_ but I have the same problem once and this is how I "fix it".

The lag spike on interaction can be easily "hide" while still maintaining <1.13 compatibility, you just need to put a _dummy_ `Material.matchMaterial("STONE", true)` on the **onEnable** method. This way the lag spike would occur when the plugin is starting and not on a player interaction.

**Comment by PikaMug** [comment]
@eUipKh Feel free to submit a pull request.
