### ISSUE TITLE
Quest Failure Condition Error

### ISSUE THREAD

**Issue by CraftXpNetwork** [PikaMug/Quests#2023]
### What is your Quests version / build number (do *not* say "latest")?

4.5.2-b355

### Describe the problem and how to replicate it.

Tried to create a Condition that would cause an active quest to fail when leaving a region.
Also tried to create an Action that would activate upon failing a quest.

Upon leaving the region, the chat spams the player that the quest has been failed repeatedly as they move around. However, when checking their active quests, the quest is still shown as active, and the player can resume the quest.

Also the Action set to for fail-event in the quests.yml file never activates.

### Any console errors to share?

```shell
[19:48:20 ERROR]: Thread Craft Scheduler Thread - 47 - Quests failed main thread check: command dispatch
java.lang.Throwable: null
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[paper-1.19.2.jar:git-Paper-123]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:887) ~[paper-1.19.2.jar:git-Paper-123]
	at me.blackvein.quests.actions.Action.fire(Action.java:379) ~[Quests-4.5.2.jar:?]
	at me.blackvein.quests.Quester.meetsCondition(Quester.java:4978) ~[Quests-4.5.2.jar:?]
	at me.blackvein.quests.listeners.PlayerListener.lambda$playerMove$14(PlayerListener.java:991) ~[Quests-4.5.2.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-123]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-123]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[19:48:20 ERROR]: Thread Craft Scheduler Thread - 48 - Quests failed main thread check: command dispatch
java.lang.Throwable: null
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[paper-1.19.2.jar:git-Paper-123]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:887) ~[paper-1.19.2.jar:git-Paper-123]
	at me.blackvein.quests.actions.Action.fire(Action.java:379) ~[Quests-4.5.2.jar:?]
	at me.blackvein.quests.Quester.meetsCondition(Quester.java:4978) ~[Quests-4.5.2.jar:?]
	at me.blackvein.quests.listeners.PlayerListener.lambda$playerMove$14(PlayerListener.java:991) ~[Quests-4.5.2.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-123]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-123]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[19:48:20 WARN]: [Quests] Plugin Quests v4.5.2-b355 generated an exception while executing task 13252
java.lang.IllegalStateException: Asynchronous command dispatch!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16) ~[paper-1.19.2.jar:git-Paper-123]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:887) ~[paper-1.19.2.jar:git-Paper-123]
	at me.blackvein.quests.actions.Action.fire(Action.java:379) ~[Quests-4.5.2.jar:?]
	at me.blackvein.quests.Quester.meetsCondition(Quester.java:4978) ~[Quests-4.5.2.jar:?]
	at me.blackvein.quests.listeners.PlayerListener.lambda$playerMove$14(PlayerListener.java:991) ~[Quests-4.5.2.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-123]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-123]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[19:48:20 WARN]: [Quests] Plugin Quests v4.5.2-b355 generated an exception while executing task 13231
java.lang.IllegalStateException: Asynchronous command dispatch!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16) ~[paper-1.19.2.jar:git-Paper-123]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:887) ~[paper-1.19.2.jar:git-Paper-123]
	at me.blackvein.quests.actions.Action.fire(Action.java:379) ~[Quests-4.5.2.jar:?]
	at me.blackvein.quests.Quester.meetsCondition(Quester.java:4978) ~[Quests-4.5.2.jar:?]
	at me.blackvein.quests.listeners.PlayerListener.lambda$playerMove$14(PlayerListener.java:991) ~[Quests-4.5.2.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-123]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-123]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[19:48:20 ERROR]: Thread Craft Scheduler Thread - 45 - Quests failed main thread check: command dispatch
java.lang.Throwable: null
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[paper-1.19.2.jar:git-Paper-123]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:887) ~[paper-1.19.2.jar:git-Paper-123]
	at me.blackvein.quests.actions.Action.fire(Action.java:379) ~[Quests-4.5.2.jar:?]
	at me.blackvein.quests.Quester.meetsCondition(Quester.java:4978) ~[Quests-4.5.2.jar:?]
	at me.blackvein.quests.listeners.PlayerListener.lambda$playerMove$14(PlayerListener.java:991) ~[Quests-4.5.2.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-123]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-123]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[19:48:20 ERROR]: Thread Craft Scheduler Thread - 47 - Quests failed main thread check: command dispatch
java.lang.Throwable: null
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[paper-1.19.2.jar:git-Paper-123]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:887) ~[paper-1.19.2.jar:git-Paper-123]
	at me.blackvein.quests.actions.Action.fire(Action.java:379) ~[Quests-4.5.2.jar:?]
	at me.blackvein.quests.Quester.meetsCondition(Quester.java:4978) ~[Quests-4.5.2.jar:?]
	at me.blackvein.quests.listeners.PlayerListener.lambda$playerMove$14(PlayerListener.java:991) ~[Quests-4.5.2.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-123]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-123]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[19:48:20 WARN]: [Quests] Plugin Quests v4.5.2-b355 generated an exception while executing task 13290
java.lang.IllegalStateException: Asynchronous command dispatch!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16) ~[paper-1.19.2.jar:git-Paper-123]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:887) ~[paper-1.19.2.jar:git-Paper-123]
	at me.blackvein.quests.actions.Action.fire(Action.java:379) ~[Quests-4.5.2.jar:?]
	at me.blackvein.quests.Quester.meetsCondition(Quester.java:4978) ~[Quests-4.5.2.jar:?]
	at me.blackvein.quests.listeners.PlayerListener.lambda$playerMove$14(PlayerListener.java:991) ~[Quests-4.5.2.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-123]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-123]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[19:48:20 WARN]: [Quests] Plugin Quests v4.5.2-b355 generated an exception while executing task 13293
java.lang.IllegalStateException: Asynchronous command dispatch!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16) ~[paper-1.19.2.jar:git-Paper-123]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:887) ~[paper-1.19.2.jar:git-Paper-123]
	at me.blackvein.quests.actions.Action.fire(Action.java:379) ~[Quests-4.5.2.jar:?]
	at me.blackvein.quests.Quester.meetsCondition(Quester.java:4978) ~[Quests-4.5.2.jar:?]
	at me.blackvein.quests.listeners.PlayerListener.lambda$playerMove$14(PlayerListener.java:991) ~[Quests-4.5.2.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-123]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-123]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[19:48:20 ERROR]: Thread Craft Scheduler Thread - 48 - Quests failed main thread check: command dispatch
java.lang.Throwable: null
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[paper-1.19.2.jar:git-Paper-123]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:887) ~[paper-1.19.2.jar:git-Paper-123]
	at me.blackvein.quests.actions.Action.fire(Action.java:379) ~[Quests-4.5.2.jar:?]
	at me.blackvein.quests.Quester.meetsCondition(Quester.java:4978) ~[Quests-4.5.2.jar:?]
	at me.blackvein.quests.listeners.PlayerListener.lambda$playerMove$14(PlayerListener.java:991) ~[Quests-4.5.2.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-123]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-123]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[19:48:20 WARN]: [Quests] Plugin Quests v4.5.2-b355 generated an exception while executing task 13298
java.lang.IllegalStateException: Asynchronous command dispatch!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16) ~[paper-1.19.2.jar:git-Paper-123]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:887) ~[paper-1.19.2.jar:git-Paper-123]
	at me.blackvein.quests.actions.Action.fire(Action.java:379) ~[Quests-4.5.2.jar:?]
	at me.blackvein.quests.Quester.meetsCondition(Quester.java:4978) ~[Quests-4.5.2.jar:?]
	at me.blackvein.quests.listeners.PlayerListener.lambda$playerMove$14(PlayerListener.java:991) ~[Quests-4.5.2.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-123]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-123]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[19:48:20 ERROR]: Thread Craft Scheduler Thread - 48 - Quests failed main thread check: command dispatch
java.lang.Throwable: null
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[paper-1.19.2.jar:git-Paper-123]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:887) ~[paper-1.19.2.jar:git-Paper-123]
	at me.blackvein.quests.actions.Action.fire(Action.java:379) ~[Quests-4.5.2.jar:?]
	at me.blackvein.quests.Quester.meetsCondition(Quester.java:4978) ~[Quests-4.5.2.jar:?]
	at me.blackvein.quests.listeners.PlayerListener.lambda$playerMove$14(PlayerListener.java:991) ~[Quests-4.5.2.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-123]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-123]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[19:48:20 WARN]: [Quests] Plugin Quests v4.5.2-b355 generated an exception while executing task 13302
java.lang.IllegalStateException: Asynchronous command dispatch!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16) ~[paper-1.19.2.jar:git-Paper-123]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:887) ~[paper-1.19.2.jar:git-Paper-123]
	at me.blackvein.quests.actions.Action.fire(Action.java:379) ~[Quests-4.5.2.jar:?]
	at me.blackvein.quests.Quester.meetsCondition(Quester.java:4978) ~[Quests-4.5.2.jar:?]
	at me.blackvein.quests.listeners.PlayerListener.lambda$playerMove$14(PlayerListener.java:991) ~[Quests-4.5.2.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-123]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-123]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[19:48:20 ERROR]: Thread Craft Scheduler Thread - 20 - Quests failed main thread check: command dispatch
java.lang.Throwable: null
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[paper-1.19.2.jar:git-Paper-123]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:887) ~[paper-1.19.2.jar:git-Paper-123]
	at me.blackvein.quests.actions.Action.fire(Action.java:379) ~[Quests-4.5.2.jar:?]
	at me.blackvein.quests.Quester.meetsCondition(Quester.java:4978) ~[Quests-4.5.2.jar:?]
	at me.blackvein.quests.listeners.PlayerListener.lambda$playerMove$14(PlayerListener.java:991) ~[Quests-4.5.2.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-123]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-123]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[19:48:20 WARN]: [Quests] Plugin Quests v4.5.2-b355 generated an exception while executing task 13311
java.lang.IllegalStateException: Asynchronous command dispatch!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16) ~[paper-1.19.2.jar:git-Paper-123]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:887) ~[paper-1.19.2.jar:git-Paper-123]
	at me.blackvein.quests.actions.Action.fire(Action.java:379) ~[Quests-4.5.2.jar:?]
	at me.blackvein.quests.Quester.meetsCondition(Quester.java:4978) ~[Quests-4.5.2.jar:?]
	at me.blackvein.quests.listeners.PlayerListener.lambda$playerMove$14(PlayerListener.java:991) ~[Quests-4.5.2.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-123]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-123]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
Here is the conditions setup in the conditions.yml:

Conditions:
  Manor Quest:
    fail-quest: true
    stay-within-region:
    - halloweenmap1

------------------------------
Here is the actions setup for the action I would like to take place upon failing the quest or quitting the quest:

Actions:
  MANOR_ClearItems:
    commands:
    - minecraft:clear <player> stone_pressure_plate{display:{Name:'[{"text":"Orange Checkpoint","italic":false,"color":"gold","bold":true}]'}}
    - minecraft:clear <player> stone_pressure_plate{display:{Name:'[{"text":"Green Checkpoint","italic":false,"color":"dark_green","bold":true}]'}}
    - minecraft:clear <player> stone_pressure_plate{display:{Name:'[{"text":"Purple Checkpoint","italic":false,"color":"light_purple","bold":true}]'}}
    - minecraft:clear <player> polished_blackstone_pressure_plate{display:{Name:'[{"text":"Secret Key Plate","italic":false,"color":"dark_red","bold":true}]'}}
    - minecraft:clear <player> echo_shard{display:{Name:'[{"text":"Soul Shard","italic":false,"color":"light_purple","bold":true}]'}}

------------------------------
Here is a portion of the quests.yml file, stage '3' is where the fail-event comes into play.

    stages:
      ordered:
        '1':
          npc-uuids-to-talk-to:
          - 3f16e02a-0bb7-4f90-9224-78d04aa0ee32
          finish-event: MANOR_StrangeOldMan_Speech1
          objective-override:
          - '&7Click on the &8[&7Strange Old Man&8] &7to talk to him and hear his
            story.'
        '2':
          locations-to-reach:
          - world 735.5 65.0 -688.0
          reach-location-radii:
          - 15
          reach-location-names:
          - Manor Entrance
          start-event: MANOR_GiveWarp
          delay: 10
          objective-override:
          - '&7Type &b/warp Manor &7to travel to the dark woods!'
          - '&7Once there, find the entrance to the &cHaunted Manor&7.'
        '3':
          npc-uuids-to-talk-to:
          - b0b7172a-f824-4d87-98a1-c5d64c76344b
          start-event: Storm_3hr
          finish-event: MANOR_SoulShard
          fail-event: MANOR_ClearItems
          condition: Manor Quest
          delay: 1
          complete-message: '&8[&7Lost Spirit&8]&7: &bHello there… are you… a person?
            A real person?! Do you think you could help me out? There are more like
            me trapped here... Take this and find the rest of us!'
          objective-override:
          - '&7Find the spirit near the main stairwell of the Manor.'
          - '&7Talk to the spirit to recieve a special item.'
        '4':
          npc-uuids-to-talk-to:
          - 0215e002-0e65-428a-853d-29a73a257919
          fail-event: MANOR_ClearItems
          finish-event: MANOR_OrangePlate
          condition: Manor Quest
          delay: 1
          complete-message: '&8[&7Lost Spirit&8]&7: &boh… a person? Please take this!
            It is the essence of my spirit- whatever you do, DO NOT let him have it...
            please, save us...'
          objective-override:
          - '&7Find the lost spirit near the Kitchen of the Manor.'
          - '&7Talk to the spirit to recieve a special item.'

------------------------------

Neither the Action or Condition are functioning properly, note that other actions and conditions in the same files are working okay.
```

**Comment by PikaMug** [comment]
Thanks for the report. Please confirm whether this occurs on the latest 4.6.0 version (you're on 4.5.2).

**Comment by CraftXpNetwork** [comment]
Hi, I just updated and tested it out on version 4.6.0-b361
Still seeing the same issue as before. 

If there's any other info you think you might need that might be helpful to re-creating the issue on your end, let me know.
