### ISSUE TITLE
[12:15:16 ERROR]: Cannot load configuration from stream

### ISSUE THREAD

**Issue by CaptainRexPL** [PikaMug/Quests#2058]
### What is your Quests version / build number (do *not* say "latest")?

version: 4.6.1-b373

### Describe the problem and how to replicate it.

Start the server and click any slot in your inventory that has an item in it. What is even more strange is that it doesn't appear every time I click.

### Any console errors to share?

```shell
[12:23:27 ERROR]: Cannot load configuration from stream
org.bukkit.configuration.InvalidConfigurationException: Top level is not a Map.
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:108) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:335) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at me.blackvein.quests.util.Lang.init(Lang.java:229) ~[Quests-4.6.1.jar:?]
        at me.blackvein.quests.util.Lang.get(Lang.java:98) ~[Quests-4.6.1.jar:?]
        at me.blackvein.quests.listeners.PlayerListener.onInventoryClickEvent(PlayerListener.java:126) ~[Quests-4.6.1.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor587.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-270]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleSetCreativeModeSlot(ServerGamePacketListenerImpl.java:3486) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundSetCreativeModeSlotPacket.handle(ServerboundSetCreativeModeSlotPacket.java:18) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundSetCreativeModeSlotPacket.handle(ServerboundSetCreativeModeSlotPacket.java:12) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-270]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.2.jar:git-Paper-270]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-270]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.2.jar:git-Paper-270]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.2.jar:git-Paper-270]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1389) ~[paper-1.19.2.jar:git-Paper-270]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-270]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-270]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[12:23:27 ERROR]: Cannot load configuration from stream
org.bukkit.configuration.InvalidConfigurationException: Top level is not a Map.
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:108) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:335) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at me.blackvein.quests.util.Lang.init(Lang.java:232) ~[Quests-4.6.1.jar:?]
        at me.blackvein.quests.util.Lang.get(Lang.java:98) ~[Quests-4.6.1.jar:?]
        at me.blackvein.quests.listeners.PlayerListener.onInventoryClickEvent(PlayerListener.java:126) ~[Quests-4.6.1.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor587.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-270]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleSetCreativeModeSlot(ServerGamePacketListenerImpl.java:3486) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundSetCreativeModeSlotPacket.handle(ServerboundSetCreativeModeSlotPacket.java:18) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundSetCreativeModeSlotPacket.handle(ServerboundSetCreativeModeSlotPacket.java:12) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-270]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.2.jar:git-Paper-270]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-270]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.2.jar:git-Paper-270]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.2.jar:git-Paper-270]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1389) ~[paper-1.19.2.jar:git-Paper-270]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-270]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-270]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
# For non-English characters, this file MUST stay encoded in UTF-8
quests:
  custom1:
    name: '2'
    ask-message: Proszę, przynieś mi 3 diamenty
    finish-message: Dziękuję ci. Oto twoja nagroda
    npc-giver-uuid: 0c325998-24a4-472c-a98e-b05ab61115bc
    block-start: world -275.0 63.0 -163.0
    region: __global__
    gui-display:
      ==: org.bukkit.inventory.ItemStack
      v: 3120
      type: DIAMOND
    requirements:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 3120
        type: DIAMOND
      remove-items:
      - false
    stages:
      ordered:
        '1':
          items-to-smelt:
          - ==: org.bukkit.inventory.ItemStack
            v: 3120
            type: DIAMOND_ORE
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 3120
        type: NETHERITE_BLOCK
```

**Comment by PikaMug** [comment]
Run your file through YAML parse like https://yaml-online-parser.appspot.com/ (not affiliated) as there's probably an errant space or tab somewhere.

**Comment by CaptainRexPL** [comment]
I tried to run all of the files through a YAML parser and I even tried to reset the plugin's folder, but the error is still the same.

**Comment by PikaMug** [comment]
My mistake⁠—run your _lang_ file through a YAML parser. If that doesn't help, let me know which language you have set (both in config.yml and your Minecraft client).

**Comment by CaptainRexPL** [comment]
I ran the lang file, but the error was still there so I tried to synchronise the language set client-side with the language used in config.yml and now it works fine. Thank you for fast support.
