### ISSUE TITLE
Uninstalling Quests broke PlaceholderAPI

### ISSUE THREAD

**Issue by astronymity** [PikaMug/Quests#2062]
### What is your Quests version / build number (do *not* say "latest")?

4.7.0

### Describe the problem and how to replicate it.

I installed quests, ran my server, added the placeholder api expansion for quests, then uninstalled quests (deleted folder and .jar file from the plugins folder). All of my placeholders with placeholder API don't work, and when I try to run placeholder api commands, I get a console error.
![2023-01-19_21 12 08](https://user-images.githubusercontent.com/19599094/213622142-3bb69e72-dac3-403f-bb17-819a7aa30d5d.png)

### Any console errors to share?

```shell
Papi dump returned this: https://paste.helpch.at/cugevulave
This is the error I get at startup, and then when I try to use placeholder api commands:
20.01 05:02:34 [Server] INFO [PlaceholderAPI] Placeholder expansion registration initializing...
258	20.01 05:02:34 [Server] INFO [PlaceholderAPI] Fetching available expansion information...
259	20.01 05:02:34 [Server] ERROR [PlaceholderAPI] Failed to load class files of expansion.
260	20.01 05:02:34 [Server] INFO java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: me/blackvein/quests/quests/IQuest
261	20.01 05:02:34 [Server] INFO at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
262	20.01 05:02:34 [Server] INFO at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
263	20.01 05:02:34 [Server] INFO at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
264	20.01 05:02:34 [Server] INFO at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
265	20.01 05:02:34 [Server] INFO at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
266	20.01 05:02:34 [Server] INFO at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1176) ~[?:?]
267	20.01 05:02:34 [Server] INFO at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1647) ~[?:?]
268	20.01 05:02:34 [Server] INFO at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1614) ~[?:?]
269	20.01 05:02:34 [Server] INFO at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
270	20.01 05:02:34 [Server] INFO Caused by: java.lang.NoClassDefFoundError: me/blackvein/quests/quests/IQuest
271	20.01 05:02:34 [Server] INFO at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
272	20.01 05:02:34 [Server] INFO at java.lang.Class.privateGetDeclaredMethods(Class.java:3373) ~[?:?]
273	20.01 05:02:34 [Server] INFO at java.lang.Class.getDeclaredMethods(Class.java:2480) ~[?:?]
274	20.01 05:02:34 [Server] INFO at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.lambda$findExpansionInFile$7(LocalExpansionManager.java:413) ~[PlaceholderAPI-2.11.2.jar:?]
275	20.01 05:02:34 [Server] INFO at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
276	20.01 05:02:34 [Server] INFO ... 6 more
277	20.01 05:02:34 [Server] INFO Caused by: java.lang.ClassNotFoundException: me.blackvein.quests.quests.IQuest
278	20.01 05:02:34 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:432) ~[?:?]
279	20.01 05:02:34 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
280	20.01 05:02:34 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
281	20.01 05:02:34 [Server] INFO at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
282	20.01 05:02:34 [Server] INFO at java.lang.Class.privateGetDeclaredMethods(Class.java:3373) ~[?:?]
283	20.01 05:02:34 [Server] INFO at java.lang.Class.getDeclaredMethods(Class.java:2480) ~[?:?]
284	20.01 05:02:35 [Server] INFO at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.lambda$findExpansionInFile$7(LocalExpansionManager.java:413) ~[PlaceholderAPI-2.11.2.jar:?]
285	20.01 05:02:35 [Server] INFO at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
286	20.01 05:02:35 [Server] INFO ... 6 more
```

**Comment by astronymity** [comment]
Removing quests expansion file inside placeholder api fixed it.
