### ISSUE TITLE
can't use it on 1.8 errors on startup

### ISSUE THREAD

**Issue by luispradoangel2** [PikaMug/Quests#2070]
### What is your Quests version / build number (do *not* say "latest")?

4.7.1

### Describe the problem and how to replicate it.

The plugin doesn't start up at all no files are created and disables itself on paperspigot 1.8.

### Any console errors to share?

```shell
[17:46:55 INFO]: [Quests] Enabling Quests v4.7.0-b384
[17:46:55 ERROR]: Error occurred while enabling Quests v4.7.0-b384 (Is it up to date?)
java.lang.NoSuchMethodError: 'org.bukkit.Material org.bukkit.Material.matchMaterial(java.lang.String, boolean)'
        at me.blackvein.quests.Quests.onEnable(Quests.java:178) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.base/java.lang.Thread.run(Thread.java:833) [?:?]
[17:46:55 INFO]: [Quests] Disabling Quests v4.7.0-b384
[17:46:55 INFO]: [Quests] Saving Quester data...
[17:46:55 INFO]: [Quests] Closing storage...
```

**Comment by PikaMug** [comment]
@luispradoangel2 Try https://ci.codemc.io/job/PikaMug/job/Quests/389/
