### ISSUE TITLE
npc-delivery-id is missing, see quest Le forgeron stage 1

### ISSUE THREAD

**Issue by NayrMelio** [PikaMug/Quests#2078]
### What is your Quests version / build number (do *not* say "latest")?

The version used is 4.7.1-b388

### Describe the problem and how to replicate it.

hey, I would like to know how to correct this error, we have already looked at the npc level but no problem . it's at server startup

### Any console errors to share?

```shell
me.blackvein.quests.exceptions.StageFormatException: npc-delivery-id is missing, see quest Le forgeron stage 1
[12:37:38 WARN]:        at Quests-4.7.1.jar//me.blackvein.quests.Quests.loadQuestStages(Quests.java:3031)
[12:37:38 WARN]:        at Quests-4.7.1.jar//me.blackvein.quests.Quests.loadQuests(Quests.java:1803)
[12:37:38 WARN]:        at Quests-4.7.1.jar//me.blackvein.quests.Quests.lambda$delayLoadQuestInfo$3(Quests.java:850)
[12:37:38 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101)
[12:37:38 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[12:37:38 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1473)
[12:37:38 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[12:37:38 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
[12:37:38 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1173)
[12:37:38 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[12:37:38 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
custom1:
    name: Le forgeron
    ask-message: Salut, j'ai perdu le fer d'une de mes commandes, tu pourrais m'aider
      ?
    finish-message: Oh! Tu me sauves la vie et celle de mon client
    npc-giver-uuid: b8eea08a-85bd-44bc-acf0-081ae9f36d9c
    stages:
      ordered:
        '1':
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 3218
            type: IRON_INGOT
            amount: 16
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 3218
        type: IRON_INGOT
        amount: 32
      - ==: org.bukkit.inventory.ItemStack
        v: 3218
        type: COAL
        amount: 64
      money: 1000
      quest-points: 3
      exp: 170
    planner:
      cooldown: 604800
```

**Comment by PikaMug** [comment]
Recreate the quest in-game and make sure to set an NPC for the delivery objective.
