### ISSUE TITLE
bug !

### ISSUE THREAD

**Issue by shawn695** [PikaMug/Quests#2084]
### What is your Quests version / build number (do *not* say "latest")?

4.8.1

### Describe the problem and how to replicate it.

pluggin keeps saying "pluggin is currently loading, try again later"
![bandicam 2023-04-01 14-40-45-335](https://user-images.githubusercontent.com/92684055/229309830-b5ef7fb6-db3a-4587-a127-cdaa43d19808.jpg)

### Any console errors to share?

```shell
no errors that i can see
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
https://pastebin.com/FJgYUk11

file had to many charectors pastebin ^^^^
```

**Comment by PikaMug** [comment]
Thanks for the report. Will need to see your server's startup log (use Pastebin).

**Comment by shawn695** [comment]
https://pastebin.com/wjduqT35

this issue started after i was making a quests and had to do /questadmin reload

**Comment by PikaMug** [comment]
This excerpt from your log appears to be the issue:

```
[11:39:08] [Server thread/WARN]: [Quests] Task #123 for Quests v4.8.1-b402 generated an exception
java.lang.IllegalArgumentException: No enum constant org.bukkit.entity.EntityType.SKELETONHORSE
	at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
	at org.bukkit.entity.EntityType.valueOf(EntityType.java:25) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at me.blackvein.quests.Quests.loadQuestStages(Quests.java:3417) ~[Quests-4.8.1.jar:?]
	at me.blackvein.quests.Quests.loadQuests(Quests.java:1981) ~[Quests-4.8.1.jar:?]
	at me.blackvein.quests.Quests.lambda$delayLoadQuestInfo$3(Quests.java:846) ~[Quests-4.8.1.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1500) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:488) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

Will look into it soon.

**Comment by PikaMug** [comment]
Your quest ID custom67 (name: '&c13 &aRancher') has an invalid constant in the mobs-to-tame list. The constant `skeletonhorse` should be `skeleton_horse`. I'll have the plugin catch this type of exception in the future, but for now make sure to add the `_`.

**Comment by shawn695** [comment]
yes that was the most recent quest i was trying to complete. i did finish then the plugin asked me to do /questadmin restart then it went to poop. how do i fix this ? cause i cant get back in it to edit using /quests editor

**Comment by shawn695** [comment]
when doing /quests editor the plugin says its still loading try again later ..... says all day long lol

**Comment by PikaMug** [comment]
@shawn695 If you don't feel comfortable with adding the underscore yourself, try this build:
https://ci.codemc.io/job/PikaMug/job/Quests/403/
