### ISSUE TITLE
[PlaceholderAPI] Failed to load expansion Expansion-Quests.jar

### ISSUE THREAD

**Issue by GadzooksAlot** [PikaMug/Quests#2100]
### What is your Quests version / build number (do *not* say "latest")?

Quests 4.8.1
PlaceholderAPI 2.11.3
PlaceholderExpansion-Quests 1.6

### Describe the problem and how to replicate it.

just set up mysql and added the information for it to Quests.
recieved an error saying quests could not load due to a missing dependency Expansion-Quests
i went to spigot and downloaded:        PlaceholderExpansion-Quests 1.6
played it inside   /plugins/PlaceholderAPI
/
expansions
and recieved an error

### Any console errors to share?

```shell
[18:43:05 ERROR]: [PlaceholderAPI] Failed to load expansion Expansion-Quests.jar (is a dependency missing?)
java.lang.NoClassDefFoundError: me/blackvein/quests/quests/IQuest
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
        at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?]
        at java.lang.Class.getDeclaredMethods(Class.java:2504) ~[?:?]
        at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.lambda$findExpansionInFile$7(LocalExpansionManager.java:419) ~[PlaceholderAPI.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.ClassNotFoundException: me.blackvein.quests.quests.IQuest
        at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 11 more
```

**Comment by PikaMug** [comment]
What do you get from running _/quests info_?

**Comment by PikaMug** [comment]
Closing due to lack of response from OP.
