### ISSUE TITLE
Problem with placeholder

### ISSUE THREAD

**Issue by 500gHackfleisch** [PikaMug/Quests#2110]
### What is your Quests version / build number (do *not* say "latest")?

Quests v3.13.3-5a28efa

### Describe the problem and how to replicate it.

Installing Quests and the Quests PlaceholderAPI extention.

### Any console errors to share?

```shell
[22.05 02:48:41.571] INFO: [Citybuild-1] [02:48:40 ERROR]: [PlaceholderAPI] Failed to load expansion Expansion-quests.jar (is a dependency missing?)
[22.05 02:48:41.571] INFO: [Citybuild-1] java.lang.NoClassDefFoundError: me/blackvein/quests/quests/IQuest
[22.05 02:48:41.571] INFO: [Citybuild-1]        at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
[22.05 02:48:41.571] INFO: [Citybuild-1]        at java.lang.Class.privateGetDeclaredMethods(Class.java:3434) ~[?:?]
[22.05 02:48:41.571] INFO: [Citybuild-1]        at java.lang.Class.getDeclaredMethods(Class.java:2536) ~[?:?]
[22.05 02:48:41.572] INFO: [Citybuild-1]        at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.lambda$findExpansionInFile$7(LocalExpansionManager.java:419) ~[PlaceholderAPI-2.11.3.jar:?]
[22.05 02:48:41.572] INFO: [Citybuild-1]        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
[22.05 02:48:41.572] INFO: [Citybuild-1]        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
[22.05 02:48:41.572] INFO: [Citybuild-1]        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
[22.05 02:48:41.572] INFO: [Citybuild-1]        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
[22.05 02:48:41.572] INFO: [Citybuild-1]        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
[22.05 02:48:41.572] INFO: [Citybuild-1]        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
[22.05 02:48:41.572] INFO: [Citybuild-1]        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
[22.05 02:48:41.572] INFO: [Citybuild-1] Caused by: java.lang.ClassNotFoundException: me.blackvein.quests.quests.IQuest
[22.05 02:48:41.572] INFO: [Citybuild-1]        at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
[22.05 02:48:41.573] INFO: [Citybuild-1]        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
[22.05 02:48:41.573] INFO: [Citybuild-1]        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
[22.05 02:48:41.573] INFO: [Citybuild-1]        ... 11 more
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
-
```

**Comment by PikaMug** [comment]
You have the wrong Quests plugin installed.
