### ISSUE TITLE
Can't deliver item to NPC

### ISSUE THREAD

**Issue by ElZylonite** [PikaMug/Quests#2114]
### What is your Quests version / build number (do *not* say "latest")?

Quests 4.8.2

### Describe the problem and how to replicate it.

I'm trying to create a Quest that you have to deliver a specific item to a specific NPC, when the stage came up to deliver the item to the npc, when I'm right clicking the npc doesn't do nothing.

### Any console errors to share?

```shell
[14:52:30 ERROR]: Could not pass event NPCRightClickEvent to Quests v4.8.2-b416
java.lang.NoClassDefFoundError: io/lumine/xikage/mythicmobs/adapters/AbstractEntity
        at com.gmail.berndivader.mythicmobsquests.MythicItemDeliverObjective.onNPCInteract(MythicItemDeliverObjective.java:46) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1320.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-794]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-794]
        at net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:493) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor672.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-794]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2360) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:55) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:12) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1271) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1264) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1338) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1135) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: io.lumine.xikage.mythicmobs.adapters.AbstractEntity
        at java.net.URLClassLoader.findClass(URLClassLoader.java:433) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
        at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:852) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        ... 27 more
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
The quest is in spanish, I don't really think you will understand it if you don't speak spanish.

custom22:
    name: Mision G4 Sunagakure
    ask-message: ¡Objetivos de desafío!
    finish-message: ¡Wau! Gracias por llevarle agua a esos pobres ancianos
    npc-giver-uuid: a0fcc4ed-335f-4358-ba59-3415d6adc989
    gui-display:
      ==: org.bukkit.inventory.ItemStack
      v: 2586
      type: ENCHANTED_BOOK
      meta:
        ==: ItemMeta
        meta-type: ENCHANTED
        display-name: '{"extra":[{"text":"Mision G4 Sunagakure"}],"text":""}'
        lore:
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"yellow","text":"¡Haz
          click para asignar la mision!"}],"text":""}'
        stored-enchants:
          PROTECTION_ENVIRONMENTAL: 1
    requirements:
      permissions:
      - suna.genin
    stages:
      ordered:
        '1':
          npc-uuids-to-talk-to:
          - 4eda14f3-6749-40d2-b575-abb0a3e0deea
          start-message: '&8&l[&eAsistente del &aKazekage&8&l] &7» &aHola, ¿Podrias
            buscar a eusebio y darle unos suministros? Se encuentra en los alrededores
            en una casa afuera de la aldea.'
          complete-message: '&8&l[&9Eusebio&8&l] &7» &aA mi no me va esas movidas,
            dáselas a Eustaquio que a el le encanta.'
        '2':
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 2586
            type: POTION
            meta:
              ==: ItemMeta
              meta-type: POTION
              display-name: '{"extra":[{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_gray","text":"["},{"bold":true,"italic":false,"color":"light_purple","text":"Refresco
                de Fresa"},{"bold":true,"italic":false,"color":"dark_gray","text":"]"}],"text":""}'
              lore:
              - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"aqua","text":"Objetos
                de Mision"}],"text":""}'
              attribute-modifiers:
                GENERIC_ATTACK_SPEED:
                - ==: org.bukkit.attribute.AttributeModifier
                  amount: 0.0
                  name: mmoitemsDecoy
                  uuid: 87851e28-af12-43f6-898e-c62bde6bd0ec
                  operation: 0
              ItemFlags:
              - HIDE_ATTRIBUTES
              internal: H4sIAAAAAAAA/3WOTUvDMBiA33oqgqKCh6ngyCEnjx5kJ2P3rg026UjSQykl7KPCZFhoe5GxH+Vv8I+ZyjaR6iWEPO+T9zkG8OFSiIQbFNqOM8kED2ycKIRBTuiCzpP5a9lWzXBZDsWqWVVvpPDh4qB0pzXZFMEPWSpNjMaHs9+Yj53ANU9keK9TyUL2nCr04OZnMdfsKUbLpUHFAuNGPR9ODtxlIdzSB7rO6ZKuVflSl82i6qIm7jbriMs6jbRRmUUZREwaDY8bottZS0Zk/0TuSBLqtqrfySjfkMOCPbefH01bOyEvyLbYenDda9yNchm6xPPeD3CUFx4MepoWGH9Lf8FAsckOXvWgwinj6j9VC26iDsIXKPAW6c0BAAA=
          npc-delivery-uuids:
          - e746b6b7-5c1f-4016-a0ab-97f3bccbc366
          delivery-messages:
          - Gracias mijo
        '3':
          npc-uuids-to-talk-to:
          - a0fcc4ed-335f-4358-ba59-3415d6adc989
    rewards:
      commands:
      - economia dar <player> 10
      - atributos dar <player> Exp 20
    planner:
      cooldown: 2400
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true
```

**Comment by PikaMug** [comment]
MythicMobs module is outdated, contact its developer.
