### ISSUE TITLE
Console Error When Loading Quests

### ISSUE THREAD

**Issue by autpek** [PikaMug/Quests#2115]
### Where else have you looked for answers to this question?

Discord, Spigot, gitbook.io, google

### Share your question with as much detail as possible.

When loading quests I am getting the following error in console. I have tried downgrading as well and get same issue.

[15:33:02 WARN]: [Quests] Task #34422834 for Quests v4.8.2-b416 generated an exception
java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
        at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
        at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
        at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
        at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
        at me.blackvein.quests.Quests.loadQuestStages(Quests.java:2673) ~[Quests-4.8.2.jar:?]
        at me.blackvein.quests.Quests.loadQuests(Quests.java:1979) ~[Quests-4.8.2.jar:?]
        at me.blackvein.quests.Quests.lambda$delayLoadQuestInfo$3(Quests.java:845) ~[Quests-4.8.2.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.1.jar:git-Paper-111]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.1.jar:git-Paper-111]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1491) ~[paper-1.19.1.jar:git-Paper-111]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.1.jar:git-Paper-111]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1415) ~[paper-1.19.1.jar:git-Paper-111]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[paper-1.19.1.jar:git-Paper-111]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.1.jar:git-Paper-111]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by PikaMug** [comment]
This should be a bug report; not a question, as you have a console error. Please create a new ticket using the "Report a bug" option, and include your quests.yml file via a site like Pastebin.
