### ISSUE TITLE
Got this message when a quest failed, console said to report it here

### ISSUE THREAD

**Issue by LaBarata** [PikaMug/Quests#2127]
### What is your Quests version / build number (do *not* say "latest")?

4.8.2-b416

### Describe the problem and how to replicate it.

Attempted to test a quest in which attackers ambush the player via a Denizen command- Command would not run, quest stopped functioning normally. Nothing wrong with the script, used it perfectly with other quests.

### Any console errors to share?

```shell
[18:53:36 ERROR]: [Quests] An error has occurred with Quests. Please report on Github with info below
[18:53:36 WARN]: [Quests] quest = custom22
[18:53:36 WARN]: [Quests] index = 0
[18:53:36 WARN]: [Quests] location = Location{world=CraftWorld{name=BigCanyonMap},x=-3.542298409851055,y=71.0,z=-15.822483276954049,pitch=8.851324,yaw=1.203357}
[18:53:36 WARN]: [Quests] locationsToReach = 0
[18:53:36 WARN]: [Quests] locationsReached = 0
[18:53:36 WARN]: [Quests] hasReached = 0
[18:53:36 WARN]: java.lang.NullPointerException: Cannot invoke "java.util.UUID.version()" because "uuid" is null
[18:53:36 WARN]:        at Citizens-2.0.31-b3086.jar//net.citizensnpcs.npc.CitizensNPCRegistry.getByUniqueId(CitizensNPCRegistry.java:157)
[18:53:36 WARN]:        at Quests-4.8.2.jar//me.blackvein.quests.dependencies.DenizenTrigger.runDenizenScript(DenizenTrigger.java:34)
[18:53:36 WARN]:        at Quests-4.8.2.jar//me.blackvein.quests.actions.Action.fire(Action.java:466)
[18:53:36 WARN]:        at Quests-4.8.2.jar//me.blackvein.quests.Quest.setStage(Quest.java:334)
[18:53:36 WARN]:        at Quests-4.8.2.jar//me.blackvein.quests.Quest.nextStage(Quest.java:278)
[18:53:36 WARN]:        at Quests-4.8.2.jar//me.blackvein.quests.Quester.finishObjective(Quester.java:4307)
[18:53:36 WARN]:        at Quests-4.8.2.jar//me.blackvein.quests.Quester.reachLocation(Quester.java:3720)
[18:53:36 WARN]:        at Quests-4.8.2.jar//me.blackvein.quests.listeners.PlayerListener.lambda$playerMove$9(PlayerListener.java:1005)
[18:53:36 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[18:53:36 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[18:53:36 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1483)
[18:53:36 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[18:53:36 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
[18:53:36 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1174)
[18:53:36 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[18:53:36 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
custom22:
    name: The Road Less Well Traveled
    ask-message: 'Iroh: Welcome back, my young friend- I think I have some ideas about
      your situation, if you are willing to hear them!'
    finish-message: So there are, in fact, those who wish to strike against benders.
      I cannot say as I blame them, really- Such things are powerful and dangerous.
      Still, we cannot allow them to do as they please. It is time for you to learn
      another technique. Pay attention!
    npc-giver-uuid: 34421ceb-6cf5-463c-8a2b-af8ae2303468
    requirements:
      quests:
      - custom20
    stages:
      ordered:
        '1':
          locations-to-reach:
          - BigCanyonMap -4.0 70.0 -11.0
          reach-location-radii:
          - 5
          reach-location-names:
          - Camino Canyon
          start-event: irohletterjeongjeong
          start-message: 'Iroh: I have heard rumours of a group who hold strong sentiments
            against the bending arts and seek to strike against those able to wield
            them. Please take this letter to Master Jeong Jeong, he will be able to
            help you act further. Make sure to stay safe!'
          complete-message: 'Masked Man: Look, there they are! See? I told you they''d
            need to come back this way! Staking out that town was a great idea! Now,
            get ''em!'
          objective-override:
          - Return to Jeong Jeong through the tunnel outside the fire town
        '2':
          npc-uuids-to-kill:
          - f34812fe-af20-4096-958f-959ad9dd26cf
          - 5a81569a-0a37-47ff-90ac-97cff4dc8cac
          - 0e20e2f5-6cfd-4caa-b88d-af739f3ea26f
          - 82d0fd13-dbd8-46f6-93a9-e31960c17557
          npc-kill-amounts:
          - 1
          - 1
          - 1
          - 1
          start-event: Ambush
          start-message: More of them! I guess Iroh was right to be careful!
          complete-message: Phew- That should be all of them!
          objective-override:
          - Defend yourself from the masked men!
        '3':
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 3337
            type: GLOBE_BANNER_PATTERN
            meta:
              ==: ItemMeta
              meta-type: UNSPECIFIC
              display-name: '{"extra":[{"text":"Iroh''s Letter To Jeong Jeong"}],"text":""}'
              lore:
              - '{"extra":[{"text":"This, a tea-stained scroll"}],"text":""}'
              - '{"extra":[{"text":"holds an important letter"}],"text":""}'
              - '{"extra":[{"text":"addressed to Jeong Jeong."}],"text":""}'
          npc-delivery-uuids:
          - eba97635-4232-4747-b4b3-bf743fba5f22
          delivery-messages:
          - Thank you. Only <amount> more to go!
          start-message: I'd better get this letter delivered- Master Jeong Jeong
            will want to know everything that's happened!
          complete-message: 'Jeong Jeong: So you return- I trust you''ve had enough
            tea to drown an eelfish, then? You were attacked a second time? They knew
            you were coming, did they... Ah, a letter from Iroh- Please let me see
            that... Hm, this is troubling news.'
          objective-override:
          - Deliver the letter to Jeong Jeong!
    rewards:
      commands:
      - lp user <player> promote firebender
      - sudo <player> b h firewheel
      details-override:
      - 'Bending Ability: Fire Wheel'
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true
```

**Comment by PikaMug** [comment]
@LaBarata Thanks for the report. Are these "attackers" players or NPCs (using Sentinel?)? And what is the command you're having Denizen execute?

**Comment by LaBarata** [comment]
Sorry- The attackers are Citizens NPCs using Sentinel, yes. After digging a bit more, I may have found something that might have caused the issue- The script isn’t binding properly to the action (probably because I realize now I made it so that it can’t really work when run from console) and the reason it was working elsewhere was because I implemented it differently, making me think this came about via user error. 

The script itself is just a simple thing, ‘spawn sentinels near player’, effectively. 

Sorry to bug you, wouldn’t have except it said to in the console.

**Comment by PikaMug** [comment]
Am I correct in understanding you found a workaround? If so, that's great!

I'm getting the impression that—despite the error stating it's within Quests—the command is referencing a Citizens NPC that either doesn't exist yet or was spawned in a manner which did not assign it a UUID (a unique identifier which every entity should have). I'll have Quests check for null UUID before trying to run the script, but @fullwall may also want to do so in the CitizensNPCRegistry class.

Will close this shortly if there are no objections.
