### ISSUE TITLE
PAPI expansion fails

### ISSUE THREAD

**Issue by SlimeDog** [PikaMug/Quests#2148]
### What is your Quests version / build number (do *not* say "latest")?

Paper 1.20.2-223 (and previous)
Quests 5.0.0-rc.1-b428
Expansion-Quests 1.6

### Describe the problem and how to replicate it.

- Update Paper
- Update Quests
- Start server
- Read log

### Any console errors to share?

```shell
On server start-up or `papi reload`

[05:08:30 ERROR]: [PlaceholderAPI] Failed to load expansion Expansion-Quests-1.6.jar (is a dependency missing?)
java.lang.NoClassDefFoundError: me/blackvein/quests/quests/IQuest
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
        at java.lang.Class.privateGetDeclaredMethods(Class.java:3578) ~[?:?]
        at java.lang.Class.getDeclaredMethods(Class.java:2676) ~[?:?]
        at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.lambda$findExpansionInFile$7(LocalExpansionManager.java:429) ~[PlaceholderAPI-2.11.5-b182.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
Caused by: java.lang.ClassNotFoundException: me.blackvein.quests.quests.IQuest
        at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 11 more
```
```


### If applicable, can you provide an example quest from quests.yml?

_No response_

**Comment by PikaMug** [comment]
Not much is compatible with the 5.x development builds at this time. This was announced on Discord.

**Comment by SlimeDog** [comment]
Thanks. I will not subscribe to 175 Discord channels, which is the number of MC plugins I follow.
