### ISSUE TITLE
console error

### ISSUE THREAD

**Issue by robtbs** [PikaMug/Quests#2165]
### What is your Quests version / build number (do *not* say "latest")?

5.0.0-rc.2

### Describe the problem and how to replicate it.

on server start up

### Any console errors to share?

```shell
25.11 21:21:54 [Server] INFO [Quests] Loaded 20 Quest(s), 8 Action(s), 1 Condition(s) and 813 Phrase(s)
25.11 21:21:54 [Server] ERROR [Quests] Module error! Seek help from developer of module:
25.11 21:21:54 [Server] WARN java.lang.NoClassDefFoundError: me/blackvein/quests/CustomRequirement
25.11 21:21:54 [Server] WARN at java.base/java.lang.ClassLoader.defineClass1(Native Method)
25.11 21:21:54 [Server] WARN at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
25.11 21:21:54 [Server] WARN at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
25.11 21:21:54 [Server] WARN at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
25.11 21:21:54 [Server] WARN at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
25.11 21:21:54 [Server] WARN at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
25.11 21:21:54 [Server] WARN at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
25.11 21:21:54 [Server] WARN at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
25.11 21:21:54 [Server] WARN at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
25.11 21:21:54 [Server] WARN at java.base/java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:872)
25.11 21:21:54 [Server] WARN at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
25.11 21:21:54 [Server] WARN at java.base/java.lang.Class.forName0(Native Method)
25.11 21:21:54 [Server] WARN at java.base/java.lang.Class.forName(Class.java:467)
25.11 21:21:54 [Server] WARN at Quests-5.0.0-rc.2.jar//me.pikamug.quests.storage.implementation.jar.BukkitModuleJarStorage.loadModule(BukkitModuleJarStorage.java:128)
25.11 21:21:54 [Server] WARN at Quests-5.0.0-rc.2.jar//me.pikamug.quests.storage.implementation.jar.BukkitModuleJarStorage.init(BukkitModuleJarStorage.java:65)
25.11 21:21:54 [Server] WARN at Quests-5.0.0-rc.2.jar//me.pikamug.quests.BukkitQuestsPlugin.lambda$delayLoadQuestInfo$3(BukkitQuestsPlugin.java:636)
25.11 21:21:54 [Server] WARN at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
25.11 21:21:54 [Server] WARN at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
25.11 21:21:54 [Server] WARN at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1479)
25.11 21:21:54 [Server] WARN at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
25.11 21:21:54 [Server] WARN at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1393)
25.11 21:21:54 [Server] WARN at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1170)
25.11 21:21:54 [Server] WARN at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
25.11 21:21:54 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:840)
25.11 21:21:54 [Server] WARN Caused by: java.lang.ClassNotFoundException: me.blackvein.quests.CustomRequirement
25.11 21:21:54 [Server] WARN at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
25.11 21:21:54 [Server] WARN at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
25.11 21:21:54 [Server] WARN at java.base/java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:872)
25.11 21:21:54 [Server] WARN at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
25.11 21:21:54 [Server] WARN ... 24 more
25.11 21:21:54 [Server] ERROR [Quests] Module error! Seek help from developer of module:
25.11 21:21:54 [Server] WARN java.lang.NoClassDefFoundError: me/blackvein/quests/CustomReward
25.11 21:21:54 [Server] WARN at java.base/java.lang.ClassLoader.defineClass1(Native Method)
25.11 21:21:54 [Server] WARN at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
25.11 21:21:54 [Server] WARN at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
25.11 21:21:54 [Server] WARN at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
25.11 21:21:54 [Server] WARN at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
25.11 21:21:54 [Server] WARN at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
25.11 21:21:54 [Server] WARN at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
25.11 21:21:54 [Server] WARN at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
25.11 21:21:54 [Server] WARN at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
25.11 21:21:54 [Server] WARN at java.base/java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:872)
25.11 21:21:54 [Server] WARN at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
25.11 21:21:54 [Server] WARN at java.base/java.lang.Class.forName0(Native Method)
25.11 21:21:54 [Server] WARN at java.base/java.lang.Class.forName(Class.java:467)
25.11 21:21:54 [Server] WARN at Quests-5.0.0-rc.2.jar//me.pikamug.quests.storage.implementation.jar.BukkitModuleJarStorage.loadModule(BukkitModuleJarStorage.java:128)
25.11 21:21:54 [Server] WARN at Quests-5.0.0-rc.2.jar//me.pikamug.quests.storage.implementation.jar.BukkitModuleJarStorage.init(BukkitModuleJarStorage.java:65)
25.11 21:21:54 [Server] WARN at Quests-5.0.0-rc.2.jar//me.pikamug.quests.BukkitQuestsPlugin.lambda$delayLoadQuestInfo$3(BukkitQuestsPlugin.java:636)
25.11 21:21:54 [Server] WARN at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
25.11 21:21:54 [Server] WARN at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
25.11 21:21:54 [Server] WARN at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1479)
25.11 21:21:54 [Server] WARN at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
25.11 21:21:54 [Server] WARN at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1393)
25.11 21:21:54 [Server] WARN at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1170)
25.11 21:21:54 [Server] WARN at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
25.11 21:21:54 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:840)
25.11 21:21:54 [Server] WARN Caused by: java.lang.ClassNotFoundException: me.blackvein.quests.CustomReward
25.11 21:21:54 [Server] WARN at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
25.11 21:21:54 [Server] WARN at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
25.11 21:21:54 [Server] WARN at java.base/java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:872)
25.11 21:21:54 [Server] WARN at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
25.11 21:21:54 [Server] WARN ... 24 more
25.11 21:21:54 [Server] ERROR [Quests] Module error! Seek help from developer of module:
25.11 21:21:54 [Server] WARN java.lang.NoClassDefFoundError: me/blackvein/quests/CustomReward
25.11 21:21:54 [Server] WARN at java.base/java.lang.ClassLoader.defineClass1(Native Method)
25.11 21:21:54 [Server] WARN at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
25.11 21:21:54 [Server] WARN at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
25.11 21:21:54 [Server] WARN at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
25.11 21:21:54 [Server] WARN at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
25.11 21:21:54 [Server] WARN at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
25.11 21:21:54 [Server] WARN at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
25.11 21:21:54 [Server] WARN at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
25.11 21:21:54 [Server] WARN at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
25.11 21:21:54 [Server] WARN at java.base/java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:872)
25.11 21:21:54 [Server] WARN at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
25.11 21:21:54 [Server] WARN at java.base/java.lang.Class.forName0(Native Method)
25.11 21:21:54 [Server] WARN at java.base/java.lang.Class.forName(Class.java:467)
25.11 21:21:54 [Server] WARN at Quests-5.0.0-rc.2.jar//me.pikamug.quests.storage.implementation.jar.BukkitModuleJarStorage.loadModule(BukkitModuleJarStorage.java:128)
25.11 21:21:54 [Server] WARN at Quests-5.0.0-rc.2.jar//me.pikamug.quests.storage.implementation.jar.BukkitModuleJarStorage.init(BukkitModuleJarStorage.java:65)
25.11 21:21:54 [Server] WARN at Quests-5.0.0-rc.2.jar//me.pikamug.quests.BukkitQuestsPlugin.lambda$delayLoadQuestInfo$3(BukkitQuestsPlugin.java:636)
25.11 21:21:54 [Server] WARN at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
25.11 21:21:54 [Server] WARN at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
25.11 21:21:54 [Server] WARN at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1479)
25.11 21:21:54 [Server] WARN at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
25.11 21:21:54 [Server] WARN at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1393)
25.11 21:21:54 [Server] WARN at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1170)
25.11 21:21:54 [Server] WARN at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
25.11 21:21:54 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:840)
25.11 21:21:54 [Server] WARN Caused by: java.lang.ClassNotFoundException: me.blackvein.quests.CustomReward
25.11 21:21:54 [Server] WARN at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
25.11 21:21:54 [Server] WARN at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
25.11 21:21:54 [Server] WARN at java.base/java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:872)
25.11 21:21:54 [Server] WARN at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
25.11 21:21:54 [Server] WARN ... 24 more
25.11 21:21:54 [Server] ERROR [Quests] Module error! Seek help from developer of module:
25.11 21:21:54 [Server] WARN java.lang.NoClassDefFoundError: me/blackvein/quests/CustomRequirement
25.11 21:21:54 [Server] WARN at java.base/java.lang.ClassLoader.defineClass1(Native Method)
25.11 21:21:54 [Server] WARN at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
25.11 21:21:54 [Server] WARN at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
25.11 21:21:54 [Server] WARN at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
25.11 21:21:54 [Server] WARN at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
25.11 21:21:54 [Server] WARN at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
25.11 21:21:54 [Server] WARN at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
25.11 21:21:54 [Server] WARN at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
25.11 21:21:54 [Server] WARN at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
25.11 21:21:54 [Server] WARN at java.base/java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:872)
25.11 21:21:54 [Server] WARN at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
25.11 21:21:54 [Server] WARN at java.base/java.lang.Class.forName0(Native Method)
25.11 21:21:54 [Server] WARN at java.base/java.lang.Class.forName(Class.java:467)
25.11 21:21:54 [Server] WARN at Quests-5.0.0-rc.2.jar//me.pikamug.quests.storage.implementation.jar.BukkitModuleJarStorage.loadModule(BukkitModuleJarStorage.java:128)
25.11 21:21:54 [Server] WARN at Quests-5.0.0-rc.2.jar//me.pikamug.quests.storage.implementation.jar.BukkitModuleJarStorage.init(BukkitModuleJarStorage.java:65)
25.11 21:21:54 [Server] WARN at Quests-5.0.0-rc.2.jar//me.pikamug.quests.BukkitQuestsPlugin.lambda$delayLoadQuestInfo$3(BukkitQuestsPlugin.java:636)
25.11 21:21:54 [Server] WARN at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
25.11 21:21:54 [Server] WARN at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
25.11 21:21:54 [Server] WARN at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1479)
25.11 21:21:54 [Server] WARN at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
25.11 21:21:54 [Server] WARN at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1393)
25.11 21:21:54 [Server] WARN at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1170)
25.11 21:21:54 [Server] WARN at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
25.11 21:21:54 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:840)
25.11 21:21:54 [Server] WARN Caused by: java.lang.ClassNotFoundException: me.blackvein.quests.CustomRequirement
25.11 21:21:54 [Server] WARN at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
25.11 21:21:54 [Server] WARN at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
25.11 21:21:54 [Server] WARN at java.base/java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:872)
25.11 21:21:54 [Server] WARN at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
25.11 21:21:54 [Server] WARN ... 24 more
25.11 21:21:54 [Server] ERROR [Quests] Module error! Seek help from developer of module:
25.11 21:21:54 [Server] WARN java.lang.NoClassDefFoundError: me/blackvein/quests/CustomRequirement
25.11 21:21:54 [Server] WARN at java.base/java.lang.ClassLoader.defineClass1(Native Method)
25.11 21:21:54 [Server] WARN at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
25.11 21:21:54 [Server] WARN at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
25.11 21:21:54 [Server] WARN at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
25.11 21:21:54 [Server] WARN at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
25.11 21:21:54 [Server] WARN at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
25.11 21:21:54 [Server] WARN at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
25.11 21:21:54 [Server] WARN at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
25.11 21:21:54 [Server] WARN at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
25.11 21:21:54 [Server] WARN at java.base/java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:872)
25.11 21:21:54 [Server] WARN at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
25.11 21:21:54 [Server] WARN at java.base/java.lang.Class.forName0(Native Method)
25.11 21:21:54 [Server] WARN at java.base/java.lang.Class.forName(Class.java:467)
25.11 21:21:54 [Server] WARN at Quests-5.0.0-rc.2.jar//me.pikamug.quests.storage.implementation.jar.BukkitModuleJarStorage.loadModule(BukkitModuleJarStorage.java:128)
25.11 21:21:54 [Server] WARN at Quests-5.0.0-rc.2.jar//me.pikamug.quests.storage.implementation.jar.BukkitModuleJarStorage.init(BukkitModuleJarStorage.java:65)
25.11 21:21:54 [Server] WARN at Quests-5.0.0-rc.2.jar//me.pikamug.quests.BukkitQuestsPlugin.lambda$delayLoadQuestInfo$3(BukkitQuestsPlugin.java:636)
25.11 21:21:54 [Server] WARN at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
25.11 21:21:54 [Server] WARN at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
25.11 21:21:54 [Server] WARN at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1479)
25.11 21:21:54 [Server] WARN at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
25.11 21:21:54 [Server] WARN at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1393)
25.11 21:21:54 [Server] WARN at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1170)
25.11 21:21:54 [Server] WARN at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
25.11 21:21:54 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:840)
25.11 21:21:54 [Server] WARN Caused by: java.lang.ClassNotFoundException: me.blackvein.quests.CustomRequirement
25.11 21:21:54 [Server] WARN at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
25.11 21:21:54 [Server] WARN at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
25.11 21:21:54 [Server] WARN at java.base/java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:872)
25.11 21:21:54 [Server] WARN at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
```

**Comment by PikaMug** [comment]
Which modules do you have installed?
