### ISSUE TITLE
Error log

### ISSUE THREAD

**Issue by Blskk** [PikaMug/Quests#2182]
### What is your Quests version / build number (do *not* say "latest")?

paper1.20.1  quests 5.0.0-rc.4-b443

### Describe the problem and how to replicate it.

/questsadmin give player 测试
It will only happen when the player does not have quest at present
### Any console errors to share?

```shell
[08:21:15 INFO]: Lantiann issued server command: /questadmin 给予 Lantiann 测试
> java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "this.compassTargetQuestId" is null
        at Quests-5.0.0-rc.4 (1).jar//me.pikamug.quests.player.BukkitQuester.hardQuit(BukkitQuester.java:4348)
        at Quests-5.0.0-rc.4 (1).jar//me.pikamug.quests.commands.questadmin.subcommands.BukkitQuestadminGiveCommand.execute(BukkitQuestadminGiveCommand.java:113)
        at Quests-5.0.0-rc.4 (1).jar//me.pikamug.quests.commands.questadmin.BukkitQuestadminCommandHandler.check(BukkitQuestadminCommandHandler.java:73)
        at Quests-5.0.0-rc.4 (1).jar//me.pikamug.quests.listeners.BukkitCommandManager.onCommand(BukkitCommandManager.java:53)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:987)
        at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265)
        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:324)
        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:308)
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2354)
        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$21(PlayerConnection.java:2314)
        at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        at net.minecraft.server.TickTask.run(TickTask.java:18)
        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1338)
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1315)
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1308)
        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
        at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1286)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1174)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
        at java.base/java.lang.Thread.run(Thread.java:842)
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
'000002':
    name: 测试
    ask-message: 挑战目标！
    finish-message: 做得好！
    stages:
      ordered:
        '1':
          password-displays:
          - 不告诉你
          password-phrases:
          - 5a4s4da4aw4d6wq
```

**Comment by Blskk** [comment]
In the default2 quest, an error log will occur during the normal completion stage
### Any console errors to share?  two
[08:37:25 INFO]: Lantiann issued server command: /questadmin give Lantiann Mob Hunter
> java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "this.compassTargetQuestId" is null
        at Quests-5.0.0-rc.4 (1).jar//me.pikamug.quests.player.BukkitQuester.hardQuit(BukkitQuester.java:4348)
        at Quests-5.0.0-rc.4 (1).jar//me.pikamug.quests.commands.questadmin.subcommands.BukkitQuestadminGiveCommand.execute(BukkitQuestadminGiveCommand.java:113)
        at Quests-5.0.0-rc.4 (1).jar//me.pikamug.quests.commands.questadmin.BukkitQuestadminCommandHandler.check(BukkitQuestadminCommandHandler.java:73)
        at Quests-5.0.0-rc.4 (1).jar//me.pikamug.quests.listeners.BukkitCommandManager.onCommand(BukkitCommandManager.java:53)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:987)
        at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265)
        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:324)
        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:308)
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2354)
        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$21(PlayerConnection.java:2314)
        at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        at net.minecraft.server.TickTask.run(TickTask.java:18)
        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1338)
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1315)
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1308)
        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
        at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1286)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1174)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
        at java.base/java.lang.Thread.run(Thread.java:842)
[08:37:25 INFO]: [Quests] 7b92be67-9ae3-3729-b002-8e56b252d22b started quest Mob Hunter
[08:37:34 INFO]: Lantiann issued server command: /mm m s zombie 3
[08:37:40 INFO]: Lantiann issued server command: /mm m s pig 3
[08:38:02 INFO]: Lantiann issued server command: /mm m s zombie 3
> java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "this.compassTargetQuestId" is null
        at Quests-5.0.0-rc.4 (1).jar//me.pikamug.quests.player.BukkitQuester.hardQuit(BukkitQuester.java:4348)
        at Quests-5.0.0-rc.4 (1).jar//me.pikamug.quests.quests.BukkitQuest.setStage(BukkitQuest.java:349)
        at Quests-5.0.0-rc.4 (1).jar//me.pikamug.quests.quests.BukkitQuest.doNextStage(BukkitQuest.java:304)
        at Quests-5.0.0-rc.4 (1).jar//me.pikamug.quests.quests.BukkitQuest.nextStage(BukkitQuest.java:283)
        at Quests-5.0.0-rc.4 (1).jar//me.pikamug.quests.player.BukkitQuester.finishObjective(BukkitQuester.java:3777)
        at Quests-5.0.0-rc.4 (1).jar//me.pikamug.quests.player.BukkitQuester.killMob(BukkitQuester.java:3067)
        at Quests-5.0.0-rc.4 (1).jar//me.pikamug.quests.listeners.BukkitPlayerListener.preKillMob(BukkitPlayerListener.java:708)
        at Quests-5.0.0-rc.4 (1).jar//me.pikamug.quests.listeners.BukkitPlayerListener.onEntityDeath(BukkitPlayerListener.java:677)
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1132.execute(Unknown Source)
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:928)
        at net.minecraft.world.entity.EntityLiving.dropAllDeathLoot(EntityLiving.java:1801)
        at net.minecraft.world.entity.EntityLiving.a(EntityLiving.java:1695)
        at net.minecraft.world.entity.EntityLiving.a(EntityLiving.java:1519)
        at net.minecraft.world.entity.monster.EntityZombie.a(EntityZombie.java:318)
        at org.bukkit.craftbukkit.v1_20_R1.entity.CraftLivingEntity.damage(CraftLivingEntity.java:380)
        at MythicLib-dist-1.6.2-20240106.121459-29.jar//io.lumine.mythic.lib.manager.DamageManager.applyDamage(DamageManager.java:162)
        at MythicLib-dist-1.6.2-20240106.121459-29.jar//io.lumine.mythic.lib.manager.DamageManager.registerAttack(DamageManager.java:121)
        at MythicLib-dist-1.6.2-20240106.121459-29.jar//io.lumine.mythic.lib.player.PlayerMetadata.attack(PlayerMetadata.java:136)
        at MythicLib-dist-1.6.2-20240106.121459-29.jar//io.lumine.mythic.lib.player.PlayerMetadata.attack(PlayerMetadata.java:111)
        at MMOItems-6.9.5-20240106.134828-14.jar//net.Indyuce.mmoitems.api.TypeSet.lambda$static$0(TypeSet.java:49)
        at MMOItems-6.9.5-20240106.134828-14.jar//net.Indyuce.mmoitems.api.TypeSet.applyAttackEffect(TypeSet.java:155)
        at MMOItems-6.9.5-20240106.134828-14.jar//net.Indyuce.mmoitems.api.interaction.weapon.Weapon.handleTargetedAttack(Weapon.java:111)
        at MMOItems-6.9.5-20240106.134828-14.jar//net.Indyuce.mmoitems.listener.ItemUse.meleeAttacks(ItemUse.java:132)
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1030.execute(Unknown Source)
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
        at MythicLib-dist-1.6.2-20240106.121459-29.jar//io.lumine.mythic.lib.listener.event.AttackEventListener.registerEvents(AttackEventListener.java:58)
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor845.execute(Unknown Source)
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:264)
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1215)
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1070)
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1014)
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1249)
        at net.minecraft.world.entity.EntityLiving.damageEntity0(EntityLiving.java:2184)
        at net.minecraft.world.entity.EntityLiving.a(EntityLiving.java:1431)
        at net.minecraft.world.entity.monster.EntityZombie.a(EntityZombie.java:318)
        at net.minecraft.world.entity.player.EntityHuman.d(EntityHuman.java:1320)
        at net.minecraft.server.level.EntityPlayer.d(EntityPlayer.java:2168)
        at net.minecraft.server.network.PlayerConnection$4.a(PlayerConnection.java:2913)
        at net.minecraft.network.protocol.game.PacketPlayInUseEntity$1.a(PacketPlayInUseEntity.java:24)
        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:80)
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2837)
        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:67)
        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:12)
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:51)
        at net.minecraft.server.TickTask.run(TickTask.java:18)
        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1338)
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1315)
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1308)
        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
        at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1286)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1174)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
        at java.base/java.lang.Thread.run(Thread.java:842)

**Comment by PikaMug** [comment]
https://ci.codemc.io/job/PikaMug/job/Quests/446/
