### ISSUE TITLE
[PlaceholderAPI] Loading bug

### ISSUE THREAD

**Issue by arnon001** [PikaMug/Quests#2193]
### What is your Quests version / build number (do *not* say "latest")?

Quests v3.13.3-5a28efa

### Describe the problem and how to replicate it.

I installed the plugin to the /PlaceholderAPI/expansions.
and when I reloaded the plugin, I got the error

### Any console errors to share?

```shell
papi reload
[10:35:49 INFO]: [PlaceholderAPI] Placeholder expansion registration initializing...
[10:35:49 INFO]: [PlaceholderAPI] Fetching available expansion information...
[10:35:49 ERROR]: [PlaceholderAPI] Failed to load expansion Expansion-Quests.jar (is a dependency missing?)
java.lang.NoClassDefFoundError: me/pikamug/quests/quests/Quest
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
        at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?]
        at java.lang.Class.getDeclaredMethods(Class.java:2504) ~[?:?]
        at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.lambda$findExpansionInFile$7(LocalExpansionManager.java:429) ~[PlaceholderAPI-2.11.5.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.ClassNotFoundException: me.pikamug.quests.quests.Quest
        at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:592) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        ... 11 more
[10:35:49 INFO]: [PlaceholderAPI] Successfully registered external expansion: worldguard [1.4.2]
[10:35:49 WARN]: [PlaceholderAPI] Cannot load expansion playertime due to a missing plugin: PlayerTime
[10:35:49 INFO]: [PlaceholderAPI] Successfully registered external expansion: playerlist [3.0.3]
[10:35:49 INFO]: [PlaceholderAPI] Successfully registered external expansion: player [2.0.4]
[10:35:49 INFO]: [PlaceholderAPI] Successfully registered external expansion: servertime [3.2]
[10:35:49 INFO]: [PlaceholderAPI] Successfully registered external expansion: vault [1.8.1]
[10:35:49 INFO]: [PlaceholderAPI] Successfully registered external expansion: luckperms [5.4-R2]
[10:35:49 INFO]: [PlaceholderAPI] Successfully registered external expansion: server [2.6.2]
[10:35:49 INFO]: [PlaceholderAPI] Successfully registered external expansion: statistic [2.0.1]
[10:35:49 INFO]: 8 placeholder hook(s) registered!
```

**Comment by PikaMug** [comment]
You are using a different Quests plugin.
