### ISSUE TITLE
Console errors on logout with timer active

### ISSUE THREAD

**Issue by HorusApl** [PikaMug/Quests#2199]
### What is your Quests version / build number (do *not* say "latest")?

5.0.1-b454

### Describe the problem and how to replicate it.

Set any quest of any type with a start action (or any action?) that has a timer of any duration. Once the action/timer has begun, logout and watch your console. I did a 60 second timer test quest of just breaking dirt.

### Any console errors to share?

```shell
[05:26:28 WARN]: [Quests] Task #4646 for Quests v5.0.1-b454 generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.getUniqueId()" because the return value of "me.pikamug.quests.player.BukkitQuester.getPlayer()" is null
        at me.pikamug.quests.player.BukkitQuester.quitQuest(BukkitQuester.java:901) ~[Quests-5.0.1.jar:?]
        at me.pikamug.quests.quests.BukkitQuest.failQuest(BukkitQuest.java:1130) ~[Quests-5.0.1.jar:?]
        at me.pikamug.quests.tasks.BukkitActionTimer.run(BukkitActionTimer.java:36) ~[Quests-5.0.1.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2151]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[purpur-1.20.4.jar:git-Purpur-2151]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1669) ~[purpur-1.20.4.jar:git-Purpur-2151]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.4.jar:git-Purpur-2151]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1548) ~[purpur-1.20.4.jar:git-Purpur-2151]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1236) ~[purpur-1.20.4.jar:git-Purpur-2151]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2151]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
'000099':
    name: Test Quest
    ask-message: Challenge objectives!
    finish-message: Well done!
    stages:
      ordered:
        '1':
          break-block-names:
          - DIRT
          break-block-amounts:
          - 1
          break-block-durability:
          - 0
          start-event: 1MinTimer
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true

With action:

  1MinTimer:
    timer: 60
    cancel-timer: false
```

**Comment by PikaMug** [comment]
@HorusApl Thanks for reporting this. Please let me know whether this build resolves the issue:
https://ci.codemc.io/job/PikaMug/job/Quests/

**Comment by HorusApl** [comment]
[09:10:13 WARN]: [Quests] Task #279 for Quests v5.0.2-b458 generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.sendMessage(String)" because the return value of "me.pikamug.quests.player.Quester.getPlayer()" is null
        at me.pikamug.quests.tasks.BukkitActionTimer.run(BukkitActionTimer.java:39) ~[Quests-5.0.2.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2151]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[purpur-1.20.4.jar:git-Purpur-2151]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1669) ~[purpur-1.20.4.jar:git-Purpur-2151]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.4.jar:git-Purpur-2151]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1548) ~[purpur-1.20.4.jar:git-Purpur-2151]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1236) ~[purpur-1.20.4.jar:git-Purpur-2151]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2151]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[09:10:33 WARN]: [Quests] Task #280 for Quests v5.0.2-b458 generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.sendMessage(String)" because the return value of "me.pikamug.quests.player.Quester.getPlayer()" is null
        at me.pikamug.quests.tasks.BukkitActionTimer.run(BukkitActionTimer.java:39) ~[Quests-5.0.2.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2151]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[purpur-1.20.4.jar:git-Purpur-2151]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1669) ~[purpur-1.20.4.jar:git-Purpur-2151]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.4.jar:git-Purpur-2151]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1548) ~[purpur-1.20.4.jar:git-Purpur-2151]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1236) ~[purpur-1.20.4.jar:git-Purpur-2151]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2151]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]


Same error spam as before.

**Comment by PikaMug** [comment]
@HorusApl https://ci.codemc.io/job/PikaMug/job/Quests/459/

**Comment by HorusApl** [comment]
Looks like some progress, I only got the error after the timer stopped and it attempted to fail the request:

[08:00:35 WARN]: [Quests] Task #435 for Quests v5.0.2-b459 generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.isOnline()" because "player" is null
        at me.pikamug.quests.quests.BukkitQuest.failQuest(BukkitQuest.java:1131) ~[Quests-5.0.2 (1).jar:?]
        at me.pikamug.quests.tasks.BukkitActionTimer.run(BukkitActionTimer.java:36) ~[Quests-5.0.2 (1).jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2151]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[purpur-1.20.4.jar:git-Purpur-2151]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1669) ~[purpur-1.20.4.jar:git-Purpur-2151]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.4.jar:git-Purpur-2151]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1548) ~[purpur-1.20.4.jar:git-Purpur-2151]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1236) ~[purpur-1.20.4.jar:git-Purpur-2151]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2151]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by PikaMug** [comment]
@HorusApl Thanks, let me know if there's any further traces:
https://ci.codemc.io/job/PikaMug/job/Quests/460/

**Comment by HorusApl** [comment]
[06:25:54 INFO]: Horus_Apl issued server command: /quests take Test Quest 1
[06:25:55 INFO]: [Quests] aec51ed3-a7e0-4779-a2f0-512dea126ddc started quest Test Quest 1
[06:25:57 INFO]: Horus_Apl lost connection: Disconnected
[06:26:55 INFO]: [Quests] aec51ed3-a7e0-4779-a2f0-512dea126ddc quit quest Test Quest 1

"Test Quest 1" had a 60 second timer to fail it, so seems we're good! Thank you for your work.
