### ISSUE TITLE
Location Stages not showing up with right click

### ISSUE THREAD

**Issue by MrG00s3** [PikaMug/Quests#2214]
### What is your Quests version / build number (do *not* say "latest")?

Quests-5.0.2

### Describe the problem and how to replicate it.

I create a stage and select select "reach Locations", I go ahead and hit set location and it does nothing. I only found out it was supposed to do something after watching a tutorial on how to do it online.
![Screenshot 2024-05-25 202946](https://github.com/PikaMug/Quests/assets/170843944/3d51088a-719f-4da9-b29b-d311fe337bba)

### Any console errors to share?

```shell
Worldguard keeps saying


[ 20:29:05 ERROR]: Could not pass event PlayerMoveEvent to WorldGuard v7.0.9+5934e49
java.lang.NoSuchMethodError: 'com.sk89q.worldguard.protection.managers.RegionManager com.sk89q.worldguard.bukkit.WorldGuardPlugin.getRegionManager(org.bukkit.World)'
	at com.mewin.WGRegionEvents.WGRegionEventsListener.updateRegions(WGRegionEventsListener.java:113) ~[WGRegionEvents.jar:?]
	at com.mewin.WGRegionEvents.WGRegionEventsListener.onPlayerMove(WGRegionEventsListener.java:76) ~[WGRegionEvents.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor441.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-496]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-496]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-496]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1576) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:29) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$Pos.handle(ServerboundMovePlayerPacket.java:66) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-496]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1465) ~[paper-1.20.4.jar:git-Paper-496]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-496]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:123) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1442) ~[paper-1.20.4.jar:git-Paper-496]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1365) ~[paper-1.20.4.jar:git-Paper-496]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:133) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1343) ~[paper-1.20.4.jar:git-Paper-496]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1232) ~[paper-1.20.4.jar:git-Paper-496]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-496]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]





Constantly
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
I just need a way for a player to walk on a platform and it completes a quest.
```

**Comment by PikaMug** [comment]
Thanks for reporting this. For the time being, try using a slightly older version of WorldGuard.

**Comment by MrG00s3** [comment]
> Thanks for reporting this. For the time being, try using a slightly older version of WorldGuard (or, if this is a 1.20.6 server, update to their 7.0.10 version).

Unfortunately  this didn't fix the issue with quests, If there another plugin needed that I'm missing?

**Comment by PikaMug** [comment]
WorldGuard does require WorldEdit, but this is most likely an issue with the WorldGuard Region Events plugin. Just don't have time to check at the moment.

**Comment by PikaMug** [comment]
It seems WorldGuard Region Events is not compatible with recent versions of WorldGuard. You would have to reach out to its developer or cease using it entirely.
