### ISSUE TITLE
LocaleLib not present on Purpur 1.20.6

### ISSUE THREAD

**Issue by jcxldn** [PikaMug/Quests#2215]
### What is your Quests version / build number (do *not* say "latest")?

v5.0.3 (main branch) for triaging
Initially noticed on v5.0.2 - SpigotMC build

### Describe the problem and how to replicate it.

`Purpur 1.20.6-2215-ver/1.20.6@222387f (2024-05-26T02:04:44Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)`

The issue appears to lie within the call to `localeManager = new LocaleManager();`, wherein we have the following block in the constructor:
```java
        final String packageName = Bukkit.getServer().getClass().getPackage().getName();
        try {
            if (packageName.equals("org.bukkit.craftbukkit")) {
                // Bukkit version is 1.20.5+
                craftMagicNumbers = Class.forName("org.bukkit.craftbukkit.util.CraftMagicNumbers");
                itemClazz = Class.forName("net.minecraft.world.item.Item");
            } else {
                final String version = packageName.split("\\.")[3];
                craftMagicNumbers = Class.forName("org.bukkit.craftbukkit.{v}.util.CraftMagicNumbers".replace("{v}",
                        version));
                if (hasRepackagedNms) {
                    itemClazz = Class.forName("net.minecraft.world.item.Item");
                } else {
                    itemClazz = Class.forName("net.minecraft.server.{v}.Item".replace("{v}", version));
                }
            }
```

If I print the error returned by the constructor I get the following:
```
[14:11:51 WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
[14:11:51 WARN]:        at Quests-5.0.3.jar//me.pikamug.quests.libs.localelib.LocaleManager.<init>(LocaleManager.java:81)
[14:11:51 WARN]:        at Quests-5.0.3.jar//me.pikamug.quests.BukkitQuestsPlugin.onEnable(BukkitQuestsPlugin.java:135)
[14:11:51 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287)
[14:11:51 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[14:11:51 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[14:11:51 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519)
[14:11:51 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:618)
[14:11:51 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:567)
[14:11:51 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:678)
[14:11:51 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:440)
[14:11:51 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:357)
[14:11:51 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1150)
[14:11:51 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326)
[14:11:51 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)
```
which suggests that ` if (packageName.equals("org.bukkit.craftbukkit")) {` is false? If I log `packageName.equals("org.bukkit.craftbukkit")` I get true though, odd.

### Any console errors to share?

```shell
[See above.]
```

**Comment by PikaMug** [comment]
It seems like something went wrong with the Jitpack build for LocaleLib 3.8, which is what's been included in this release of Quests. I think it's time to move LocaleLib to CodeMC, instead. I appreciate your patience while I look into this.

**Comment by PikaMug** [comment]
https://ci.codemc.io/job/PikaMug/job/Quests/470/
