### ISSUE TITLE
1.8.8 Creative Inventory Console Error

### ISSUE THREAD

**Issue by IceGames23** [PikaMug/Quests#2241]
### What is your Quests version / build number (do *not* say "latest")?

5.0.5

### Describe the problem and how to replicate it.

Close creative inventory in 1.8.8

### Any console errors to share?

```shell
[00:25:41 ERROR]: Could not pass event InventoryCreativeEvent to Quests v5.0.5-b480
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:564) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:549) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1840) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at net.minecraft.server.v1_8_R3.PacketPlayInSetCreativeSlot.a(PacketPlayInSetCreativeSlot.java:13) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at net.minecraft.server.v1_8_R3.PacketPlayInSetCreativeSlot.a(PacketPlayInSetCreativeSlot.java:5) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(PlayerConnectionUtils.java:9) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:11) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:881) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:412) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:815) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:648) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$spin$0(MinecraftServer.java:133) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.NoSuchMethodError: 'java.lang.String org.bukkit.entity.Player.getLocale()'
        at me.pikamug.quests.util.BukkitLang.get(BukkitLang.java:70) ~[?:?]
        at me.pikamug.quests.listeners.BukkitPlayerListener.onInventoryClickEvent(BukkitPlayerListener.java:124) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        ... 17 more
```

**Comment by PikaMug** [comment]
@IceGames23 Thanks for reporting this. Please try https://ci.codemc.io/job/PikaMug/job/Quests/481/
