### ISSUE TITLE
Player quests reset

### ISSUE THREAD

**Issue by call911nowplz** [PikaMug/Quests#2242]
### What is your Quests version / build number (do *not* say "latest")?

5.0.2-b469

### Describe the problem and how to replicate it.

One of our server players lost their quests. Attempting to give them a quest gives an error

### Any console errors to share?

```shell
[17:35:03 ERROR]: [Quests] Unable to add questI am a good Witch! for player kieronwarburton. Consider resetting player data or report on Github
[17:35:03 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'questadmin' in plugin Quests v5.0.2-b469
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[lightspigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[lightspigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:1001) ~[lightspigot-1.20.4.jar:git-LightSpigot-"23141ef"
]
        at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[lightspigot-1.20.4.jar:git-LightSpig
ot-"23141ef"]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[lightspigot-1.20.4.jar:git-LightSpigot-"23141
ef"]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[lightspigot-1.20.4.jar:git-LightSpigot-"23141
ef"]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[lightspigot-1.20.4.jar:git-LightSpigot
-"23141ef"]
        at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5) ~[lightspigot-1.20.4.jar:git-LightSpigot-"23141ef"]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[lightspigot-1.20.4.jar:git-LightSpigot
-"23141ef"]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:434) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:336) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:323) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2233) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2193) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[lightspigot-1.20.4.jar:git-LightSpigot-"23141ef"]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1478) ~[lightspigot-1.20.4.jar:git-LightSpigot-"23141ef"]
        at net.minecraft.server.MinecraftServer.wrapRunnable(MinecraftServer.java:197) ~[lightspigot-1.20.4.jar:git-LightSpigot-"23141ef"]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:123) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1455) ~[lightspigot-1.20.4.jar:git-LightSpigot-"23141ef"]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1378) ~[lightspigot-1.20.4.jar:git-LightSpigot-"23141ef"]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:133) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1356) ~[lightspigot-1.20.4.jar:git-LightSpigot-"23141ef"]        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1245) ~[lightspigot-1.20.4.jar:git-LightSpigot-"23141ef"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[lightspigot-1.20.4.jar:git-LightSpigot-"23141ef"]
        at java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.getName()" because the return value of "me.pikamug.quests.player.Quester.getPlayer()" is null
        at me.pikamug.quests.actions.BukkitAction.fire(BukkitAction.java:364) ~[Quests-5.0.2.jar:?]
        at me.pikamug.quests.player.BukkitQuester.takeQuest(BukkitQuester.java:808) ~[Quests-5.0.2.jar:?]
        at me.pikamug.quests.commands.questadmin.subcommands.BukkitQuestadminGiveCommand.execute(BukkitQuestadminGiveCommand.java:126) ~[Quests-5.0.2.jar:?]
        at me.pikamug.quests.commands.questadmin.BukkitQuestadminCommandHandler.check(BukkitQuestadminCommandHandler.java:71) ~[Quests-5.0.2.jar:?]
        at me.pikamug.quests.listeners.BukkitCommandManager.onCommand(BukkitCommandManager.java:53) ~[Quests-5.0.2.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[lightspigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        ... 29 more
```

**Comment by PikaMug** [comment]
@call911nowplz Please confirm whether this still occurs on the latest release (or development build) of Quests.

**Comment by PikaMug** [comment]
Closing due to lack of response from OP.
