### ISSUE TITLE
<item> is not an item error

### ISSUE THREAD

**Issue by StKillReal** [PikaMug/Quests#2243]
### What is your Quests version / build number (do *not* say "latest")?

![344861651-bb1bde49-9a27-47c2-a2b2-f4eda21ebe9c](https://github.com/PikaMug/Quests/assets/60330193/590a682b-fd4e-4431-a07d-3147045d0123)

### Describe the problem and how to replicate it.

constantly see console spam with this error:

### Any console errors to share?

```shell
[10:05:33 ERROR]: Could not pass event PlayerInteractEvent to Quests v5.0.6-b481
java.lang.IllegalArgumentException: WATER isn't an item
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.inventory.ItemStack.of(ItemStack.java:69) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:149) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:128) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at Quests-5.0.6.jar/me.pikamug.quests.listeners.BukkitBlockListener.onBlockUse(BukkitBlockListener.java:341) ~[Quests-5.0.6.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor699.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:1.21-2252-d5c06b4]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.jar:1.21-2252-d5c06b4]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.jar:1.21-2252-d5c06b4]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:594) ~[purpur-1.21.jar:1.21-2252-d5c06b4]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:550) ~[purpur-1.21.jar:1.21-2252-d5c06b4]
        at net.minecraft.world.item.BoatItem.use(BoatItem.java:65) ~[purpur-1.21.jar:1.21-2252-d5c06b4]
        at net.minecraft.world.item.ItemStack.use(ItemStack.java:605) ~[purpur-1.21.jar:1.21-2252-d5c06b4]
        at net.minecraft.server.level.ServerPlayerGameMode.useItem(ServerPlayerGameMode.java:489) ~[purpur-1.21.jar:1.21-2252-d5c06b4]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem(ServerGamePacketListenerImpl.java:2040) ~[purpur-1.21.jar:1.21-2252-d5c06b4]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:47) ~[purpur-1.21.jar:1.21-2252-d5c06b4]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:10) ~[purpur-1.21.jar:1.21-2252-d5c06b4]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:36) ~[purpur-1.21.jar:1.21-2252-d5c06b4]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.jar:1.21-2252-d5c06b4]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.jar:1.21-2252-d5c06b4]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.jar:1.21-2252-d5c06b4]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1513) ~[purpur-1.21.jar:1.21-2252-d5c06b4]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.jar:1.21-2252-d5c06b4]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.jar:1.21-2252-d5c06b4]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1491) ~[purpur-1.21.jar:1.21-2252-d5c06b4]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1484) ~[purpur-1.21.jar:1.21-2252-d5c06b4]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.jar:1.21-2252-d5c06b4]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1443) ~[purpur-1.21.jar:1.21-2252-d5c06b4]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1564) ~[purpur-1.21.jar:1.21-2252-d5c06b4]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1275) ~[purpur-1.21.jar:1.21-2252-d5c06b4]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:332) ~[purpur-1.21.jar:1.21-2252-d5c06b4]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

```

**Comment by PikaMug** [comment]
It's just as the error says; WATER isn't an item. When you created the quest, maybe you meant WATER_BUCKET?

Feel free to include the example quest if you need further assistance.

**Comment by PikaMug** [comment]
On closer inspection, it looks like this is yet another Paper issue:
https://github.com/PaperMC/Paper/blob/8c8b227547fa78b8f3295e4ac8ee066777e04e98/patches/api/0478-Proxy-ItemStack-to-CraftItemStack.patch#L56

Will explore some kind of workaround.

**Comment by PikaMug** [comment]
@StKillReal Please give this build a try. You should be able to test it my clicking on a Water block during quests:
https://ci.codemc.io/job/PikaMug/job/Quests/482/
