### ISSUE TITLE
FabledQuestsModule doesn't work

### ISSUE THREAD

**Issue by Galen3** [PikaMug/Quests#2261]
### What is your Quests version / build number (do *not* say "latest")?

Quests 5.0.6-b491

### Describe the problem and how to replicate it.

I use FabledQuestsModule, and in the consol sendme a WARN and dont work.

### Any console errors to share?

```shell
[16:12:29 WARN]: [Quests] Plugin Quests v5.0.6-b491 generated an exception whilst handling conversation input
java.lang.NoSuchMethodError: 'studio.magemonkey.fabled.api.player.PlayerData studio.magemonkey.fabled.Fabled.getPlayerData(org.bukkit.OfflinePlayer)'
        at studio.magemonkey.fabled.quests.ClassLevelRequirement.testRequirement(ClassLevelRequirement.java:26) ~[?:?]
        at me.pikamug.quests.quests.BukkitQuest.testRequirements(BukkitQuest.java:689) ~[Quests-5.0.6.jar:?]
        at me.pikamug.quests.player.BukkitQuester.takeQuest(BukkitQuester.java:756) ~[Quests-5.0.6.jar:?]
        at me.pikamug.quests.convo.misc.QuestAcceptPrompt.acceptInput(QuestAcceptPrompt.java:122) ~[Quests-5.0.6.jar:?]
        at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:234) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:59) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:2327) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
        at me.pikamug.quests.commands.quests.subcommands.BukkitQuestsChoiceCommand.execute(BukkitQuestsChoiceCommand.java:61) ~[Quests-5.0.6.jar:?]
        at me.pikamug.quests.commands.quests.BukkitQuestsCommandHandler.check(BukkitQuestsCommandHandler.java:70) ~[Quests-5.0.6.jar:?]
        at me.pikamug.quests.listeners.BukkitCommandManager.onCommand(BukkitCommandManager.java:51) ~[Quests-5.0.6.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:999) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
        at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
        at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:434) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:336) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:323) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2231) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2191) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1472) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:123) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1449) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1372) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:133) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1350) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1239) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[pufferfish-1.20.4.jar:git-Pufferfish-52]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
'000003':
    name: testquest
    ask-message: Challenge objectives!
    finish-message: Well done!
    npc-giver-uuid: 722e5adc-94ff-4eb2-9bd0-fc7868a2d9fa
    requirements:
      custom-requirements:
        req1:
          name: Class Level Requirement
          data:
            Level: '1'
    stages:
      ordered:
        '1':
          npc-uuids-to-talk-to:
          - 722e5adc-94ff-4eb2-9bd0-fc7868a2d9fa
          start-event: test_potion
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true
```

**Comment by PikaMug** [comment]
Not a Quests issue. Seek help from the module developer.
