### ISSUE TITLE
Quest Failure NullPointerException with onFail Action

### ISSUE THREAD

**Issue by iTemmy** [PikaMug/Quests#2286]
### What is your Quests version / build number (do *not* say "latest")?

5.1.2-b501

### Describe the problem and how to replicate it.

- Create quest with action to run when stage is failed
- Fail quest in stage that has onFailed action
- Check console for error

### Any console errors to share?

```shell
[08:57:41 WARN]: [Quests] Task #153025 for Quests v5.1.2-b501 generated an exception
java.lang.NullPointerException: Cannot invoke "me.pikamug.quests.quests.components.Stage.getFailAction()" because the return value of "me.pikamug.quests.player.BukkitQuester.getCurrentStage(me.pikamug.quests.quests.Quest)" is null
        at me.pikamug.quests.player.BukkitQuester.lambda$meetsCondition$29(BukkitQuester.java:4358) ~[Quests-5.1.2.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1679) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1558) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
Quest:
  '000001':
    name: Test1
    ask-message: Challenge objectives!
    finish-message: Well done!
    stages:
      ordered:
        '1':
          locations-to-reach:
          - irisWorld -7086.0 87.0 -3627.0
          reach-location-radii:
          - 5
          reach-location-names:
          - 'Location #1'
          fail-event: GiveQuest
          condition: WithinIris
        '2':
          locations-to-reach:
          - irisWorld -7079.0 88.0 -3643.0
          reach-location-radii:
          - 5
          reach-location-names:
          - 'Location #1'
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true

  '000002':
    name: Test 2
    ask-message: Challenge objectives!
    finish-message: Well done!
    stages:
      ordered:
        '1':
          password-displays:
          - aaa
          password-phrases:
          - aaa

Action:
  GiveQuest:
    clear-inventory: false
    fail-quest: false
    commands:
    - qa give <player> Test 2

Condition:
  WithinIris:
    fail-quest: true
    stay-within-world:
    - irisWorld
```

**Comment by iTemmy** [comment]
> @iTemmy Thank you for reporting this. Please try the following build: https://ci.codemc.io/job/PikaMug/job/Quests/504/

I will try it once I finish work today, will re-open if issue is still happening.
