### ISSUE TITLE
Server stops responding when player logs out.

### ISSUE THREAD

**Issue by Seasonull** [PikaMug/Quests#2298]
### What is your Quests version / build number (do *not* say "latest")?

Quests v5.1.4-b507, but it was happening on a previous version as well. Tried updating to fix the issue but didn't work.

### Describe the problem and how to replicate it.

Randomly when a player logs out and I'm running Quests the server will stop responding and start spitting errors in console until it stops randomly but the server does not respond again until killed and restarted. I have tried regenerating Quests/config.yml and Quests/data (folder) but this didn't help either.
[latest (5).log](https://github.com/user-attachments/files/17284637/latest.5.log)
Scroll down to 10:13.

### Any console errors to share?

```shell
See log @ 10:13.

[10:13:31] [Server thread/INFO]: bicudoti lost connection: Timed out
[10:13:41] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - 1.21.1-119-7cd4f2c (MC: 1.21.1) ---
[10:13:41] [Paper Watchdog Thread/ERROR]: The server has not responded for 10 seconds! Creating thread dump
[10:13:41] [Paper Watchdog Thread/ERROR]: ------------------------------
[10:13:41] [Paper Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[10:13:41] [Paper Watchdog Thread/ERROR]: ------------------------------
[10:13:41] [Paper Watchdog Thread/ERROR]: Current Thread: Server thread
[10:13:41] [Paper Watchdog Thread/ERROR]: 	PID: 50 | Suspended: false | Native: false | State: WAITING
[10:13:41] [Paper Watchdog Thread/ERROR]: 	Stack:
[10:13:41] [Paper Watchdog Thread/ERROR]: 		java.base@21/jdk.internal.misc.Unsafe.park(Native Method)
[10:13:41] [Paper Watchdog Thread/ERROR]: 		java.base@21/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
[10:13:41] [Paper Watchdog Thread/ERROR]: 		java.base@21/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1864)
[10:13:41] [Paper Watchdog Thread/ERROR]: 		java.base@21/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3780)
[10:13:41] [Paper Watchdog Thread/ERROR]: 		java.base@21/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3725)
[10:13:41] [Paper Watchdog Thread/ERROR]: 		java.base@21/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1898)
[10:13:41] [Paper Watchdog Thread/ERROR]: 		java.base@21/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2072)
[10:13:41] [Paper Watchdog Thread/ERROR]: 		Quests-5.1.4.jar//me.pikamug.quests.player.BukkitQuester.saveData(BukkitQuester.java:3630)
[10:13:41] [Paper Watchdog Thread/ERROR]: 		Quests-5.1.4.jar//me.pikamug.quests.listeners.BukkitPlayerListener.onPlayerQuit(BukkitPlayerListener.java:948)
[10:13:41] [Paper Watchdog Thread/ERROR]: 		com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor924.execute(Unknown Source)
[10:13:41] [Paper Watchdog Thread/ERROR]: 		org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[10:13:41] [Paper Watchdog Thread/ERROR]: 		co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[10:13:41] [Paper Watchdog Thread/ERROR]: 		org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[10:13:41] [Paper Watchdog Thread/ERROR]: 		io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[10:13:41] [Paper Watchdog Thread/ERROR]: 		io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[10:13:41] [Paper Watchdog Thread/ERROR]: 		org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[10:13:41] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.players.PlayerList.remove(PlayerList.java:605)
[10:13:41] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.network.ServerGamePacketListenerImpl.removePlayerFromWorld(ServerGamePacketListenerImpl.java:2107)
[10:13:41] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2087)
[10:13:41] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.network.ServerCommonPacketListenerImpl.disconnect0(ServerCommonPacketListenerImpl.java:397)
[10:13:41] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.network.ServerCommonPacketListenerImpl.disconnect(ServerCommonPacketListenerImpl.java:388)
[10:13:41] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.network.ServerCommonPacketListenerImpl.disconnect(ServerCommonPacketListenerImpl.java:345)
[10:13:41] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.network.ServerCommonPacketListenerImpl.lambda$handleKeepAlive$0(ServerCommonPacketListenerImpl.java:141)
[10:13:41] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.network.ServerCommonPacketListenerImpl$$Lambda/0x00007f5c9f721200.run(Unknown Source)
[10:13:41] [Paper Watchdog Thread/ERROR]: 		net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:60)
[10:13:41] [Paper Watchdog Thread/ERROR]: 		net.minecraft.util.thread.BlockableEventLoop$$Lambda/0x00007f5c9f721420.get(Unknown Source)
[10:13:41] [Paper Watchdog Thread/ERROR]: 		java.base@21/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[10:13:41] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.TickTask.run(TickTask.java:18)
[10:13:41] [Paper Watchdog Thread/ERROR]: 		net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[10:13:41] [Paper Watchdog Thread/ERROR]: 		net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[10:13:41] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1535)
[10:13:41] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)
[10:13:41] [Paper Watchdog Thread/ERROR]: 		net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[10:13:41] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1512)
[10:13:41] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1505)
[10:13:41] [Paper Watchdog Thread/ERROR]: 		net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
[10:13:41] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1464)
[10:13:41] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1471)
[10:13:41] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1316)
[10:13:41] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
[10:13:41] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer$$Lambda/0x00007f5c9ccba2b0.run(Unknown Source)
[10:13:41] [Paper Watchdog Thread/ERROR]: 		java.base@21/java.lang.Thread.runWith(Thread.java:1596)
[10:13:41] [Paper Watchdog Thread/ERROR]: 		java.base@21/java.lang.Thread.run(Thread.java:1583)
```

**Comment by Seasonull** [comment]
Now I'm seeing this on startup. [17:40:00 WARN]: Couldn't look up profile properties for 71f17181-c618-4e7e-aa31-9d0d0d1fba1c
com.mojang.authlib.exceptions.MinecraftClientException: Failed to read from https://sessionserver.mojang.com/session/minecraft/profile/71f17181c6184e7eaa319d0d0d1fba1c?unsigned=false due to Read timed out
        at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:108) ~[authlib-6.0.54.jar:?]
        at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:57) ~[authlib-6.0.54.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fetchProfileUncached(YggdrasilMinecraftSessionService.java:201) ~[authlib-6.0.54.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fetchProfile(YggdrasilMinecraftSessionService.java:171) ~[authlib-6.0.54.jar:?]
        at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fetchProfile(PaperMinecraftSessionService.java:35) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at org.bukkit.craftbukkit.profile.CraftPlayerProfile.getUpdatedProfile(CraftPlayerProfile.java:180) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:278) ~[?:?]
        at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:304) ~[?:?]
        at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346) ~[?:?]
        at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796) ~[?:?]
        at java.base/java.net.Socket$SocketInputStream.read(Socket.java:1099) ~[?:?]
        at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:489) ~[?:?]
        at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:483) ~[?:?]
        at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70) ~[?:?]
        at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1461) ~[?:?]
        at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1066) ~[?:?]
        at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:291) ~[?:?]
        at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:347) ~[?:?]
        at java.base/java.io.BufferedInputStream.implRead(BufferedInputStream.java:420) ~[?:?]
        at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:399) ~[?:?]
        at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:827) ~[?:?]
        at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:759) ~[?:?]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1690) ~[?:?]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1599) ~[?:?]
        at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:531) ~[?:?]
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:307) ~[?:?]
        at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:84) ~[authlib-6.0.54.jar:?]
        ... 9 more

**Comment by PikaMug** [comment]
I know it says "look for plugins here" but that merely describes what was happening at the time of crash; it does not indicate that Quests is the cause. It's more likely that you have other plugin(s) slowing down your server and disk I/O. Use a performance profiler like [spark](https://www.spigotmc.org/resources/spark.57242/) (not affiliated) to see what needs to be addressed.

The startup error is likely from using third-party launchers. Try this guide https://minecrafthopper.net/help/hosts-file/

**Comment by Seasonull** [comment]
Each time this happens it shows the same thread dumps with Quests in them, which at the very least tells me that if it's not Quests then whatever it is is happening at the same time Quests is doing something. I don't think I use a third party launcher and I don't know what third party launchers are or why people would use them - looks like, to allow cracked clients? I run paper and currently am on a host provider that uses pterodactyl. I honestly don't think Quests is the culprit, but was hoping for some direction or advice on to why this could be happening. I've since removed Quests and the issue has stopped. I was using quests for over around 2 months before this started happening.
