### ISSUE TITLE
Potion error

### ISSUE THREAD

**Issue by Dragsio** [PikaMug/Quests#2302]
### What is your Quests version / build number (do *not* say "latest")?

5.1.4

### Describe the problem and how to replicate it.

Quester does not want to accept the potion, it does not give any error to the player, only the console has an error. I am using Purpur Server 1.21.1.

### Any console errors to share?

```shell
[11:07:45 ERROR Minecraft] Could not pass event NPCRightClickEvent to Quests v5.1.4-b${env.BUILD_NUMBER}
java.lang.NullPointerException: Cannot invoke "org.bukkit.potion.PotionData.getType()" because the return value of "org.bukkit.inventory.meta.PotionMeta.getBasePotionData()" is null
    at Quests-5.1.4-custom.jar//me.pikamug.quests.util.BukkitItemUtil.compareItems(BukkitItemUtil.java:152)
    at Quests-5.1.4-custom.jar//me.pikamug.quests.util.BukkitItemUtil.compareItems(BukkitItemUtil.java:60)
    at Quests-5.1.4-custom.jar//me.pikamug.quests.listeners.BukkitCitizensListener.onNPCRightClick(BukkitCitizensListener.java:81)
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor390.execute(Unknown Source)
    at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
    at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630)
    at Citizens-2.0.35-b3583.jar//net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:637)
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor354.execute(Unknown Source)
    at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
    at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630)
    at net.minecraft.server.network.Server
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
#excerpt

stages:
    ordered:
        '5':
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 3955
            type: POTION
            meta:
              ==: ItemMeta
              meta-type: POTION
              display-name: '{"text":"","extra":[{"text":"Fine Beer","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"white","bold":false}]}'
              lore:
              - '{"text":"","extra":["§t",{"text":"Good Taste","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"dark_gray","bold":false}]}'
              - '{"text":"","extra":["§u"]}'
              - '{"text":"","extra":["§s",{"text":"[","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"dark_gray","bold":false},{"text":"⭑⭑⭑⭑⭑","italic":false,"color":"gray"},{"text":"]","italic":false,"color":"dark_gray"}]}'
              - '{"text":"","extra":["§y",{"text":"Fermented","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}'
              ItemFlags:
              - HIDE_ADDITIONAL_TOOLTIP
              PublicBukkitValues: |-
                {
                    "brewery:brewdata": [B; 86B, 1B, 0B, 0B, 10B, -8B, 0B, 6B, 0B, 4B, 80B, 105B, 118B, 111B, 0B, 0B, 0B, 0B, 0B]
                }
              custom-color:
                ==: Color
                ALPHA: 255
                RED: 255
                BLUE: 51
                GREEN: 211
              custom-effects: []
          npc-delivery-uuids:
          - c3fd99a1-6e48-453f-8097-510f0ad07f39
          delivery-messages:
          - Thanks
          start-message: xyz
          complete-message: ok
```

**Comment by PikaMug** [comment]
This does not look like a vanilla Potion... I can catch the error and inform the player, but most likely you'll want a module for compatibility with whatever plugin is creating these. See https://pikamug.gitbook.io/quests/casual/modules#want-support-for-other-plugins-or-features

**Comment by Dragsio** [comment]
It is Brewery plugin. Compatibility with this plugin worked in MC version 1.20.4.

**Comment by PikaMug** [comment]
Unfortunately, Minecraft 1.21 changed a lot of things, and compatibility with plugins like Brewery was never a guarantee.
