### ISSUE TITLE
PlaceholderAPI error

### ISSUE THREAD

**Issue by PirataGu** [PikaMug/Quests#2303]
### What is your Quests version / build number (do *not* say "latest")?

Quests version 3.15.2-b216e2b

### Describe the problem and how to replicate it.

Every server restart it appears when loading the placeholders.

### Any console errors to share?

```shell
[11:53:43 ERROR]: [PlaceholderAPI] Failed to load expansion Expansion-quests.jar (is a dependency missing?)
java.lang.NoClassDefFoundError: me/pikamug/quests/quests/Quest
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
        at java.lang.Class.privateGetDeclaredMethods(Class.java:3578) ~[?:?]
        at java.lang.Class.getDeclaredMethods(Class.java:2676) ~[?:?]
        at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.lambda$findExpansionInFile$7(LocalExpansionManager.java:429) ~[PlaceholderAPI-2.11.6(2).jar:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
Caused by: java.lang.ClassNotFoundException: me.pikamug.quests.quests.Quest
        at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 11 more
```

**Comment by DeadlykillOfficial** [comment]
Quests doesn't have version 3.1.5 neither the build number is a valid one for this Plugin.
Plesee refer to the correct Author of your Plugin. (this is not the correct place or author for the plugin you are using)

**Comment by PirataGu** [comment]
💀 my god... please delete this post HAHA . Im so sorry!!
