### ISSUE TITLE
"block" is invalid! You may need to update your quests.yml or actions.yml in accordance with https://bit.ly/2BkBNNN

### ISSUE THREAD

**Issue by SimmsRyan97** [PikaMug/Quests#2311]
### What is your Quests version / build number (do *not* say "latest")?

5.1.4

### Describe the problem and how to replicate it.

On server start-up I receive this error. It says to use the correct name for the block but OAK_LOG is correct according to the list, as is STONE.

### Any console errors to share?

```shell
[12:25:54 WARN]: OAK_LOG x 1 is invalid! You may need to update your quests.yml or actions.yml in accordance with https://bit.ly/2BkBNNN
[12:25:54 WARN]: me.pikamug.quests.exceptions.StageFormatException: 'break-block-names' has invalid item name OAK_LOG, see quest Get Wood stage 1
[12:25:54 WARN]:        at Quests-5.1.4.jar//me.pikamug.quests.storage.implementation.file.BukkitQuestYamlStorage.loadQuestStages(BukkitQuestYamlStorage.java:891)
[12:25:54 WARN]:        at Quests-5.1.4.jar//me.pikamug.quests.storage.implementation.file.BukkitQuestYamlStorage.init(BukkitQuestYamlStorage.java:110)
[12:25:54 WARN]:        at Quests-5.1.4.jar//me.pikamug.quests.BukkitQuestsPlugin.lambda$delayLoadQuestInfo$3(BukkitQuestsPlugin.java:661)
[12:25:54 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:78)
[12:25:54 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:474)
[12:25:54 WARN]:        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1801)
[12:25:54 WARN]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1662)
[12:25:54 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1328)
[12:25:54 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:339)
[12:25:54 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[12:25:54 WARN]: STONE x 8 is invalid! You may need to update your quests.yml or actions.yml in accordance with https://bit.ly/2BkBNNN
[12:25:54 ERROR]: Unable to use LEGACY_STONE as item name
[12:25:54 WARN]: java.lang.NullPointerException: Cannot invoke "me.pikamug.quests.util.stack.BlockItemStackFactory.of(org.bukkit.Material, int, short)" because the return value of "me.pikamug.quests.util.stack.BlockItemStacks.getFactory()" is null
[12:25:54 WARN]:        at Quests-5.1.4.jar//me.pikamug.quests.util.stack.BlockItemStack.of(BlockItemStack.java:32)
[12:25:54 WARN]:        at Quests-5.1.4.jar//me.pikamug.quests.util.BukkitItemUtil.processBlockItemStack(BukkitItemUtil.java:276)
[12:25:54 WARN]:        at Quests-5.1.4.jar//me.pikamug.quests.storage.implementation.file.BukkitQuestYamlStorage.loadQuestStages(BukkitQuestYamlStorage.java:883)
[12:25:54 WARN]:        at Quests-5.1.4.jar//me.pikamug.quests.storage.implementation.file.BukkitQuestYamlStorage.init(BukkitQuestYamlStorage.java:110)
[12:25:54 WARN]:        at Quests-5.1.4.jar//me.pikamug.quests.BukkitQuestsPlugin.lambda$delayLoadQuestInfo$3(BukkitQuestsPlugin.java:661)
[12:25:54 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:78)
[12:25:54 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:474)
[12:25:54 WARN]:        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1801)
[12:25:54 WARN]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1662)
[12:25:54 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1328)
[12:25:54 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:339)
[12:25:54 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[12:25:54 WARN]: me.pikamug.quests.exceptions.StageFormatException: 'break-block-names' has invalid item name STONE, see quest Hot Topic stage 1
[12:25:54 WARN]:        at Quests-5.1.4.jar//me.pikamug.quests.storage.implementation.file.BukkitQuestYamlStorage.loadQuestStages(BukkitQuestYamlStorage.java:891)
[12:25:54 WARN]:        at Quests-5.1.4.jar//me.pikamug.quests.storage.implementation.file.BukkitQuestYamlStorage.init(BukkitQuestYamlStorage.java:110)
[12:25:54 WARN]:        at Quests-5.1.4.jar//me.pikamug.quests.BukkitQuestsPlugin.lambda$delayLoadQuestInfo$3(BukkitQuestsPlugin.java:661)
[12:25:54 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:78)
[12:25:54 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:474)
[12:25:54 WARN]:        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1801)
[12:25:54 WARN]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1662)
[12:25:54 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1328)
[12:25:54 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:339)
[12:25:54 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[12:25:54 INFO]: [Quests] Loaded 2 Quest(s), 7 Action(s), 1 Condition(s) and 798 Phrase(s)
[12:25:54 WARN]: [Quests] Citizens was detected, but is not enabled! Fix Citizens to allow linkage.
[12:25:54 WARN]: [Quests] Unable to consider custom objectives because quest for getWood was null
[12:25:54 WARN]: [Quests] Unable to consider custom objectives because quest for hotTopic was null
```

**Comment by PikaMug** [comment]
@SimmsRyan97 Please include a relevant example quest from storage/quests.yml (or the entire file).

**Comment by PikaMug** [comment]
Closing due to lack of response from OP.
