### ISSUE TITLE
[1.21.3] NPC  items-to-deliver not working

### ISSUE THREAD

**Issue by F-luxus** [PikaMug/Quests#2312]
### What is your Quests version / build number (do *not* say "latest")?

Quests v5.1.4-b507

### Describe the problem and how to replicate it.

I have created new quest with  items-to-deliver
Using custom item to deliver to another NPC
When brining item to NPC, items is removing from hand. Console showing errors. After all items are delivered quest not completed and not giving reward

### Any console errors to share?

```shell
[23:00:03 ERROR]: Could not pass event NPCRightClickEvent to Quests v5.1.4-b507
java.lang.NullPointerException: Cannot invoke "me.pikamug.quests.util.stack.BlockItemStackFactory.of(org.bukkit.Material, int, short)" because the return value of "me.pikamug.quests.util.stack.BlockItemStacks.getFactory()" is null
	at Quests-5.1.4.jar/me.pikamug.quests.util.stack.BlockItemStack.of(BlockItemStack.java:32) ~[Quests-5.1.4.jar:?]
	at Quests-5.1.4.jar/me.pikamug.quests.player.BukkitQuester.finishObjective(BukkitQuester.java:3197) ~[Quests-5.1.4.jar:?]
	at Quests-5.1.4.jar/me.pikamug.quests.player.BukkitQuester.deliverToNPC(BukkitQuester.java:2578) ~[Quests-5.1.4.jar:?]
	at Quests-5.1.4.jar/me.pikamug.quests.listeners.BukkitCitizensListener.onNPCRightClick(BukkitCitizensListener.java:91) ~[Quests-5.1.4.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor510.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.3.jar:1.21.3-2335-7a01fd8]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.3.jar:1.21.3-2335-7a01fd8]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at Citizens-2.0.36-b3633.jar/net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:659) ~[Citizens-2.0.36-b3633.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor275.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.3.jar:1.21.3-2335-7a01fd8]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.3.jar:1.21.3-2335-7a01fd8]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl$4.performInteraction(ServerGamePacketListenerImpl.java:2901) ~[purpur-1.21.3.jar:1.21.3-2335-7a01fd8]
	at net.minecraft.server.network.ServerGamePacketListenerImpl$4.onInteraction(ServerGamePacketListenerImpl.java:2954) ~[purpur-1.21.3.jar:1.21.3-2335-7a01fd8]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket$InteractionAction.dispatch(ServerboundInteractPacket.java:138) ~[purpur-1.21.3.jar:1.21.3-2335-7a01fd8]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:89) ~[purpur-1.21.3.jar:1.21.3-2335-7a01fd8]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2890) ~[purpur-1.21.3.jar:1.21.3-2335-7a01fd8]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:76) ~[purpur-1.21.3.jar:1.21.3-2335-7a01fd8]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:14) ~[purpur-1.21.3.jar:1.21.3-2335-7a01fd8]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[purpur-1.21.3.jar:1.21.3-2335-7a01fd8]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.3.jar:1.21.3-2335-7a01fd8]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:154) ~[purpur-1.21.3.jar:1.21.3-2335-7a01fd8]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.3.jar:1.21.3-2335-7a01fd8]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1619) ~[purpur-1.21.3.jar:1.21.3-2335-7a01fd8]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:207) ~[purpur-1.21.3.jar:1.21.3-2335-7a01fd8]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:128) ~[purpur-1.21.3.jar:1.21.3-2335-7a01fd8]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1596) ~[purpur-1.21.3.jar:1.21.3-2335-7a01fd8]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1589) ~[purpur-1.21.3.jar:1.21.3-2335-7a01fd8]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:138) ~[purpur-1.21.3.jar:1.21.3-2335-7a01fd8]
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1540) ~[purpur-1.21.3.jar:1.21.3-2335-7a01fd8]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1550) ~[purpur-1.21.3.jar:1.21.3-2335-7a01fd8]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1386) ~[purpur-1.21.3.jar:1.21.3-2335-7a01fd8]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:342) ~[purpur-1.21.3.jar:1.21.3-2335-7a01fd8]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
quests:
  '000001':
    name: Little Help
    ask-message: Ahoy there, mateys! It's Captain Willy, and I'm in a bit of a pickle!
      Stranded on the high seas, I've got a ship full of important letters that need
      delivering. Can you lend a hand and find them for me?
    finish-message: Well done!
    npc-giver-uuid: dc3ceed3-a722-4ab8-89a0-f3491b95d817
    stages:
      ordered:
        '1':
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 4082
            type: PAPER
            meta:
              ==: ItemMeta
              meta-type: UNSPECIFIC
              display-name: '{"text":"","extra":["Delivery to Australia"]}'
              lore:
              - '{"text":"","extra":[" "]}'
              - '{"text":"","extra":[{"text":"From: ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gold","bold":false},{"text":"Willy","italic":false,"color":"dark_red"}]}'
              - '{"text":"","extra":[{"text":"To: ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gold","bold":false},{"text":"Mayor
                of Australia","italic":false,"color":"dark_red"}]}'
          - ==: org.bukkit.inventory.ItemStack
            v: 4082
            type: PAPER
            meta:
              ==: ItemMeta
              meta-type: UNSPECIFIC
              display-name: '{"text":"","extra":["Delivery to North America"]}'
              lore:
              - '{"text":"","extra":[" "]}'
              - '{"text":"","extra":[{"text":"From: ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gold","bold":false},{"text":"Willy","italic":false,"color":"dark_red"}]}'
              - '{"text":"","extra":[{"text":"To: ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gold","bold":false},{"text":"Mayor
                of North America","italic":false,"color":"dark_red"}]}'
          - ==: org.bukkit.inventory.ItemStack
            v: 4082
            type: PAPER
            meta:
              ==: ItemMeta
              meta-type: UNSPECIFIC
              display-name: '{"text":"","extra":["Delivery to South America"]}'
              lore:
              - '{"text":"","extra":[" "]}'
              - '{"text":"","extra":[{"text":"From: ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gold","bold":false},{"text":"Willy","italic":false,"color":"dark_red"}]}'
              - '{"text":"","extra":[{"text":"To: ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gold","bold":false},{"text":"Mayor
                of South America","italic":false,"color":"dark_red"}]}'
          - ==: org.bukkit.inventory.ItemStack
            v: 4082
            type: PAPER
            meta:
              ==: ItemMeta
              meta-type: UNSPECIFIC
              display-name: '{"text":"","extra":["Delivery to Europe"]}'
              lore:
              - '{"text":"","extra":[" "]}'
              - '{"text":"","extra":[{"text":"From: ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gold","bold":false},{"text":"Willy","italic":false,"color":"dark_red"}]}'
              - '{"text":"","extra":[{"text":"To: ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gold","bold":false},{"text":"Mayor
                of Europe","italic":false,"color":"dark_red"}]}'
          - ==: org.bukkit.inventory.ItemStack
            v: 4082
            type: PAPER
            meta:
              ==: ItemMeta
              meta-type: UNSPECIFIC
              display-name: '{"text":"","extra":["Delivery to North Asia"]}'
              lore:
              - '{"text":"","extra":[" "]}'
              - '{"text":"","extra":[{"text":"From: ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gold","bold":false},{"text":"Willy","italic":false,"color":"dark_red"}]}'
              - '{"text":"","extra":[{"text":"To: ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gold","bold":false},{"text":"Mayor
                of North Asia","italic":false,"color":"dark_red"}]}'
          - ==: org.bukkit.inventory.ItemStack
            v: 4082
            type: PAPER
            meta:
              ==: ItemMeta
              meta-type: UNSPECIFIC
              display-name: '{"text":"","extra":["Delivery to Africa"]}'
              lore:
              - '{"text":"","extra":[" "]}'
              - '{"text":"","extra":[{"text":"From: ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gold","bold":false},{"text":"Willy","italic":false,"color":"dark_red"}]}'
              - '{"text":"","extra":[{"text":"To: ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gold","bold":false},{"text":"Mayor
                of Africa","italic":false,"color":"dark_red"}]}'
          npc-delivery-uuids:
          - 0445b2eb-245d-430c-9234-25b2d27f63b0
          - 0445b2eb-245d-430c-9234-25b2d27f63b0
          - 0445b2eb-245d-430c-9234-25b2d27f63b0
          - 0445b2eb-245d-430c-9234-25b2d27f63b0
          - 0445b2eb-245d-430c-9234-25b2d27f63b0
          - 0445b2eb-245d-430c-9234-25b2d27f63b0
          delivery-messages:
          - Keep searching!
          - Keep searching!
          - Keep searching!
          - Keep searching!
          - Keep searching!
          - Keep searching!
          start-message: Go and searh my ship!
          complete-message: Good Job! I will check now these letters. I will give
            you reward
    rewards:
      money: 400
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true
```

**Comment by PikaMug** [comment]
@F-luxus Thanks for reporting this. Please let me know if the following build helps:
https://ci.codemc.io/job/PikaMug/job/Quests/511/
