### ISSUE TITLE
Error occurred while dispatching BREAK_BLOCK for quest ID with parties progression

### ISSUE THREAD

**Issue by pak404** [PikaMug/Quests#2315]
### What is your Quests version / build number (do *not* say "latest")?

5.1.5-b512

### Describe the problem and how to replicate it.

I am not sure if I have understood the quests.yml incorrectly, but I have made 150 quests and all of them work but and the ones that are party quests will spam warnings in console when 2 players (or more) are in same party and progression sharing is set to 1 there will be warnings in the console everytime party members in quests place  or break a block and its making console unreadable. This happens when party members have accepted the same quest.  I tested this on my local server with only one quest too.

### Any console errors to share?

```shell
[08:04:48] [Server thread/ERROR]: [Quests] Error occurred while dispatching BREAK_BLOCK for quest ID 000001
[08:04:48] [Server thread/WARN]: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
[08:04:48] [Server thread/WARN]: 	at java.base/java.util.LinkedList.checkElementIndex(LinkedList.java:566)
[08:04:48] [Server thread/WARN]: 	at java.base/java.util.LinkedList.get(LinkedList.java:487)
[08:04:48] [Server thread/WARN]: 	at Quests-5.1.5.jar//me.pikamug.quests.listeners.BukkitBlockListener.lambda$onBlockPlace$4(BukkitBlockListener.java:283)
[08:04:48] [Server thread/WARN]: 	at Quests-5.1.5.jar//me.pikamug.quests.player.BukkitQuester.dispatchMultiplayerEverything(BukkitQuester.java:4336)
[08:04:48] [Server thread/WARN]: 	at Quests-5.1.5.jar//me.pikamug.quests.listeners.BukkitBlockListener.onBlockPlace(BukkitBlockListener.java:278)
[08:04:48] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor191.execute(Unknown Source)
[08:04:48] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[08:04:48] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[08:04:48] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[08:04:48] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[08:04:48] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[08:04:48] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[08:04:48] [Server thread/WARN]: 	at org.bukkit.craftbukkit.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:459)
[08:04:48] [Server thread/WARN]: 	at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:487)
[08:04:48] [Server thread/WARN]: 	at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:606)
[08:04:48] [Server thread/WARN]: 	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1942)
[08:04:48] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:44)
[08:04:48] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:11)
[08:04:48] [Server thread/WARN]: 	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56)
[08:04:48] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[08:04:48] [Server thread/WARN]: 	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[08:04:48] [Server thread/WARN]: 	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[08:04:48] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1535)
[08:04:48] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)
[08:04:48] [Server thread/WARN]: 	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[08:04:48] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1512)
[08:04:48] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1505)
[08:04:48] [Server thread/WARN]: 	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
[08:04:48] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1464)
[08:04:48] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1471)
[08:04:48] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1316)
[08:04:48] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
[08:04:48] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
quests:
  '000001':
    name: test
    ask-message: Challenge objectives!
    finish-message: Well done!
    stages:
      ordered:
        '1':
          break-block-names:
          - STONE
          break-block-amounts:
          - 5
          break-block-durability:
          - 0
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: false
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true
```

**Comment by PikaMug** [comment]
@pak404 Thanks for your patience. Please give this build a try:
https://ci.codemc.io/job/PikaMug/job/Quests/514/
