### ISSUE TITLE
Cant do missions on first login

### ISSUE THREAD

**Issue by Deywark** [PikaMug/Quests#783]
This is the error code.

[11:12:40 WARN]: java.lang.NullPointerException
[11:12:40 WARN]:        at me.blackvein.quests.Quests.getQuest(Quests.java:3055)
[11:12:40 WARN]:        at me.blackvein.quests.Quests$QuestPrompt.acceptInput(Quests.java:364)
[11:12:40 WARN]:        at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:235)
[11:12:40 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:60)
[11:12:40 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1420)
[11:12:40 WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnection$2.run(PlayerConnection.java:1602)
[11:12:40 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1033)
[11:12:40 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[11:12:40 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940)
[11:12:40 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837)
[11:12:40 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by PikaMug** [comment]
Closing as OP did not follow issue instructions (missing Quests version, no description, did not post error using Pastebin).

**Comment by Deywark** [comment]
The error is resolved, i dont put the correct perms. Thanks for your
response. ^^
