### ISSUE TITLE
Can't save a quest. Java errors

### ISSUE THREAD

**Issue by tiradorus** [PikaMug/Quests#840]
**What is your Quests version / build number (do _not_ say "latest")?**

The latest
*troll*
Okay it's the 3.7.4 =)
Server's version: 1.8.8

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Just ... can't save a quest :S 
WIth any configuration of the Quest, i can't save it

Here are the java arrors whil i write '1' to save the quest (The 2 works to continue editing)

```
14:31:49: Error handling conversation prompt
java.lang.NullPointerException
at me.blackvein.quests.QuestFactory.saveQuest(QuestFactory.java:1361) ~[?:?]
at me.blackvein.quests.QuestFactory$SavePrompt.acceptInput(QuestFactory.java:706) ~[?:?]
at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:229) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.craftbukkit.v1_8_R3.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:58) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1029) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.PlayerConnection$5.evaluate(PlayerConnection.java:1011) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.craftbukkit.v1_8_R3.util.Waitable.run(Waitable.java:24) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:729) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

```
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

All quests are doing the same result.

**Comment by PikaMug** [comment]
Thanks for the report! Quests 3.7.4 has been re-uploaded with a fix; please download the "new" version.
