### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by SlimeDog** [PikaMug/Quests#845]
**What is your Quests version / build number (do _not_ say "latest")?**
Spigot 1.13.2 final or Spigot 1.14.3 (Jenkins 2400) git-Spigot-5e4e7f3-5f88938 (MC: 1.14.3) (Implementing API version 1.14.3-R0.1-SNAPSHOT)
Quests 3.7.4

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
NoClassDefFoundError with latest bleeding edge Denizen build
- Update Denizen to 1.1.0-b945
- Start server
- Observe console/log ERROR

```[08:52:52] [Server thread/ERROR]: Error occurred while enabling Quests v3.7.4-b${env.BUILD_NUMBER} (Is it up to date?)
java.lang.NoClassDefFoundError: net/aufdemrand/denizen/Denizen
        at me.blackvein.quests.Dependencies.init(Dependencies.java:129) ~[?:?]
        at me.blackvein.quests.Quests.onEnable(Quests.java:170) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[spigot-1.13.2.jar-2019-04-22-2230:git-Spigot-1a3504a-a46fdbc]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:347) [spigot-1.13.2.jar-2019-04-22-2230:git-Spigot-1a3504a-a46fdbc]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [spigot-1.13.2.jar-2019-04-22-2230:git-Spigot-1a3504a-a46fdbc]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436) [spigot-1.13.2.jar-2019-04-22-2230:git-Spigot-1a3504a-a46fdbc]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350) [spigot-1.13.2.jar-2019-04-22-2230:git-Spigot-1a3504a-a46fdbc]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580) [spigot-1.13.2.jar-2019-04-22-2230:git-Spigot-1a3504a-a46fdbc]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542) [spigot-1.13.2.jar-2019-04-22-2230:git-Spigot-1a3504a-a46fdbc]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420) [spigot-1.13.2.jar-2019-04-22-2230:git-Spigot-1a3504a-a46fdbc]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot-1.13.2.jar-2019-04-22-2230:git-Spigot-1a3504a-a46fdbc]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [spigot-1.13.2.jar-2019-04-22-2230:git-Spigot-1a3504a-a46fdbc]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: net.aufdemrand.denizen.Denizen
        at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:136) ~[spigot-1.13.2.jar-2019-04-22-2230:git-Spigot-1a3504a-a46fdbc]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:82) ~[spigot-1.13.2.jar-2019-04-22-2230:git-Spigot-1a3504a-a46fdbc]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        ... 13 more
```

**Comment by PikaMug** [comment]
The latest official release of Denizen is 1.0.6 and, although I couldn't find a 1.10 development build, Quests only supports Spigot releases from https://www.spigotmc.org/resources/denizen.21039/

**Comment by SlimeDog** [comment]
No worries. Until Quests 3.7.4, it loaded on (then-current) Spigot 1.14.3, so I thought maybe it was an error. I will be patient until Denizen 1.1.0 is official released.

**Comment by SXRWahrheit** [comment]
This issue fully breaks Quests and it would be nice if a dev build or alternative branch were available for those of us who are attempting to test the new Denizen builds.

**Comment by PikaMug** [comment]
I see now they have a separate Jenkins project for development builds. Nonetheless, I’m hesitant to support something that could change again before release (or at least before it’s considered stable). If I find time I could make a separate branch for it, but I’m currently working on #794 and, as mentioned there, I’ll eventually need to come up with a way to support two versions of the same plugin regardless.

For now, I’d encourage you both to reach out to the Denizen developers and make sure the class name change wasn’t an accident or oversight.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SXRWahrheit** [comment]
It was not an accident or oversight. It will be pushed to Spigot as soon as any latent bugs are squashed - and it's already generally stable.

https://i.imgur.com/abnDTJT.png

**Comment by mcmonkey4eva** [comment]
The necessary changes are: `net.aufdemrand` becomes `com.denizenscript`, `dPlayer` becomes `PlayerTag`

At a glance I don't think anything else applies.

**Comment by Elxafil** [comment]
Has this been fixed yet?

**Comment by SXRWahrheit** [comment]
There has not been a commit, so no.

**Comment by mcmonkey4eva** [comment]
I created a PR to fix this for you at #863

**Comment by mcmonkey4eva** [comment]
@PikaMug I'm looking at your commit and I'm really confused why you did any of that. Like... literally what benefit is that massive pile of reflection? Anyone who updates to latest Quests can just also update to latest Denizen, there's no need for any complicated compatibility.

**Comment by PikaMug** [comment]
@mcmonkey4eva As I alluded to in #863, Quests supports protocol back to Minecraft 1.7.10 and thus this was necessary to provide an option for servers which cannot update. Those running Denizen 1.1.0+ will not be subject to using reflection.

Dev build - https://ci.codemc.org/job/PikaMug/job/Quests/6/
