### ISSUE TITLE
failQuest on Timed Quest quest failing.

### ISSUE THREAD

**Issue by stronger108** [PikaMug/Quests#854]
Here is the error I get when the player does not collect 10 dirt in 40 seconds. Nothing is printed into the chat and the quest is still active after this error.

```
[09:57:40] [Craft Scheduler Thread - 49/WARN]: [Quests] Plugin Quests v3.7.5 generated an exception while executing task 16989
java.lang.IllegalStateException: QuesterPreFailQuestEvent cannot be triggered asynchronously from another thread.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:511) ~[server.jar:git-Spigot-5e4e7f3-2349feb]
        at me.blackvein.quests.Quest.failQuest(Quest.java:707) ~[?:?]
        at me.blackvein.quests.timers.ActionTimer.run(ActionTimer.java:39) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[server.jar:git-Spigot-5e4e7f3-2349feb]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [server.jar:git-Spigot-5e4e7f3-2349feb]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_181]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
```

**Comment by PikaMug** [comment]
Use https://ci.codemc.org/job/PikaMug/job/Quests/3/
