### ISSUE TITLE
Could not pass event DPlayerLeaveDGroupEvent to Quests v3.7.6-b5

### ISSUE THREAD

**Issue by BearLeonLight** [PikaMug/Quests#867]
This server is running CraftBukkit version git-Spigot-9de398a-9c887d4 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
Error message
[19:52:58] [Server thread/ERROR]: Could not pass event DPlayerLeaveDGroupEvent to Quests v3.7.6-b5
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at de.erethon.dungeonsxl.command.LeaveCommand.onExecute(LeaveCommand.java:77) ~[?:?]
        at de.erethon.dungeonsxl.util.commons.command.DRECommandExecutor.onCommand(DRECommandExecutor.java:67) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:710) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1641) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1481) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:910) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:903) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:887) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:820) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.NullPointerException
        at me.blackvein.quests.listeners.DungeonsListener.onPlayerLeaveEvent(DungeonsListener.java:50) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        ... 23 more

**Comment by PikaMug** [comment]
https://github.com/PikaMug/Quests/blob/master/main/src/main/java/me/blackvein/quests/listeners/DungeonsListener.java#L50

@Sataniel98 It seems DPlayerLeaveDGroupEvent#getDGroup() can return null? How is that possible?

**Comment by BearLeonLight** [comment]
I am not very clear, but I will encounter such a situation in use, need to update? In my image, I use 3.7.6-b5 to update it, can I download it?

**Comment by BearLeonLight** [comment]
This is my actual situation 。/dxl edit test and /dxl Leave 
[16:22:27] [Server thread/INFO]: BearLeon issued server command: /dxl edit test
[16:22:27] [Server thread/INFO]: -------- World Settings For [DXL_Edit_0] --------
[16:22:27] [Server thread/INFO]: Mob Spawn Range: 8
[16:22:27] [Server thread/INFO]: Experience Merge Radius: 3.0
[16:22:27] [Server thread/INFO]: View Distance: 10
[16:22:27] [Server thread/INFO]: Max TNT Explosions: 100
[16:22:27] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[16:22:27] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[16:22:27] [Server thread/INFO]: Item Despawn Rate: 6000
[16:22:27] [Server thread/INFO]: Item Merge Radius: 2.5
[16:22:27] [Server thread/INFO]: Arrow Despawn Rate: 1200
[16:22:27] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[16:22:27] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[16:22:27] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[16:22:27] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[16:22:27] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true
[16:22:27] [Server thread/INFO]: Cactus Growth Modifier: 100%
[16:22:27] [Server thread/INFO]: Cane Growth Modifier: 100%
[16:22:27] [Server thread/INFO]: Melon Growth Modifier: 100%
[16:22:27] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[16:22:27] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[16:22:27] [Server thread/INFO]: Sapling Growth Modifier: 100%
[16:22:27] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[16:22:27] [Server thread/INFO]: Carrot Growth Modifier: 100%
[16:22:27] [Server thread/INFO]: Potato Growth Modifier: 100%
[16:22:27] [Server thread/INFO]: Wheat Growth Modifier: 100%
[16:22:27] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[16:22:27] [Server thread/INFO]: Vine Growth Modifier: 100%
[16:22:27] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[16:22:27] [Server thread/INFO]: Bamboo Growth Modifier: 100%
[16:22:27] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
[16:22:27] [Server thread/INFO]: Kelp Growth Modifier: 100%
[16:22:27] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313Ocean: 14357621 Shipwreck: 165745295 Slime: 987234911
[16:22:30] [Server thread/INFO]: BearLeon issued server command: /dxl leave
[16:22:30] [Server thread/ERROR]: Could not pass event DPlayerLeaveDGroupEvent to Quests v3.7.6-b5
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at de.erethon.dungeonsxl.command.LeaveCommand.onExecute(LeaveCommand.java:77) ~[?:?]
        at de.erethon.dungeonsxl.util.commons.command.DRECommandExecutor.onCommand(DRECommandExecutor.java:67) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:710) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1641) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1481) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:910) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:903) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:887) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:820) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.NullPointerException
        at me.blackvein.quests.listeners.DungeonsListener.onPlayerLeaveEvent(DungeonsListener.java:50) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        ... 23 more
[16:22:31] [Server thread/WARN]: [Multiverse-Core] Hmm Multiverse does not know about this world but it's loaded in memory.
[16:22:31] [Server thread/WARN]: [Multiverse-Core] To let Multiverse know about it, use:
[16:22:31] [Server thread/WARN]: [Multiverse-Core] /mv import DXL_Edit_0 NORMAL
[16:22:31] [Server thread/INFO]: ThreadedAnvilChunkStorage (DXL_Edit_0): All chunks are saved

**Comment by BearLeonLight** [comment]
Is it possible to allow NULL when it is possible to get the player again?
Player cannot be NULL, but return NULL
I have only a few studies on JAVA, and I am very clear about the complete JAVA syntax from time to time.
Maybe it should be changed

if(event.getDGroup().getCaptain()!=null&&event.getDPlayer().getPlayer()!=null){
Player k = event.getDGroup().getCaptain();
Player p = event.getDPlayer().getPlayer();
}

**Comment by BearLeonLight** [comment]
Sorry to close the question by @@.

**Comment by BearLeonLight** [comment]
So what should I do?
