### ISSUE TITLE
Error at the end of the Quest

### ISSUE THREAD

**Issue by Atlantiis31** [PikaMug/Quests#892]
Hi,

When a player finish a quest there is a console error message :

LOG:

```
[19:06:50] [Server thread/ERROR]: [Quests] An error has occurred with Quests. Please report on Github. Include the info below
[19:06:50] [Server thread/WARN]: [Quests] index = 0
[19:06:50] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to Quests v3.7.8-b16
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1613]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1613]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1613]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1613]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:697) ~[patched_1.12.2.jar:git-Paper-1613]
	at net.minecraft.server.v1_12_R1.PacketPlayInFlying.a(SourceFile:126) ~[patched_1.12.2.jar:git-Paper-1613]
	at net.minecraft.server.v1_12_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) ~[patched_1.12.2.jar:git-Paper-1613]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1613]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_212]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1613]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1613]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1613]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1613]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1613]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NullPointerException
	at me.blackvein.quests.Quester.reachLocation(Quester.java:1721) ~[?:?]
	at me.blackvein.quests.listeners.PlayerListener.onPlayerMove(PlayerListener.java:864) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor805.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1613]
	... 15 more
```

Example quest:
```
  mission6:
    name: Rôtisserie
    ask-message: §6§nAccomplissez dans l'ordre:§7 Tuer 100 Poules...
    finish-message: ''
    requirements:
      permissions:
      - niveau.1
      fail-requirement-message: §8[§4✘§8] §cVous devez être Niveau 1 pour effectuer
        cette Mission.
    stages:
      ordered:
        '1':
          mobs-to-kill:
          - chicken
          mob-amounts:
          - 100
          death-event: DeathFail
        '2':
          locations-to-reach:
          - world 7.0 70.0 7.0
          reach-location-radii:
          - 3
          reach-location-names:
          - Spawn
          death-event: DeathFail
          objective-override: §7Retourner au Spawn
    rewards:
      commands:
      - pex user <player> add mission.6
      - pvplevels message <player> &8[&2✔&8] &7Mission &5Rôtisserie &7Terminée ! Félicitations
        !
      - recompense1 <player>
      - bc &6<player> &7a terminé la mission &5Rôtisserie &7!
      commands-override-display:
      - ''
    options:
      allow-commands: true
      use-dungeonsxl-plugin: false
      use-parties-plugin: true
```

I don't know what is the problem, it appear since last update.

Thanks for your help !

**Comment by Atlantiis31** [comment]
Hi, 
Any news about the problem please ? 

Thanks'

**Comment by PikaMug** [comment]
This was caused by your quest having 3 command rewards, but only 1 command display override. You should either have as many overrides as you do commands, or none at all.

Using this build will resolve the error, but unless you fix what I just mentioned, rewards may not appear as desired at the end of your quest:
https://ci.codemc.org/job/PikaMug/job/Quests/24/
