### ISSUE TITLE
Java errors on 1.8.8

### ISSUE THREAD

**Issue by tiradorus** [PikaMug/Quests#925]
**What is your Quests version / build number (do _not_ say "latest")?**

 Quests v3.7.8-b16
Minecraft 1.8.8

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Sometimes, quests do some Java errors. I don't know how to replicate it and i don't know why it occurs

```
15:58:22: Could not pass event NPCRightClickEvent to Quests v3.7.8-b16
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:385) [citizens-2.0.16-SNAPSHOT.jar:?]
at sun.reflect.GeneratedMethodAccessor268.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1315) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[?:1.8.0_181]
at java.util.ArrayList.get(ArrayList.java:433) ~[?:1.8.0_181]
at me.blackvein.quests.Quest.completeQuest(Quest.java:630) ~[?:?]
at me.blackvein.quests.Quest.nextStage(Quest.java:187) ~[?:?]
at me.blackvein.quests.Quester.finishObjective(Quester.java:1989) ~[?:?]
at me.blackvein.quests.Quester.interactWithNPC(Quester.java:1661) ~[?:?]
at me.blackvein.quests.listeners.NpcListener.onNPCRightClick(NpcListener.java:167) ~[?:?]
at sun.reflect.GeneratedMethodAccessor269.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
... 23 more
```

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

**Comment by PikaMug** [comment]
Thanks for the report. Please give the latest dev build a try and let me know if it resolves the issue:
https://ci.codemc.org/job/PikaMug/job/Quests/27/

**Warning:** The build linked above is experimental. Make sure to back up your Quests folder before attempting to use it.

**Comment by PikaMug** [comment]
Closing due to lack of response from OP.
