### ISSUE TITLE
Java errors on 1.8.8 made by Quests 3.8.0

### ISSUE THREAD

**Issue by tiradorus** [PikaMug/Quests#960]
**What is your Quests version / build number (do _not_ say "latest")?**
Quest Version: Quests **3.8.0**
Minecraft Server Version: **1.8.8**
**Spigot.**

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Java errors on 1.8.8. appear when you try to edit Rewards of a quest (12)
The rewards menu isn't shown, and you can't see what are you doing.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
Allright, it's the same with Every quests
```
  Journa4:
    name: Journalière4 - Envahisseurs!
    ask-message: Temporaire
    finish-message: Quête 4 du Canyon des Kerzians terminée
    stages:
      ordered:
        '1':
          custom-objectives:
            custom1:
              name: Kill MythicMobs Objective
              count: 15
              data:
                Objective Name: |-
                  §4(§c§M=§4§l Objectif §4§m=§c)
                  §cTuer §6§l15 §cEnvahisseur Kashian

                  §5(§d§M=§5§l Localisation §d§m=§5)
                  §dCanyon des Kerzians

                  §1(§9§M=§1§l Avancement §9§m=§1)
                  §3%count% §9Tués
                Conditions: NONE
                TargetConditions: NONE
                Internal Mobnames: QueteDesert1
                Mob Level: '0'
                Mob Faction: ANY
                Notifier enabled: 'true'
                Notifier msg: §f[§a %c% §f] §6mobs tués sur §f[§c %s% §f]
    rewards:
      money: 5000
      commands:
      - scoreboard players add <player> Canyonquetes 1
      - scoreboard players add <player> canyon 1
      - scoreboard players add <player> progression 1
      - mycmd-runas player <player> /canyon3
      commands-override-display:
      - ''
    options:
      allow-commands: true
      allow-quitting: true
      use-dungeonsxl-plugin: false
      use-parties-plugin: true
      share-progress-level: 1
```

**Comment by PikaMug** [comment]
Thanks for your report. Please provide a copy of the console error.

**Comment by tiradorus** [comment]
Wow i didn't have paste the java errors oO
First time i forget something like that xD
I'll check the LOGS...
Here we are!

```
[12:52:45] [Server thread/INFO]: tiradorus issued server command: /quests editor
[12:53:05] [Server thread/ERROR]: Error handling conversation prompt
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[?:1.8.0_181]
	at java.util.ArrayList.get(ArrayList.java:433) ~[?:1.8.0_181]
	at me.blackvein.quests.prompts.RewardsPrompt.getAdditionalText(RewardsPrompt.java:169) ~[?:?]
	at me.blackvein.quests.prompts.RewardsPrompt.getPromptText(RewardsPrompt.java:261) ~[?:?]
	at org.bukkit.conversations.Conversation.outputNextPrompt(Conversation.java:291) ~[minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:230) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:58) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1029) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerConnection$5.evaluate(PlayerConnection.java:1011) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.util.Waitable.run(Waitable.java:24) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:729) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[12:53:10] [Async Chat Thread - #0/INFO]: <tiradorus> 15
```

**Comment by PikaMug** [comment]
This is caused by your quest not having as many command override displays as it does commands. What you have here...

```
      commands:
      - scoreboard players add <player> Canyonquetes 1
      - scoreboard players add <player> canyon 1
      - scoreboard players add <player> progression 1
      - mycmd-runas player <player> /canyon3
      commands-override-display:
      - ''
```

...should probably look like...
```
      commands:
      - scoreboard players add <player> Canyonquetes 1
      - scoreboard players add <player> canyon 1
      - scoreboard players add <player> progression 1
      - mycmd-runas player <player> /canyon3
      commands-override-display:
      - ''
      - ''
      - ''
```

I'll update the plugin so the way you've done it will work too (overriding just the first command), but you should make the change above if you're trying to hide all commands.
